### ISSUE TITLE
"Id is missing" on subscription creation (POST /subscriptions)

### ISSUE THREAD

**Issue by MS-Fiware** [ScorpioBroker/ScorpioBroker#1]
Hi,

when trying to create a subscription with POST /subscriptions I get a "500 Internal Server Error" in the HTTP response, although the [spec](https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.01.01_60/gs_CIM009v010101p.pdf) states that at creation time the id is optional and is assigned during subscription process, if not provided.

My request:

`curl -X POST \
  http://192.168.57.101:9090/ngsi-ld/v1/subscriptions \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "description": "Notify me of all air quality level changes",
    "entities": [
        {
            "idPattern": ".*",
            "type": "AirQualityObserved"
        }
    ],
    "watchedAttributes": [
        "airQualityLevel"
    ],
    "notification": {
        "attributes": [
            "id",
            "type",
            "airQualityLevel"
        ],
        "format": "keyValues",
        "endpoint": {
            "uri": "http://localhost:8080/subscription/air-quality-level-change",
            "accept": "application/ld+json"
        }
    },
    "@context": [
        "https://schema.lab.fiware.org/ld/context",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}'`

The response body:

`{
    "timestamp": "2019-09-30T15:32:44.970+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "Id is missing",
    "path": "/"
}`

When providing the id attribute, the subscription is created successfully and the id is returned in the response body.

I tested with the initial commit https://github.com/ScorpioBroker/ScorpioBroker/commit/b7df1f84802dde5af3065dd4296c640ce8414c06.

Greetings,
Michael

**Comment by ScorpioBroker** [comment]
Fixed in the latest commit. (De)Serialization was a bit to tight here.
