### ISSUE TITLE
csource registration subscription without 'watchedAttributes' attribute can not be retrieved in list (GET /csourceSubscriptions)

### ISSUE THREAD

**Issue by michaeI-s** [ScorpioBroker/ScorpioBroker#12]
Hi,

when creating a csource registration subscription without the 'watchedAttributes' attribute (which is optional and can be undefined -> meaning all possible attributes in the csource registrations for matching entities match) and trying afterwards to retrieve that created subscription within a list (GET /csourceSubscriptions) I get a "500 Internal Server Error" in the HTTP response.
On the contrary, trying to get this single csource registration subscription will succeed, if directly requested by subscription Id (GET /csourceSubscriptions/{subscriptionId}). 
After patching the subscription to include 'watchedAttributes', it can be retrieved again by requesting GET /csourceSubscriptions.

My request for the csource registration subscription:

```
curl -X POST \
  http://192.168.57.101:9090/ngsi-ld/v1/csourceSubscriptions \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Subscription:MyAwesomeCsourceSubscription",
    "type": "Subscription",
    "description": "Notifies me of all context source registrations potentially providing information for AirQualityObserved entities I'\''m interested in",
    "entities": [
        {
            "idPattern": ".*",
            "type": "AirQualityObserved"
        }
    ],
    "notification": {
        "attributes": [
            "airQualityLevel",
            "dateObserved"
        ],
        "format": "keyValues",
        "endpoint": {
            "uri": "http://localhost:8080/csource-subscription/air-quality-observed-csource",
            "accept": "application/ld+json"
        }
    },
    "@context": [
        "https://schema.lab.fiware.org/ld/context",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}'
```

The response body for the csource registration subscription:

```
"urn:ngsi-ld:Subscription:MyAwesomeCsourceSubscription"
```

My request for retrieving the csource registration subscription list:

```
curl -X GET \
  http://192.168.57.101:9090/ngsi-ld/v1/csourceSubscriptions \
  -H 'Accept: application/ld+json' \
  -H 'Link: <https://schema.lab.fiware.org/ld/context>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' 
```

The response body for the csource registration subscription:

```
{
    "timestamp": "2019-10-05T09:38:33.779+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "No message available",
    "path": "/ngsi-ld/v1/csourceSubscriptions"
}
```

I tested with the latest commit https://github.com/ScorpioBroker/ScorpioBroker/commit/d1f7c9a8349bcd491cda8e9f2a226fc3decdbd99.

Greetings,
Michael

**Comment by ScorpioBroker** [comment]
Hi is fixed.

**Comment by michaeI-s** [comment]
Thank you!
