### ISSUE TITLE
Missing Release Tags on GitHub

### ISSUE THREAD

**Issue by jason-fox** [ScorpioBroker/ScorpioBroker#133]
According to [this](https://github.com/ScorpioBroker/ScorpioBroker/tags) the last scorpio release was **FIWARE 7.8.2** there are missing release tags to align with Docker Hub

- `0.9.10` - should be a double tag of  **FIWARE 7.8.2** 
- `1.0.0` - missing
- `1.0.1` - missing.

Adding in these tags on GitHub is essential to track the releases of scorpio for the FIWARE catalogue.

**Comment by ScorpioBroker** [comment]
Hi,

I will add them. Should i tag releases on dockerhub in between fiware releases also with the then current fiware tag? 
Is the underscore we have in the release ok or should be a space?
So FIWARE_7.8.2 or FIWARE 7.8.2
BR

**Comment by jason-fox** [comment]
`FIWARE_7.8.2` is only to mark the version included at the time of the FIWARE release - you don't need to add the tag to your interim releases. And it uses underscore.

**Comment by ScorpioBroker** [comment]
Ok great. I added the tag on dockerhub.

BR
Benni
