### ISSUE TITLE
resource URI of the created subscription found in body

### ISSUE THREAD

**Issue by jason-fox** [ScorpioBroker/ScorpioBroker#138]
I am creating a subscription as shown:

```console
curl -L -X POST 'http://localhost:9090/ngsi-ld/v1/subscriptions/' \
-H 'Content-Type: application/ld+json' \
--data-raw '{
	"description": "Notify me of low stock in Store 001",
	"type": "Subscription",
	"entities": [{"type": "Shelf"}],
	"watchedAttributes": ["numberOfItems"],
	"q": "numberOfItems<10;locatedIn==urn:ngsi-ld:Building:store001",
	"notification": {
		"attributes": ["numberOfItems", "stocks", "locatedIn"],
		"format": "keyValues",
		"endpoint": {
			"uri": "http://tutorial:3000/subscription/low-stock-store001",
			"accept": "application/json"
		}
	},
   "@context": "https://fiware.github.io/tutorials.Step-by-Step/tutorials-context.jsonld"
} '
```

The subscription is created successfully and returns HTTP Code 201 ✅ 

However the response *body* returns a plain text response ❌ 

```text
urn:ngsi-ld:Subscription:1043620979
```

According to the 1.3.1 specification
**Table 6.12.3.1-1: Post Context Source Registration Subscription request body
and possible responses**

|  Response Codes  | Remarks | 
| --- | ---|
| 201 | Created Upon success, the HTTP response shall include a "Location" HTTP header that contains the resource URI of the created context source registration subscription resource. |

Note that the `LOCATION` Header is returned as well, it's just this shouldn't appear in the body. Tested on Scorpio *1.0.1*

**Comment by ScorpioBroker** [comment]
Fixed & merged to dev
