### ISSUE TITLE
Unable to list registrations

### ISSUE THREAD

**Issue by jason-fox** [ScorpioBroker/ScorpioBroker#139]
I create a Registration:

```console
curl -L -X POST 'http://localhost:9090/ngsi-ld/v1/csourceRegistrations/' \
-H 'Content-Type: application/json' \
-H 'Link: <https://fiware.github.io/tutorials.Step-by-Step/tutorials-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw ' {
    "type": "ContextSourceRegistration",
    "information": [
        {
            "entities": [
                {
                    "type": "Building",
                    "id": "urn:ngsi-ld:Building:store001"
                }
            ],
            "properties": [
                "tweets"
            ]
        }
    ],
    "endpoint": "http://context-provider:3000/static/tweets"
}'
```

Broker returns HTTP 201 Created  ✅ 

I then attempt to retrieve the list of registrations:

```console
curl -L -X GET 'http://localhost:9090/ngsi-ld/v1/csourceRegistrations/' \
-H 'Accept: application/ld+json' \
-H 'Link: <https://fiware.github.io/tutorials.Step-by-Step/tutorials-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"'
```

The Broker returns an error response ❌ 

```jsonld
{
    "type": "http://uri.etsi.org/ngsi-ld/errors/BadRequestData",
    "title": "Bad Request Data.",
    "details": "You must provide at least type or attrs as parameter"
}
```

I would expect the registration to be returned. The specification **Table 6.8.3.2-1: Query parameters** does not list `type` or `attrs` as mandatory attributes.

Scorpio _v1.0.1_

Note that if I copy the registration id direct from the `Location` header (e.g. `/ngsi-ld/v1/csourceRegistrations/urn:ngsi-ld:csourceregistration:-144018168`) the data is returned as expected.

**Comment by ScorpioBroker** [comment]
Hmm. True that's a bug. I guess we took that over from the queries table somehow. Will take care of it.

**Comment by ScorpioBroker** [comment]
Hi Jason, 

i checked our code we have a comment there refering to 5.10.2.4 in the spec which says that attrs or type is required. I think the table needs to be updated. @martin-p-bauer can you verify this.

**Comment by ScorpioBroker** [comment]
Hi,

i talked with Martin and he confirmed that 5.10.2.4 is valid and that the table should be updated. 
I'd close here for now.

BR
