### ISSUE TITLE
Java 11 support

### ISSUE THREAD

**Issue by Glagnar** [ScorpioBroker/ScorpioBroker#14]
There is an issue with newer versions of Java, but it is very easy to solve:
https://crunchify.com/java-11-and-javax-xml-bind-jaxbcontext/

I added:
```xml
<dependency>
	<groupId>com.sun.xml.bind</groupId>
	<artifactId>jaxb-core</artifactId>
	<version>2.3.0.1</version>
</dependency>
<dependency>
	<groupId>javax.xml.bind</groupId>
	<artifactId>jaxb-api</artifactId>
	<version>2.3.1</version>
</dependency>
<dependency>
	<groupId>com.sun.xml.bind</groupId>
	<artifactId>jaxb-impl</artifactId>
	<version>2.3.1</version>
</dependency>
```
To the pom.xml and everything worked fine.

**Comment by MS-Fiware** [comment]
Good to see this pointed out here. I already created a pull request with an updated README.md addressing this issue. Hopefully it's going to be merged soon.

**Comment by ScorpioBroker** [comment]
Hi,

i merged the documentation. I will look into updating the pom file for the support of java 11.

Thanks & Regards
Benjamin

**Comment by MS-Fiware** [comment]
Thanks again for quick reaction times. :)

**Comment by ScorpioBroker** [comment]
Hi to give a final update here i've added a jdk depended profile in the build of the eureka server providing jaxb if the jdk 9 or bigger.
