### ISSUE TITLE
Obtaining Data from a simple context provider.

### ISSUE THREAD

**Issue by jason-fox** [ScorpioBroker/ScorpioBroker#140]
When using the following [docker-compose](https://github.com/FIWARE/tutorials.LD-Subscriptions-Registrations/blob/master/docker-compose/scorpio-aaio.yml). For the CSource registration created here:

```console
curl -L -X POST 'http://localhost:9090/ngsi-ld/v1/csourceRegistrations/' \
-H 'Content-Type: application/json' \
-H 'Link: <https://fiware.github.io/tutorials.Step-by-Step/tutorials-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw ' {
    "type": "ContextSourceRegistration",
    "information": [
        {
            "entities": [
                {
                    "type": "Building",
                    "id": "urn:ngsi-ld:Building:store001"
                }
            ],
            "properties": [
                "tweets"
            ]
        }
    ],
    "endpoint": "http://context-provider:3000/static/tweets"
}'
```

I would expect that I have registered the attribute `tweets` to be read from `http://context-provider:3000`.

When I read the Entity:  `urn:ngsi-ld:Building:store001`

```console
curl -L -X GET 'http://localhost:9090/ngsi-ld/v1/entities/urn:ngsi-ld:Building:store001' \
-H 'Link: <https://fiware.github.io/tutorials.Step-by-Step/tutorials-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
-H 'Content-Type: application/json'
```

I would expect `tweets` to be present, or at least some interaction to be observed at  `context-provider` - I do not.

**Comment by jason-fox** [comment]
To be honest, this is more or a placeholder than a real issue. My understanding of NGSI-LD context-providers can be found [here](https://github.com/FIWARE/tutorials.LD-Subscriptions-Registrations/blob/master/README.md#using-registrations-with-ngsi-ld) and this is how Orion-LD works.  What I'm trying to find out is how to get this working with both Scorpio and Orion-LD using the same provisioning commands.

**Comment by ScorpioBroker** [comment]
Hi,
yeah i can see where you are coming from there.  A query with id=urn:ngsi-ld:Building:store001 and type=Building would do what you expect here.
But the /entities/{entityId} part is rather strict REST and only works on the local resource in all CRUD cases. So it will only ask for a local resource on get. 

Basically from a REST point of view we are doing the correct thing here but i can also see why this is not directly obvious. The NGSILD spec isn't explicit here from what i checked. In terms of REST consistency i would say we are doing it correct.

**Comment by jason-fox** [comment]
> The NGSILD spec isn't explicit here 

Precisely - your interpretation of the "holy book" may differ from @kzangeli here, until the spec clarifies this we're going to have to work together to maintain interoperability.

I've tried   `entities/?id=urn:ngsi-ld:Building:store001&type=Building` and I've tried  `/urn:ngsi-ld:Building:store001`  and I still can't get it to work. Could you have a look at [the tutorial](https://github.com/FIWARE/tutorials.LD-Subscriptions-Registrations) run

```console
./services scorpio
``` 

and see if the debug makes sense to you?


The sort of thing I'm getting in the log is:


```text
020-09-25 16:26:52.275  INFO 53 --- [ool-76-thread-1] e.n.n.commons.storage.StorageReaderDAO   : NGSI-LD to SQL: SELECT data_without_sysattrs as data FROM entity WHERE id = 'urn:ngsi-ld:Building:store001' AND type = 'https://uri.fiware.org/ns/data-models#Building' AND  1=1 LIMIT 50 OFFSET 0 
2020-09-25 16:26:52.296  INFO 53 --- [ool-76-thread-2] e.n.n.commons.storage.StorageReaderDAO   : NGSI-LD to SQL: SELECT DISTINCT c.data FROM csource c INNER JOIN csourceinformation ci ON (ci.csource_id = c.id) WHERE (c.internal = false) AND ((c.has_registrationinfo_with_attrs_only) OR ((ci.entity_type = 'https://uri.fiware.org/ns/data-models#Building' AND ci.entity_id IS NULL AND ci.entity_idpattern IS NULL) OR ( ci.entity_type = 'https://uri.fiware.org/ns/data-models#Building' AND (ci.entity_id = 'urn:ngsi-ld:Building:store001' OR 'urn:ngsi-ld:Building:store001' ~ ci.entity_idpattern) ))) AND  1=1 
java.lang.IllegalStateException: No match found
at java.util.regex.Matcher.group(Matcher.java:536)
at eu.neclab.ngsildbroker.queryhandler.services.QueryService$2.call(QueryService.java:366)
at eu.neclab.ngsildbroker.queryhandler.services.QueryService$2.call(QueryService.java:349)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
2020-09-25 16:26:52.545 ERROR 53 --- [ool-76-thread-2] e.n.n.q.services.QueryService            : No reply from registry. Looks like you are running without a context source registry.
2020-09-25 16:26:52.545 ERROR 53 --- [ool-76-thread-2] e.n.n.q.services.QueryService            : No match found
2020-09-25 16:27:18.817  INFO 53 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2020-09-25 16:28:30.515  INFO 53 --- [ool-77-thread-1] e.n.n.commons.storage.StorageReaderDAO   : NGSI-LD to SQL: SELECT data_without_sysattrs as data FROM entity WHERE id = 'urn:ngsi-ld:Building:store001' AND  1=1 LIMIT 50 OFFSET 0 
2020-09-25 16:28:30.516  INFO 53 --- [ool-77-thread-2] e.n.n.commons.storage.StorageReaderDAO   : NGSI-LD to SQL: 
2020-09-25 16:28:30.555  WARN 53 --- [ool-77-thread-2] e.n.n.commons.storage.StorageReaderDAO   : SQL Result Exception::
2020-09-25T16:28:30.581084600Z 
org.springframework.dao.DataIntegrityViolationException: StatementCallback; SQL []; No results were returned by the query.; nested exception is org.postgresql.util.PSQLException: No results were returned by the query.
at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104) ~[spring-jdbc-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72) ~[spring-jdbc-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
```

**Comment by jason-fox** [comment]
The registration is:

```jsonld
{
    "id": "urn:ngsi-ld:csourceregistration:619196684",
    "type": "ContextSourceRegistration",
    "endpoint": "http://context-provider:3000/static/tweets",
    "information": {
        "entities": [
            {
                "id": "urn:ngsi-ld:Building:store001",
                "type": "https://uri.fiware.org/ns/data-models#Building"
            }
        ],
        "properties": "https://fiware.github.io/tutorials.Step-by-Step/schema/tweets",
        "ngsi-ld:relationships": []
    },
    "ngsi-ld:internal": false,
    "@context": [
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}
```

**Comment by martin-p-bauer** [comment]
I fear we have not explicitly documented the implementation assumptions we made for distributed operation (or at least not in an easy to find way). the NGSI-LD specification defines only the API and enables different deployment architectures, but it does not completely describe all details of the system, i.e. there are still design decisions to be made. For the central Broker case, without additional sources, the design decisions should be straightforward and we strive for complete compatibility here. For distributed/federated cases this is more problematic as there are significantly different underlying assumptions.

We took the decision that (at least for now), all management operations and also the retrieve operation only apply locally (i.e they are executed based on the DB of the Broker only without considering registrations), whereas queries and subscriptions have global scope. In this case the query entities/?id=urn:ngsi-ld:Building:store001&type=Building should provide the correct result (if it doesn't, it is a bug), whereas  /urn:ngsi-ld:Building:store001 would not provide anything if the entity does not locally exist or, if it exists, only the local information would be provided.

There are different aspects behind this decision and the most important one for NEC is to be able to scale the system and to federate different existing deployments without having to re-engineer or really touch the original ones. For scaling large systems. it is important to be able to have coarse-grained registrations, i.e. on federation level you cannot change the registration with any new entity being added or removed in some local system, thus you can have type-based registration, i.e. you only put the available types and/or attributes in the registration, but not the entity ids. In turn, this means that there is no way to efficiently retrieve  /urn:ngsi-ld:Building:store001 as you would have to query (transitively) every context source (which could be full brokers) in the system and do so in every single case, so something that is perceived as a simple entity retrieval in reality can become a super expensive operation. (I don't think Orion-LD considers type-based registrations right now.) 

In queries you have to specify at least the type (or attribute) thus, unlike in the above case, we can match that to registrations, i.e. do not have to ask EVERY context source in the system, For truly large systems we may in addition require a limited (geographical) scope in queries and subscriptions in the future - but this has not been implemented yet.
 
Having said that, we are considering a "FIWARE compatibility mode", primarily to support IoT Agent actuation, i.e. forward updates required to trigger actuations - and we could do the same for retrieval - in both cases only given that the registration contains the entity id.

**Comment by ScorpioBroker** [comment]
Hi,

aside from the architectural part there was indeed a problem with our regex for the endpoint here. I fixed it and will create a PR soon.

**Comment by jason-fox** [comment]
To take @martin-p-bauer 's points one-by-one:

> `/?id=urn:ngsi-ld:Building:store001&type=Building` should provide the correct result (if it doesn't, it is a bug)

I can confirm that when I am testing  with *v1.0.1* `/?id=urn:ngsi-ld:Building:store001&type=Building` isn't working for me - not sure if @ScorpioBroker has fixed it with the patch.

> `/?id=urn:ngsi-ld:Building:store001&type=Building` vs `/urn:ngsi-ld:Building:store001`

I see what you are getting at (local vs forward + local), but this needs to be formally defined in the spec somewhere so all brokers can follow the same paradigm. Maybe a runtime flag? Maybe a query parameter? Who knows?

As it happens, it *Orion-LD* currently implements forwarding on `/urn:ngsi-ld:Building:store001` and not yet on`/?id=urn:ngsi-ld:Building:store001&type=Building` - the opposite way round to *Scorpio* 😠 

In NGSI-v2, Orion "classic" implements forwarding on both `/urn:ngsi-ld:Building:store001` and `/?id=urn:ngsi-ld:Building:store001&type=Building` 

and I'm not sure what Stellio is doing here, but it is fair to say we have a range of views on this. issue 😃

**Comment by ScorpioBroker** [comment]
Hi,
just for completeness the patch will be in the release on Friday. It will take care of the query problem.

Having a different default on retrieve is indeed a problem. 
From a implementation point of view we can easily support a flag without much problems. 

As this is directly related to the update to iot agents, in the sense that it both affects the .../{entityId} resource handling we should be consistent in the approach to both in terms of flags and default behaviour in cooperation with the registry.

**Comment by ScorpioBroker** [comment]
Hi,
the bug is fixed now. 
I'll close here now let's take the other issues to email and discuss them.

**Comment by djs0109** [comment]
Hi,
I try to follow the [tutorial ](https://github.com/FIWARE/tutorials.LD-Subscriptions-Registrations) with scorpio broker. However, I can not get data from `context provider` with or without the above workaround. Is this tutorial still updated? Or maybe there are other tutorials for this topic?

**Comment by djs0109** [comment]
I may have found the problem. Scorpio Broker does send a request to `context provider`, but all colon `:` are encoded, i.g. replaced with `%3A`. 

`GET /static/tweets/ngsi-ld/v1/entities?type=Building&id=urn%3Angsi-ld%3ABuilding%3Astore001 501 1.900 ms - 171`

The `context provider` can not handle such a request. @jason-fox do you see this as an issue of the tutorial or it is an issue of the scorpio broker?

**Comment by jason-fox** [comment]
> The context provider can not handle such a request

As stated previously, the tutorial context provider is not a full context broker and only implements a subset of the NGSI-LD spec. When written it worked against the experimental Orion-LD interface developed as input for the FIWARE Foundation's recommendations for the  NGSI-LD 1.5.1 release. Since then 1.6.1 has clarified the expected behaviour of partial brokers.

If you look at the [code](https://github.com/FIWARE/tutorials.NGSI-LD/blob/master/app/routes/proxy-ld.js#L134) you'll see that `/static/tweets/ngsi-ld/v1/entities/<id>` is serviced, but `/static/tweets/ngsi-ld/v1/entities/` is not handled. Now that the 1.6.1. has clarified things maybe it should or maybe the `operations` array should be limited to `retrieveOp`.

Both Orion-LD and Scorpio made conflicting presuppositions about registrants. Scorpio assumed a registrant was a federating full context broker,  Orion-LD  a registrant was an IoT Agent with limited interfaces.

It is a little bit chicken-and-egg, once a broker implements 1.6.1 Distributed Operations according to spec, the tutorial registrant code can be updated to offer a partial broker  according to spec and everyone can align.
