### ISSUE TITLE
"Not Found" on batch entity creation (POST /entityOperations/create)

### ISSUE THREAD

**Issue by MS-Fiware** [ScorpioBroker/ScorpioBroker#15]
Hi,

when trying to do a batch entity creation with POST /entityOperations/create I get a "404 Not Found" in the HTTP response.

My request:

```bash
curl -X POST \
  http://192.168.57.101:9090/ngsi-ld/v1/entityOperations/create \
  -H 'Content-Type: application/ld+json' \
  -d '[
    {
        "id": "urn:ngsi-ld:testunit:124",
        "type": "AirQualityObserved",
        "dateObserved": {
            "type": "Property",
            "value": {
                "@type": "DateTime",
                "@value": "2018-08-10T12:00:00Z"
            }
        },
        "NO2": {
            "type": "Property",
            "value": 23,
            "unitCode": "GP",
            "accuracy": {
                "type": "Property",
                "value": 0.95
            }
        },
        "refPointOfInterest": {
            "type": "Relationship",
            "object": "urn:ngsi-ld:PointOfInterest:RZ:TrainStation"
        },
        "@context": [
            "https://schema.lab.fiware.org/ld/context",
            "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
        ]
    },
    {
        "id": "urn:ngsi-ld:testunit:125",
        "type": "AirQualityObserved",
        "dateObserved": {
            "type": "Property",
            "value": {
                "@type": "DateTime",
                "@value": "2018-08-12T12:00:00Z"
            }
        },
        "NO2": {
            "type": "Property",
            "value": 21,
            "unitCode": "GP",
            "accuracy": {
                "type": "Property",
                "value": 0.95
            }
        },
        "refPointOfInterest": {
            "type": "Relationship",
            "object": "urn:ngsi-ld:PointOfInterest:RZ:HarbourDistrict"
        },
        "@context": [
            "https://schema.lab.fiware.org/ld/context",
            "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
        ]
    }
]'
```

The response body:

```bash
{
    "timestamp": "2019-10-07T18:04:20.632+0000",
    "status": 404,
    "error": "Not Found",
    "message": "No message available",
    "path": "/ngsi-ld/v1/entityOperations/create"
}
```

Are batch operations not yet implemented?

I tested with commit https://github.com/ScorpioBroker/ScorpioBroker/commit/d1f7c9a8349bcd491cda8e9f2a226fc3decdbd99.

Greetings,
Michael

**Comment by ScorpioBroker** [comment]
Hi,

no batch operations are currently not in yet as they were one of the later additions.
Since they basically an array wrapping around input and output i don't forsee much problems for the implementation (famous last words)  and will add them soon.

Best Regards
Benjamin

**Comment by jmcanterafonseca** [comment]
is the error response compliant with the specification?

**Comment by MS-Fiware** [comment]
> is the error response compliant with the specification?

Since this feature is not implemented yet, it's like a request for a resource which is not found on the server, so the specification can't be applied here. Hence a "404 Not Found" is OK I guess.

**Comment by ScorpioBroker** [comment]
Hi,

so i commited the initial implementation for the entity operations. All of them are present. As a heads up for HTTP return codes... the spec is a bit unclear here to me. In the diagrams it says always to return 200 ok but then also says in the table it could be 400 for failing. 
I did the following... if all your requests went through successful it's a 200. If all failed it's a 400 and if it's some failed and some are successful it's a 207 for Multistatus. This seems to be the most http complaint approach to me.

**Comment by MS-Fiware** [comment]
Hi,

these are great news! Finally batch operations made it into Scorpio. Great work! :)

Status code 207 sounds reasonable to me when there's the need for distinguishing between response codes. 

Regarding the "all failed" error case it should be differentiated. Status 400 should only be applied if something in the request URL / header / body is malformed or has an invalid structure.
An overall unsuccessful operation does not necessarily mean that there was some format error. It can have several other reasons, e.g. any 5xx reason. So the spec might need an update in this regard.

Greetings,
Michael

**Comment by ScorpioBroker** [comment]
Hi,
yes you are right 400 might not be the best choice. I'll have a look if something like multi type errors exist and will update the impl. according to the next update of the spec when it's done. I'll close this for now. 
Just as a final remark. For this to work the gateway has to be rebuild since there is a new http resource mapping now.

Best Regards
Benjamin
