### ISSUE TITLE
Partial Attribute Update not triggering subscription notifications

### ISSUE THREAD

**Issue by idomingu** [ScorpioBroker/ScorpioBroker#155]
Hello everyone,

I'm new to ScorpioBroker and I just started playing with NGSI-LD subscriptions. I have seen that issuing a Partial Attribute Update on an attribute of a subscribed entity is not triggering notifications. However, an Update Entity Attributes operation for the same attribute does trigger a notification. My understanding of ETSI CIM 009 1.2.2 spec is that when any of the members of a watched attribute is updated with a new value, a new notification should be sent (5.8.6).

**Environment**
- scorpiobroker/scorpio:scorpio-aaio_1.0.2

**Steps to reproduce**

1.  Create subscription to watch attribute of an entity.
```
curl --location --request POST 'localhost:9090/ngsi-ld/v1/subscriptions/' \
--header 'Content-Type: application/ld+json' \
--header 'Link: <https://pastebin.com/raw/Mgxv2ykn>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw '{
	"type": "Subscription",
	"entities": [{
		"idPattern": ".*",
		"type": "Vehicle"
	}],
	"watchedAttributes": ["speed"],
	"notification": {
		"attributes": ["speed"],
		"format": "keyValues",
		"endpoint": {
			"uri": "http://consumer:8080/notify",
			"accept": "application/json"
		}
	}
}'
```
2. Create entity -> A notification is sent to the subscriber's endpoint
```
curl --location --request POST 'localhost:9090/ngsi-ld/v1/entities/' \
--header 'Content-Type: application/json' \
--header 'Accept: application/ld+json' \
--header 'Link: <https://pastebin.com/raw/Mgxv2ykn>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw '{
	"id": "urn:ngsi-ld:Vehicle:A100",
	"type": "Vehicle",
	"brandName": {
		"type": "Property",
		"value": "Mercedes"
	},
	"isParked": {
		"type": "Relationship",
		"object": "urn:ngsi-ld:OffStreetParking:Downtown1",
		"observedAt": "2017-07-29T12:00:04Z",
		"providedBy": {
			"type": "Relationship",
			"object": "urn:ngsi-ld:Person:Bob"
		}
	},
	"speed": {
		"type": "Property",
		"value": 80
	},
	"createdAt": "2017-07-29T12:00:04Z",
	"location": {
		"type": "GeoProperty",
		"value": {
			"type": "Point",
			"coordinates": [-8.5, 41.2]
		}
	}
}'
```
3. Partial Attribute Update of the watched attribute -> No notification is sent but the entity is successfully updated
```
curl --location --request PATCH 'localhost:9090/ngsi-ld/v1/entities/urn:ngsi-ld:Vehicle:A100/attrs/speed' \
--header 'Content-Type: application/json' \
--header 'Link: <https://pastebin.com/raw/Mgxv2ykn>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw '{
	"value": "100"
}'
```
4. Update Entity Attributes of the watched attribute -> Notification is sent and entity is successfully updated
```
curl --location --request PATCH 'localhost:9090/ngsi-ld/v1/entities/urn:ngsi-ld:Vehicle:A100/attrs' \
--header 'Content-Type: application/json' \
--header 'Link: <https://pastebin.com/raw/Mgxv2ykn>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw '{
	"speed": {
		"type": "Property",
		"value": "110"
	}
}'
```

**Comment by martin-p-bauer** [comment]
After a quick look, it seems that your understanding is correct and this is actually a bug. We will check it further and hopefully be able to fix it soon.

**Comment by tanktoo** [comment]
Hi, is there any progress on this yet? We are struggling with the same issue...

**Comment by rimi-itk** [comment]
We may have a fix in https://github.com/ScorpioBroker/ScorpioBroker/pull/166

**Comment by amitrnec** [comment]
Fixed this issue and merge into development branch.
