### ISSUE TITLE
Context sources and context information subscriptions

### ISSUE THREAD

**Issue by idomingu** [ScorpioBroker/ScorpioBroker#156]
Hello everyone,

I was wondering whether Scorpio supports context information subscriptions when subscribed entities are fully/partially provided by a context source. Standard GS CIM 009 1.3.1 points the following in clause 4.3.3:

> Context Consumers can query or subscribe to the Distribution Broker. On each request, the Distribution Broker discovers or does a discovery subscription to the Registry for relevant Context Sources, i.e. those that may provide context information relevant to the respective request from the Context Consumer. **The Distribution Broker then queries or subscribes to each relevant Context Source**, if possible it aggregates the context information retrieved from the Context Sources and provides them to the Context Consumer. In this mode of operation, it is not visible to the Context Consumer, whether the Broker is a Central Broker or a Distribution Broker. Alternatively, the architecture allows that Context Consumers can discover Context Sources through the Registry themselves and then directly request from Context Sources

I am facing a scenario where a Context Source provides information on the property of an entity. For queries, Scorpio successfully forwards the NGSI-LD Entity Query request to the Context Source, but when it comes to subscriptions I'm a bit confused. When a Context Consumer requests a subscription I would expect the Distribution Broker to forward the subscription request to the Context Source when the specified subscription's "entities" and "watchedAttributes" parameters result into a Context Source Discovery by the broker. 

Otherwise, how could be possible for Context Consumers to subscribe to attributes provided by Context Sources (apart from direct Consumer-Source communication)? The only way I can think of is by making the Context Source to act as a Context Producer, and thus make the broker trigger the notifications. However, this approach would require an external party to tell the Context Source to start updating the information from the broker.

Please correct me if I'm wrong, I probably misunderstood the issue as I haven't seen any reference to this within Scorpio documentation.

Many thanks in advance,

Nacho.

**Comment by martin-p-bauer** [comment]
Again I think your general understanding is correct. If you subscribe to a Distribution Broker and it has a registered Context Source that may have relevant information, the Distribution Broker will in turn subscribe to the Context Source, so the assumption is that Context Sources implement the subscription interface. In case the Distribution Broker receives a notification from the Context Source, this will be mapped to the original subscription from the Context Consumer and the notification will be forwarded to the Context Consumer.

Now, it seems that this is not working for you, but it is not very clearly described. Please note, that in NGSI-LD notifications can be value-based and time-based. In the value-based case, notifications are only sent as a result of changes, i.e only if there is a change regarding the entities or watched attributes a notification is sent - and as said above, this is the duty of the Context Source, the Distribution Broker is not polling. In the time-based case, a notification is expected after each time interval, independent of changes. The Distribution Broker will forward notifications from Context Sources to the right Context Consumer.

**Comment by idomingu** [comment]
Hello,

Thanks for your explanation. The issue I'm trying to describe is that once a Context Consumer subscribes to the Distribution Broker, then the Distribution Broker doesn't seem to subscribe to the Context Source that provides the information. As a result, the Context Source is left out of the subscription loop. Let me show an example:

**Environment**

- scorpiobroker/scorpio:scorpio-aaio_1.0.2

**Steps to reproduce**

1. Create entity
```bash
curl --location --request POST 'localhost:9090/ngsi-ld/v1/entities/' \
--header 'Content-Type: application/json' \
--header 'Accept: application/ld+json' \
--header 'Link: <https://pastebin.com/raw/Mgxv2ykn>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw '{
	"id": "urn:ngsi-ld:Vehicle:A100",
	"type": "Vehicle",
	"brandName": {
		"type": "Property",
		"value": "Mercedes"
	},
	"isParked": {
		"type": "Relationship",
		"object": "urn:ngsi-ld:OffStreetParking:Downtown1",
		"observedAt": "2017-07-29T12:00:04Z",
		"providedBy": {
			"type": "Relationship",
			"object": "urn:ngsi-ld:Person:Bob"
		}
	},
	"createdAt": "2017-07-29T12:00:04Z",
	"location": {
		"type": "GeoProperty",
		"value": {
			"type": "Point",
			"coordinates": [-8.5, 41.2]
		}
	}
}'
```
2. Register Context Source that provides information on "speed" property:
```bash
curl --location --request POST 'localhost:9090/ngsi-ld/v1/csourceRegistrations/' \
--header 'Content-Type: application/json' \
--header 'Accept: application/ld+json' \
--header 'Link: <https://pastebin.com/raw/Mgxv2ykn>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw '{
  "type": "ContextSourceRegistration",
  "name": "speedProvider",
  "description": "DescriptionExample",
  "information": [
    {
      "entities": [
        {
          "type": "Vehicle"
        }
      ],
      "properties": [
        "speed"
      ]
    }
  ],
  "endpoint": "http://provider:8080"
}'
```
3. Here we make sure context source is properly registered and that it provides the "speed" information by sending a "Query Entity" request to the Distribution Broker. **--->** Request _GET '/ngsi-ld/v1/entities?type=Vehicle_' is received by the Context Source and the "speed" information is successfully sent to the Distribution Broker, which in turn sends it to the Context Consumer.
```bash
curl --location --request GET 'localhost:9090/ngsi-ld/v1/entities?type=Vehicle' \
--header 'Content-Type: application/ld+json' \
--header 'Accept: application/ld+json' \
--header 'Link: <https://pastebin.com/raw/Mgxv2ykn>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"'
```

4. Context Consumer subscribes to the Distribution Broker for any "Vehicle" entity type and watches for changes upon property "speed".
```bash
curl --location --request POST 'localhost:9090/ngsi-ld/v1/subscriptions/' \
--header 'Content-Type: application/ld+json' \
--header 'Link: <https://pastebin.com/raw/Mgxv2ykn>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw '{
	"type": "Subscription",
	"entities": [{
		"type": "Vehicle"
	}],
	"watchedAttributes": ["speed"],
	"notification": {
		"format": "keyValues",
		"endpoint": {
			"uri": "http://consumer:8080/notify",
			"accept": "application/json"
		}
	}
}'
```
Subscription gets successfully created within the Distribution Broker, however, the Distribution Broker does not subscribe to the Context Source that provides the value of "speed". Besides, upon sending the subscription creation request, I do not see anything in the Scorpio logs. My point is, I do not understand what should be making the Distribution Broker trigger a subscription to the Context Source. From the above example, I would expect Scorpio to subscribe to the registered Context Source as it provides information for the watched attribute "speed".

Many thanks again for your help,

Cheers,
Nacho.

**Comment by martin-p-bauer** [comment]
Thank you for providing the example. We will check it in detail. In general, I think your understanding is correct, so this may be a bug, We will keep you updated and provide a fix if it turns out to be a bug.
