### ISSUE TITLE
Entity Subscription messages not stored in Kafka

### ISSUE THREAD

**Issue by idomingu** [ScorpioBroker/ScorpioBroker#157]
Hi everyone,

According to the [Entity Subscription flow](https://scorpio.readthedocs.io/en/latest/callFlow.html#entity-subscription), the Subscription Manager component is responsible for publishing NGSI-LD subscription requests under the "SUBSCRIPTIONS" topic in Kafka. However, if I subscribe to this topic and then send an NGSI-LD create subscription request to the broker, no messages are received from the topic even though the operation is successful (201 code). In addition, at the time of sending the NGSI-LD request, I do not see any activity in the Kafka logs or Scorpio logs.

I have checked that other Kafka topics for internal messaging such as "ENTITY_CREATE" work. It would be great to be able to subscribe to this topic so new components can seamlessly integrate with Scorpio Broker.

**Environment**
- scorpiobroker/scorpio:scorpio-aaio_1.0.2

**Steps to reproduce**
1. (From kafka container) Subscribe to the "SUBSCRIPTIONS" topic
```bash
./opt/kafka/bin/kafka-console-consumer.sh --topic SUBSCRIPTIONS --bootstrap-server kafka:9092 --from-beginning
```
2. Create subscription for an NGSI-LD entity.
```bash
curl --location --request POST 'localhost:9090/ngsi-ld/v1/subscriptions/' \
--header 'Content-Type: application/ld+json' \
--header 'Link: <https://pastebin.com/raw/Mgxv2ykn>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw '{
	"type": "Subscription",
	"entities": [{
		"idPattern": ".*",
		"type": "Vehicle"
	}],
	"watchedAttributes": ["speed"],
	"notification": {
		"attributes": ["speed"],
		"format": "keyValues",
		"endpoint": {
			"uri": "http://consumer:8080/notify",
			"accept": "application/json"
		}
	}
}'
```

**Comment by ScorpioBroker** [comment]
Hi,
yes this is correct this is a rather recent change. We decided to store the subscriptions in filedb for persistence. (before we used kafka for that but ttl for messages was way to high like that).
Now that had some unforseen consequences as your issue #156. 
I'll get to that as soon as i can.

**Comment by idomingu** [comment]
Hi @ScorpioBroker ! Any progress on this issue? 

Many thanks in advance,

Cheers,
Nacho.
