### ISSUE TITLE
Stricter format check for DateTime values

### ISSUE THREAD

**Issue by MS-Fiware** [ScorpioBroker/ScorpioBroker#16]
Hi,

while playing around with temporal representations and time queries I noticed that DateTime passed in query parameters are not parsed very strictly. The spec clearly states that DateTime must be expressed in UTC using the `YYYY-MM-DDThh:mm:ssZ` format as defined in ISO 8601. This means all the components, including the trailing time zone character 'Z'.

Chapter 4.6.3 states "All the referred components shall appear in the string; reduced representations are not permitted." 

I haven't tested variations in body contents so far, but when having a request like 

GET `/temporal/entities?type=AirQualityObserved&timerel=after&time=2019-01-01T12:00:00`

it is well accepted and acknowledged with a '200 OK' and some matching entities in the returned payload. Instead it should return a "400 Bad Request" I think, because of the missing 'Z'.

The observed behaviour also applies to the following requests:

GET `/temporal/entities?type=AirQualityObserved&timerel=after&time=2019-01-01T12:00:`
GET `/temporal/entities?type=AirQualityObserved&timerel=after&time=2019-01-01T12:`
GET `/temporal/entities?type=AirQualityObserved&timerel=after&time=2019-01-01`
...

I guess the missing components are automatically assumed to be '0' and without the 'Z' character no time offset is considered. But it seems not to be in compliance with the specification.

Greetings,
Michael

**Comment by ScorpioBroker** [comment]
Hi,

yes you are right the forgiving parser for datetime was still in there from dev. 
I removed it and will push in a few minutes.

Best Regards
Benjamin
