### ISSUE TITLE
Querying array values not working

### ISSUE THREAD

**Issue by tkdwnssla** [ScorpioBroker/ScorpioBroker#162]
Querying for entity data with array values not working when query term value is not the first value in the array.

e.g. if I have an entity data like below:
```
{
  "@id": "urn:ngsi-ld:OffStreetParking:ParkingLot-A",
  "@type": [
    "https://uri.fiware.org/ns/data-models#OffStreetParking"
  ],
  "https://smart-data-models.github.io/data-models/terms.jsonld#/definitions/category": [
    {
      "@type": [
        "https://uri.etsi.org/ngsi-ld/Property"
      ],
      "https://uri.etsi.org/ngsi-ld/hasValue": [
        {
          "@value": "underground"
        },
        {
          "@value": "public"
        },
        {
          "@value": "feeCharged"
        },
        {
          "@value": "mediumTerm"
        },
        {
          "@value": "barrierAccess"
        }
      ]
    }
  ]
}
```

When querying the "category" attribute, the data is only retrieved when the query is as follows:
`/ngsi-ld/v1/entities?type=https://uri.fiware.org/ns/data-models%23OffStreetParking&q=category=="underground"`

Other queries that does not include the first value in the "category" array, which is "underground", are not able to retrieve the data. The following queries fail to retrieve the data:
`/ngsi-ld/v1/entities?type=https://uri.fiware.org/ns/data-models%23OffStreetParking&q=category=="public"`
`/ngsi-ld/v1/entities?type=https://uri.fiware.org/ns/data-models%23OffStreetParking&q=category=="freeCharged","mediumTerm"`

**Comment by ScorpioBroker** [comment]
Hi this is fixed now and in the release
