### ISSUE TITLE
Simplified representation of temporal query not working

### ISSUE THREAD

**Issue by michaeI-s** [ScorpioBroker/ScorpioBroker#17]
Hi,

adding the request parameter `options=temporalValues` does not generate the expected simplified output, but instead returns a "400 Bad Request Data".

e.g.
GET `/temporal/entities?type=AirQualityObserved&timerel=after&time=2019-01-01T12:00:00Z&options=temporalValues`

gives the following response:

``` json
{
    "type": 400,
    "title": "Bad Request Data.",
    "detail": [
        "Bad Request Data."
    ]
}
```

When stripping the `options` parameter I got a 200 OK.
Please refer to chapters 6.3.12 and C.5.6.2 of the specification.

Greetings,
Michael

**Comment by ScorpioBroker** [comment]
Hi the support for the temporalValues option is now in.
