### ISSUE TITLE
Docker Swarm Issues

### ISSUE THREAD

**Issue by Glagnar** [ScorpioBroker/ScorpioBroker#177]
I am having problems running the services in a Docker Swarm configuration. I am getting a lot of errors about the Eureka service, but is that even needed ?

You can test this, but just running your compose file as a stack on a single node swarm. Is it related to this error:
https://github.com/spring-cloud/spring-cloud-netflix/issues/1820

**Comment by Glagnar** [comment]
I am still having issues, it is quite easy to replicate.
First build the containers
```
mvn clean package -DskipTests -Pdocker
```

Then you need to edit the compose file, as the version of the images generated has been updated in the pom file, without updating the compose file. E.g.
```
    image: scorpiobroker/scorpio:config-server_0.9.2-SNAPSHOT
```
to
```
    image: scorpiobroker/scorpio:config-server_1.0.0-SNAPSHOT
```

Then deploy the stack:
```
docker stack deploy -c docker-compose-dist-dev.yml  scorpio-platform
```

I get the following error when querying:
```json
{
  "timestamp": "2021-01-04T18:03:04.058+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Connect to 10.0.7.51:1026 [/10.0.7.51] failed: Connection timed out (Connection timed out)"
}
```

via. the following
```bash
curl "http://localhost:9090/ngsi-ld/v1/entities?type=AirQualityObserved" \
     -H 'Accept: application/ld+json' \
     -H 'Content-Type: application/ld+json'
```

Maybe there is a problem in the way that the client seems to be asking for the specifik IP of the service, instead of using the hostname? In docker swarm there is an ingress network and an overlay network, so each service has at least two IP's. Instead shouldn't the service be asking for query-manager:1026 ?

Checking the query manager service via. docker inspect, I see that it has indeed two IP's. From the container running gatweay, one IP actually responds as I would expect, and the other times out:

```
root@958e6e74cc9a:/usr/src/scorpio# curl "10.0.1.25:1026/"
{"timestamp":"2021-01-04T18:18:12.869+0000","status":404,"error":"Not Found","message":"No message available","path":"/"}root@958e6e74cc9a:/usr/src/scorpio#
root@958e6e74cc9a:/usr/src/scorpio# curl "10.0.7.51:1026/"
curl: (7) Failed to connect to 10.0.7.51 port 1026: Connection timed out
root@958e6e74cc9a:/usr/src/scorpio#
```

Looking at eureka, it seems it has the wrong IP for the service registered:
<img width="1249" alt="Screenshot 2021-01-04 at 19 15 40" src="https://user-images.githubusercontent.com/5913559/103566346-27020d80-4ec2-11eb-9a22-785a27e45a62.png">

I hope all this helps, I myself don't know what more you need to start looking at it - and I don't know enough about the eureka spring registry or the other things that you use, to be of much use.

I hope you can prioritise this task, as it is really holding us back - we cannot deploy the Scorpio Broker without this being fixed.

**Comment by Glagnar** [comment]
Please note, that the IP's you will be getting, are different than the ones in my examples above.

**Comment by ajayyadavnec** [comment]
Hi @Glagnar, 
Implementation of K8s is in-progress. We will update the manual by 11 Jan and it would be available to the community.  
K8s implementation would be further strengthen in this quarter.
Other community member would look your issue.

**Comment by Glagnar** [comment]
> Hi @Glagnar,
> Implementation of K8s is in-progress. We will update the manual by 11 Jan and it would be available to the community.
> K8s implementation would be further strengthen in this quarter. I hope you would not encounter this issue with K8s implementation.
> 
> Other community member would look your issue.

Thank you - we will be using k8s anyway for production. I just wanted to give you feedback on Docker Swarm as well, since some may choose to go that way.

**Comment by Glagnar** [comment]
@ajayyadavnec I cannot find the k8s deployment details. Can you send me a link ?
Are you working on an 'operator' component, or will it be a more manual process ?

**Comment by ajayyadavnec** [comment]
@Glagnar , Pull request is raised https://github.com/ScorpioBroker/ScorpioBroker/pull/180 but it is not merged to the development branch yet.

**Comment by arpitNEC** [comment]
@Glagnar , pull request is now merged to the development and now development also contains the k8s files but there are some architectural related decisions which is needed to be finalized for the distributed deployment of the Scorpio broker that's why distributed deployment may not work properly, but you can use the aaio deployment of the Scorpio, it's working fine.
