### ISSUE TITLE
"Invalid request" on temporal entity representation creation (POST /temporal/entities)

### ISSUE THREAD

**Issue by michaeI-s** [ScorpioBroker/ScorpioBroker#18]
Hi,

when trying to create a temporal entity representation with POST /temporal/entities I get a "400 Invalid Request" in the HTTP response.

My request:

```bash
curl -X POST \
  http://192.168.57.101:9090/ngsi-ld/v1/temporal/entities \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:testunit:123",
    "type": "AirQualityObserved",
    "airQualityLevel": [
        {
            "type": "Property",
            "value": "good",
            "observedAt": "2018-08-07T12:00:00Z"
        },
        {
            "type": "Property",
            "value": "moderate",
            "observedAt": "2018-08-14T12:00:00Z"
        },
        {
            "type": "Property",
            "value": "unhealthy",
            "observedAt": "2018-09-14T12:00:00Z"
        }
    ],
    "@context": [
        "https://schema.lab.fiware.org/ld/context",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}'
```

The response body:

```bash
{
    "type": 400,
    "title": "Invalid request.",
    "detail": [
        "id, type, createdAt and modifiedAt are required fields"
    ]
}
```

The detail message claims 'createdAt' and 'modifiedAt' to be required fields. When including these fields the request succeeds. But in fact this is a wrong behavior as both fields are system generated and should be ignored by the NGSI-LD implementation, in case a context producer tries to define them in the request body. See chapter 5.2.2 for more information on that topic.

I tested with commit https://github.com/ScorpioBroker/ScorpioBroker/commit/d1f7c9a8349bcd491cda8e9f2a226fc3decdbd99.

Greetings,
Michael

**Comment by jmcanterafonseca** [comment]
`detail` as per https://tools.ietf.org/html/rfc7807 is a string not an array ... please check compliance

**Comment by tanktoo** [comment]
Same problem here.

**Comment by ScorpioBroker** [comment]
Hi this is fixed now.
@jmcanterafonseca also the details is fixed for some time. Please make individual issue reports for each issue.
