### ISSUE TITLE
Entity id that is an URL

### ISSUE THREAD

**Issue by brechtvdv** [ScorpioBroker/ScorpioBroker#187]
I want to create an entity with an URI that is dereferenceable (URL), however, I'm unable to retrieve such entity with the GET /entities/{entityId} endpoint.

For example, an entity with id `http://example.org/test`:
```
curl --location --request POST 'localhost:9090/ngsi-ld/v1/entities' \
--header 'Content-Type: application/ld+json' \
--data-raw '{
    "id": "http://example.org/test",
    "type": "AirQualityObserved",
    "@context": [
        "https://schema.lab.fiware.org/ld/context",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}'
```

Fetching this entity returns a 400 Bad Request:
```
curl --location --request GET 'localhost:9090/ngsi-ld/v1/entities/http%3A%2F%2Fexample.org%2Ftest' \
--header 'Accept: application/ld+json'
```

**Comment by amitrnec** [comment]
Already resolved in Bugfix-179 #184

**Comment by brechtvdv** [comment]
Indeed, probably fixed. Can you update the docker image so I can test this? https://hub.docker.com/r/scorpiobroker/scorpio-aaio_dev/tags?page=1&ordering=last_updated

**Comment by amitrnec** [comment]
Merged into development branch. Yes sure we will update that in next docker image release.

**Comment by brechtvdv** [comment]
I confirm this is working now in the latest build

**Comment by amitrnec** [comment]
Yes it is working now.
