### ISSUE TITLE
Temporal query responses should not expose system-generated attributes by default

### ISSUE THREAD

**Issue by michaeI-s** [ScorpioBroker/ScorpioBroker#19]
Hi,

when doing a temporal query like 

GET `/temporal/entities?type=AirQualityObserved&timerel=after&time=2018-01-01T12:00:00Z`

I get a response like 

``` js
{
  "id": "urn:ngsi-ld:testunit:123",
  "type": "AirQualityObserved",
  "createdAt": "2018-08-07 12:00:00",
  "NO2": {
    "type": "Property",
    "createdAt": "2019-10-04T15:17:10Z",
    "accuracy": {
      "type": "Property",
      "createdAt": "2019-10-04T15:17:10Z",
      "value": 0.95,
      "modifiedAt": "2019-10-04T15:17:10Z"
    },
    "value": 22,
    "modifiedAt": "2019-10-04T15:17:10Z",
    "unitCode": "GP"
  },
  "modifiedAt": "2019-10-08 12:00:00",
  "airQualityLevel": [
    {
      "type": "Property",
      "createdAt": "2019-10-08T22:38:38Z",
      "value": "unhealthy",
      "modifiedAt": "2019-10-08T22:38:38Z",
      "observedAt": "2018-09-14T12:00:00Z"
    },
    {
      "type": "Property",
      "createdAt": "2019-10-08T22:38:38Z",
      "value": "moderate",
      "modifiedAt": "2019-10-08T22:38:38Z",
      "observedAt": "2018-08-14T12:00:00Z"
    },
    {
      "type": "Property",
      "createdAt": "2019-10-08T22:38:38Z",
      "value": "good",
      "modifiedAt": "2019-10-08T22:38:38Z",
      "observedAt": "2018-08-07T12:00:00Z"
    }/*,
    {
       //...
    }*/
  ],
  "https://uri.fiware.org/ns/data-models#dateObserved": {
    "type": "Property",
    "createdAt": "2019-10-04T15:17:10Z",
    "value": {
      "type": "DateTime",
      "@value": "2018-08-07T12:00:00Z"
    },
    "modifiedAt": "2019-10-04T15:17:10Z"
  },
  "refPointOfInterest": {
    "type": "Relationship",
    "createdAt": "2019-10-04T15:17:10Z",
    "object": "urn:ngsi-ld:PointOfInterest:RZ:MainSquare",
    "modifiedAt": "2019-10-04T15:17:10Z"
  },
  "@context": [
    /*...*/
  ]
}
```

As you can see the response object is cluttered with all those 'createdAt' and 'modifiedAt' attributes. I do not expect them here, since I did not explicitly requested them. Look in chapter 5.2.2 for the following paragraph:

> In query or retrieve operations implementations shall only generate common members (table 5.2.2-1) when the Context Consumer explicitly asks for their inclusion. Clause 6.3.11 defines the mechanism offered by the HTTP binding for such purpose.

Clause 6.3.11 again introduces the 'sysAttrs' keyword for the 'options' request parameter:

> When its value includes the keyword "sysAttrs", a representation of NGSI-LD Elements shall be provided so that the system-generated attributes createdAt, modifiedAt are included in the response payloads

Mabye I miss something here, but from my point of view the response body should not be enriched with these fields if not wanted. 

Best regards,
Michael

**Comment by jmcanterafonseca** [comment]
createdAt and modifiedAt do not have the trailing `Z` ... in some cases

also, in temporal queries all Attributes should be represented by an array ...

**Comment by ScorpioBroker** [comment]
Hi this is fixed now the sysAttrs option is now properly respected on temporal queries. The wrong format of the toplevel datetimes is also resolved. 
@jmcanterafonseca I will reopen another issue for the array part as this is not related to this issue
