### ISSUE TITLE
Sysattrs of sub properties don't get updated properly. This affects subscriptions not be not working for those entities.

### ISSUE THREAD

**Issue by tanktoo** [ScorpioBroker/ScorpioBroker#190]
Hi,
we found another bug. If someone subscribes for an entity of type "A" there will be no notification if "A" contains a "unitCode":
```
{
  "id" : "urn:ngsi-ld:test_temperature",
  "type" : "https://w3id.org/test#A",
  "https://w3id.org/test#field" : {
    "type" : "Property",
    "value" : "NA",
    "https://w3id.org/test#hasExampleValue" : {
      "type" : "Property",
      "value" : 123.372939,
      "unitCode" : "SEC"
    }
  },
  "@context" : [ "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld" ]
}
```
As soon as "unitCode" is deleted from the entity and the value is updated again notifications are sent.

**Comment by tanktoo** [comment]
After further investigation we think that the problem is not with the "unitCode" but with the nested subproperty, here "https://w3id.org/test#hasExampleValue". 
If we create an entity with a subproperty the first time, a notification is sent and received. If we update an already existing entity that has a subproperty (as shown above) there is no notification sent but it is updated inside the broker (You get the updated value if you do a manual query for the entity).

**Comment by ScorpioBroker** [comment]
Hi,

yes that also matches the errors i'm seeing here, that it's the subpoperty not getting a proper modifiedat attached to it. It should be the same problem as #150. I'll look into it next. I'll close #150 now as this is the more active thread.

**Comment by tanktoo** [comment]
Related to this bug report https://github.com/ScorpioBroker/ScorpioBroker/issues/150?

**Comment by ScorpioBroker** [comment]
New release 1.0.5 is out has the fix for this
