### ISSUE TITLE
Subscriptions to entities with one-to-many relationships don't trigger notifications

### ISSUE THREAD

**Issue by daniel-gonzalez-sanchez** [ScorpioBroker/ScorpioBroker#193]
Hi everyone,

I was playing with NGSI-LD subscriptions when I discovered a possible problem. Following the ETSI CIM standard, entity definition with one-to-many relationships are fully supported by NGSI-LD. But I've checked that issuing a Creation or Update operation of a subscribed entity (with one-to-many relationships) is not triggering notifications.

Let me show an example:

**Environment**

- scorpiobroker/scorpio:scorpio-aaio_1.0.4

**Steps to reproduce**

1. Create subscription to an entity:

```
curl --location --request POST 'localhost:9090/ngsi-ld/v1/subscriptions/' \
--header 'Content-Type: application/ld+json' \
--header 'Link: <https://fiware.github.io/data-models/full-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw '{
	"type": "Subscription",
	"entities": [{
		"type": "House"
	}],
	"notification": {
		"endpoint": {
			"uri": "http://consumer:8080/notify",
			"accept": "application/json"
		}
	}
}'
```

2. Create entity -> Creation has no problems, but no notification is sent to the subscriber endpoint (the Context Consumer doesn't receive notifications)

```
curl --location --request POST 'http://localhost:9090/ngsi-ld/v1/entities/' \
--header 'Content-Type: application/json' \
--header 'Link: <https://fiware.github.io/data-models/full-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw '{
        "id": "smartcity:houses:house1",
        "type": "House",
        "hasRoom": [{
                "type": "Relationship",
                "object": "house1:smartrooms:room1",
                "datasetId": "urn:ngsi-ld:Relationship:1"
        },
        {
                "type": "Relationship",
                "object": "house1:smartrooms:room2",
                "datasetId": "urn:ngsi-ld:Relationship:2"
        }]
}'
```
The ETSI CIM specification 1.3.1 supports arrays of relationships as shown in the example above. I've tried this type of entities subscription with and without datasetId data type in each relationship entry (according to ETSI CIM 009 v1.3.1 - section 5.2.6, "datasetId" is a Data Type in NGSI-LD Relationships that allows identifying a set or group of target relationship object). 

Also, I tried to define this relationship with a simplified syntax like this:

```
curl --location --request POST 'http://localhost:9090/ngsi-ld/v1/entities/' \
--header 'Content-Type: application/json' \
--header 'Link: <https://fiware.github.io/data-models/full-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw '{
        "id": "smartcity:houses:house1",
        "type": "House",
        "hasRoom": {
                "type": "Relationship",
                "object": ["house1:smartrooms:room1", "house1:smartrooms:room2"]
        }
}'
```
Obviously, before creating this House entity, I've created the Room entities that the "hasRoom" relationship refers to. But in either case, notifications are not triggered. However, If I try the same example for entity creation with one-to-one relationship (e.g., one House entity with a "hasRoom" relationship with only one Room entity), the notifications are triggered correctly.

Many thanks in advance!

Daniel

**Comment by martin-p-bauer** [comment]
The first part seems to be a bug, i.e. 2 should trigger a notification. The syntax you provide below is not supported in NGSI-LD as it is not equivalent to the above (no way to put a datasetId or other meta data). Orion-LD may still support it for some backward compatibility reasons, but it is not valid NGSI-LD according to the specification. 

We are currently discussing in ETSI ISG CIM to also support the simplified representation currently available only for retrieve operations also for create and update operations, but it also requires a change in the way multi-attributes are represented.

**Comment by daniel-gonzalez-sanchez** [comment]
Thank you so much for answering so fast and for the clarification about the correct syntax for one-to-many relationships in entity definitions follow by NGSI-LD data-model and Scorpio Broker. I had already read about this, but I assumed that this unofficial simplified syntax supported by ORION-LD Broker could be adopted by Scorpio. And it's true, this representation is more limited and doesn't allow meta-data in each relationship entry as datasetId. Thank you for the correction and the updated and detailed information about that.

Regarding notifications that are not triggered after subscriptions to entities with one-to-many relationships, I think it may indeed be a bug. I've reproduced again the same use case that I proposed above and actually the Context Consumer (a simple HTTP Consumer in my specific implementation case) doesn't receive notification logs about Entity Creation and Update operations.

Thanks again.

**Comment by ScorpioBroker** [comment]
Hi,
Yes this is a bug. I think i got the problem pined down. PR should be incoming soon.

**Comment by ScorpioBroker** [comment]
for tracking this is related to #190 as well and will come in the #191 PR

**Comment by ScorpioBroker** [comment]
PR is in new release is out as 1.0.5
