### ISSUE TITLE
Bug retrieving entity with context in Link header

### ISSUE THREAD

**Issue by brechtvdv** [ScorpioBroker/ScorpioBroker#199]
My JSON-LD context uses dots ('.') in prefixes, e.g. inside http://data.vlaanderen.be/context/gebouwenregister.jsonld there is a prefix `Gebouw.geometrie`:
```
{ "Gebouw.geometrie": {
    "@id": "https://data.vlaanderen.be/ns/gebouw#Gebouw.geometrie",
    "@type": "https://data.vlaanderen.be/ns/gebouw#2DGebouwgeometrie"
}
```

There is a bug when I want to retrieve an entity through this context file.
For example:
I create following entity:
```
curl --location --request POST 'localhost:9090/ngsi-ld/v1/entities' \
--header 'Content-Type: application/ld+json' \
--data-raw '{
  "@context": ["http://data.vlaanderen.be/context/gebouwenregister.jsonld", 
    "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"],
  "@id": "http://www.wikidata.org/entity/Q28962266",
  "@type": "Gebouw",
  "Gebouw.geometrie": {
    "@type": "Relationship",
    "object": "http://example.org/something"
  }
}'
```

And then retrieve it with the context file in a Link header:
```
curl --location --request GET 'localhost:9090/ngsi-ld/v1/entities/http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ28962266' \
--header 'Accept: application/ld+json' \
--header 'Link: <http://data.vlaanderen.be/context/gebouwenregister.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"'
```

This returns following JSON-LD:
```
{
    "id": "http://www.wikidata.org/entity/Q28962266",
    "type": "Gebouw",
    "Gebouw:.geometrie": {
        "type": "Relationship",
        "object": "http://example.org/something"
    },
    "@context": [
        "http://data.vlaanderen.be/context/gebouwenregister.jsonld",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}
```

Instead of `Gebouw:geometrie`, I receive `Gebouw:.geometrie` -> this does not match with the prefix inside the context file

**Comment by ScorpioBroker** [comment]
Hi,

it looks like our json-ld library is acting a bit weird there compared to the reference implementation. However i tried your content at the json-ld playground and it doesn't compact your entry at all. https://tinyurl.com/y4sleszj  
I played a bit around on the playground with your context and it seems to me that the @type definition is messing the compaction up. removing it gives the expected result.
https://tinyurl.com/y3qrnrh9
What happens in scorpio is basically that your definition of Gebouw.geometrie is not found in the document. The ref implementation just stops here and doesn't compact the term. However our lib still finds a match for https://data.vlaanderen.be/ns/gebouw#Gebouw and is treating it as a prefix hence you get the colon in the result.

**Comment by brechtvdv** [comment]
Thanks for finding the cause of this behavior. I'll look into changing the JSON-LD context
