### ISSUE TITLE
Prohibit addition of attribute instances to a non-existing temporal entity representation

### ISSUE THREAD

**Issue by michaeI-s** [ScorpioBroker/ScorpioBroker#20]
Hi,

when trying to add attribute instances to a temporal representation of an entity which does not exist, the NGSI-LD endpoint should reply with a `ResourceNotFound` error. Instead it returns a `204 No Content` which implies a successful addition of the attributes.

Chapter 5.6.12.4 of the spec describes the intended behavior:

> If the NGSI-LD endpoint does not know about the Temporal Representation of the target Entity, because there is no existing Temporal Representation of an Entity whose id (URI) is equivalent to the one passed as parameter, an error of type ResourceNotFound shall be raised.

My example request:

``` bash
curl -X POST \
  http://192.168.57.101:9090/ngsi-ld/v1/temporal/entities/urn:ngsi-ld:testunit:123/attrs \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "temperature": [
        {
            "type": "Property",
            "value": 27.6,
            "observedAt": "2018-08-07T12:00:00Z"
        },
        {
            "type": "Property",
            "value": 16.2,
            "observedAt": "2018-09-07T12:00:00Z"
        },
        {
            "type": "Property",
            "value": 3.2,
            "observedAt": "2018-12-07T12:00:00Z"
        }
    ],
    "@context": [
        "https://schema.lab.fiware.org/ld/context",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}'
```

As you can see I tried to add some `temperature` attribute instances to a non-existing temporal entity representation with id `urn:ngsi-ld:testunit:123`.

Greetings,
Michael

**Comment by ScorpioBroker** [comment]
This was patched and only forgotten to be closed.
