### ISSUE TITLE
No notifications after attribute deletion.

### ISSUE THREAD

**Issue by mainakae** [ScorpioBroker/ScorpioBroker#200]
Hello everyone,

In the course of the IoTCrawler project, we have noticed another issue related with notifications: after deleting an attribute on an entity, the broker will not send out notifications if that entity is updated.

Best regards,
Pedro.

**Comment by ScorpioBroker** [comment]
Hi,

can you elaborate a bit. Do you mean you are not get the notification for the delete (that's normal according to spec) or that once you delete an attrib of an entity you never get a notification for this entity again? 
BR
Benni

**Comment by mainakae** [comment]
Yes, sorry Benni, the issue is that after deleting the attribute, no further notifications are received (not the one regarding the deletion, but any other change).

BR!
