### ISSUE TITLE
PATCHing an attribute instance from a temporal entity representation results in "Resource not found" error

### ISSUE THREAD

**Issue by michaeI-s** [ScorpioBroker/ScorpioBroker#21]
Hi,

when trying to modify an attribute instance from a temporal entity representation with PATCH /temporal/entities/{entityId}/attrs/{attrId}/{instanceId} I get a "404 Resource not found" in the HTTP response.

My request:

```bash
curl -X PATCH \
  http://192.168.57.101:9090/ngsi-ld/v1/temporal/entities/urn:ngsi-ld:testunit:123/attrs/temperature/urn:ngsi-ld:testunit:123:temperature:1 \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "temperature": [
        {
            "type": "Property",
            "value": 28.6
        }
    ],
    "@context": [
        "https://schema.lab.fiware.org/ld/context",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}'
```

The response body:

```bash
{
    "type": 404,
    "title": "Resource not found.",
    "detail": [
        "Resource not found."
    ]
}
```

According to spec this error occurs, if neither the target entity, the target attribute nor the targeted attribute instance is known to the NGSI-LD system. See chapter 5.6.14.4 for details.
But in my case all of them exist.

I tested with commit https://github.com/ScorpioBroker/ScorpioBroker/commit/d1f7c9a8349bcd491cda8e9f2a226fc3decdbd99.

Greetings,
Michael

**Comment by naveennec** [comment]
Fix of issue 22 also fixed the issue no 21,  code fix is committed in development branch, which is reviewed and tested.
