### ISSUE TITLE
Temporal query fails with Bad Request Data.

### ISSUE THREAD

**Issue by KazuhitoSuda-NEC** [ScorpioBroker/ScorpioBroker#213]
NGSI-LD spec defines `timeAt` and `endTimeAt` as prameters for temporal query, but the following query fails with `Bad Request Data.`.

```
curl -sS 'http://localhost:9090/ngsi-ld/v1/temporal/entities/urn:ngsi-ld:sensor100' \
-G --data-urlencode 'timerel=between' --data-urlencode 'timeAt=2017-02-01T00:00:00Z' --data-urlencode 'endTimeAt=2017-04-01T00:00:00Z'

{
        "type":"http://uri.etsi.org/ngsi-ld/errors/BadRequestData",
        "title":"Bad Request Data.",
        "details":"Bad Request Data."
}
```

A query is successful when replacing `timeAt` with `time` and `endTimeAt` with `endTime`. This is not compliant with the NGSI-LD spec.

```
curl -sS 'http://localhost:9090/ngsi-ld/v1/temporal/entities/urn:ngsi-ld:sensor100' \
-G --data-urlencode 'timerel=between' --data-urlencode 'time=2017-02-01T00:00:00Z' --data-urlencode 'endTime=2017-04-01T00:00:00Z'

{
  "id" : "urn:ngsi-ld:sensor100",
  "type" : "Sensor",
  "temperature" : [ {
    "type" : "Property",
    "value" : 25,
    "instanceId" : "urn:ngsi-ld:23819067-1e53-4f43-9c4f-9a64ae3c8b3e",
    "observedAt" : "2017-03-01T00:00:01Z"
  }, {
    "type" : "Property",
    "value" : 21,
    "instanceId" : "urn:ngsi-ld:bda49102-4af4-44f5-9fbb-dafea373481b",
    "observedAt" : "2017-02-01T00:00:01Z"
  } ],
  "@context" : [ "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld" ]
}
```

```
$ docker images | grep scorpio
scorpiobroker/scorpio                         scorpio-aaio_latest            26a023b8d28a   4 weeks ago     586MB
```

**Comment by amitrnec** [comment]
Hi @KazuhitoSuda-NEC 
timeAt and endTimeAt are part of release "gs_cim009v010301p" or "ngsi-ld-core-context-v1.3"
" and we are currently working on it and its in the finishing stage and likely to be merge in the development in the upcoming release  but if you still wants to use it you can pull from the branch "feature-137_new" but this is not backward compatible so all the data might not work properly.

Thanks,
Amit

**Comment by KazuhitoSuda-NEC** [comment]
Thank you for your quick response! I understand.

**Comment by ScorpioBroker** [comment]
Hi @KazuhitoSuda-NEC 
just as an addon to Amits answer. While the code changes are almost done for 1.3.1, we are still investigating on how to migrate old databases to the new format when the changes are in. So it might not be all ready for the next intermediate FIWARE release (14th of march afaik) but maybe come some time after this one. 
Until we have this figured out properly we would still keep the main scorpio images on 1.2.1, to not break anyones data, and release a seperate docker release for 1.3.1 till we got the migration figured out.

Best Regards
Benjamin

**Comment by KazuhitoSuda-NEC** [comment]
After a new version for 1.3.1. is released, I will try it. 
Thank you.
