### ISSUE TITLE
RegistryManager doesn’t bootstrap from spring_args

### ISSUE THREAD

**Issue by jlanzarotti** [ScorpioBroker/ScorpioBroker#231]
I'm trying to run on a custom database with the helm dist-deployiment-files version. The only component that doesn’t start even passing all the spring_args options is the RegistryManager.

A did a simple test by building and pulling the latest image:

`docker run -it  scorpiobroker/scorpio:RegistryManager_latest bash`

Then even if passing a custom `spring.datasource.url` it keeps trying to connect to `localhost:5432`

```
root@3ce6084723aa:/usr/src/scorpio# java -jar $JAR_FILE_RUN --spring.datasource.url=jdbc:postgresql://MY_DB_ENDPOINT:5432/ngb?ApplicationName=ngb_registrymanager

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.9.RELEASE)

2021-07-19T09:34:57,631 INFO  [main] o.s.b.SpringApplication: No active profile set, falling back to default profiles: default
2021-07-19T09:35:07,624 ERROR [main] c.z.h.p.HikariPool: SpringBootHikariCP_Reader - Exception during pool initialization.
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```

Also editing the `config/application.yml` in the container doesn’t do anything.

Thanks!

**Comment by arpitNEC** [comment]
hello @jlanzarotti,

Please add the below configuration into the docker config/application.yml file (if not present)with the updated values:

reader:
  enabled: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/ngb?ApplicationName=ngb_storagemanager_reader"
    username: ngb
    password: ngb
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootHikariCP_Reader
      maxLifetime: 2000000
      connectionTimeout: 30000

writer:
  enabled: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/ngb?ApplicationName=ngb_storagemanager_writer"
    username: ngb
    password: ngb
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootHikariCP_Writer
      maxLifetime: 2000000
      connectionTimeout: 30000
And please do let me know this thing works or not, if yes then we will push these changes in the upcoming release.

**Comment by jlanzarotti** [comment]
Hi @arpitNEC thanks for your help!

I can confirm that adding that config into the config/application.yml is changing the db endpoint... however, that doesn’t allow me to configure the app with env variables. Trying to run as the docker entry does 
` CMD ["/bin/sh" "-c" "java -jar $JAR_FILE_RUN ${spring_args}"]`
and overriding the same variables as you provided, does not change the runtime and runs with the configs from application.yml.

Ideally this should work from the env vars right?
