### ISSUE TITLE
Pagination in temporal queries

### ISSUE THREAD

**Issue by hdelva** [ScorpioBroker/ScorpioBroker#234]
With the regular `/entities` endpoints, it's possible to use the `limit` query parameter to request only a fixed amount of data, but is there something similar for the `/temporal/entities` endpoint? I can find nothing useful in the NGSI-LD specification document (v1.4.2), as this query parameter is mandatory on all endpoints _except_ the temporal one. This seems a bit strange, as the temporal API returns more data than the other APIs - so surely pagination is even more important here? There is a [Swagger document](https://forge.etsi.org/swagger/ui/?url=https://forge.etsi.org/rep/NGSI-LD/NGSI-LD/raw/master/spec/updated/generated/full_api.json) out there that does seem to say it should be supported, but when I try it I simply get a `"Bad request data"` response.

Is there a chance the NGSI-LD spec will ever adopt some sort of pagination here? And if not, would this be something implementations such as Scorpio could add themselves?

**Comment by amitrnec** [comment]
Hi,
Currently it is not implemented in temporal queries but we can plan to implement it later.

BR,
Amit Raghav.

**Comment by amitrnec** [comment]
Hi,
Pagination/limit implemented in temporal queries and code merged in dev branch.

BR,
Amit Raghav.

**Comment by brechtvdv** [comment]
Can you update the Docker image: scorpiobroker/scorpio:scorpio-aaio_latest ?

**Comment by ScorpioBroker** [comment]
Hi @brechtvdv ,
i've made a new release 1.1.0 and updated latest.
It's up on dockerhub now.

**Comment by brechtvdv** [comment]
Now I don't get a 400 error when adding &count=true, but the count is still not added in the headers. Can you check?

**Comment by amitrnec** [comment]
Hi,
We have only implemented pagination/limit in temporal query but still need to work on count functionality. we will implement it asap.

Thanks,
Amit.

**Comment by brechtvdv** [comment]
Thanks

**Comment by amitrnec** [comment]
Hi,

Now count functionality have implemented and raise PR #256  

Thanks,
Amit
