### ISSUE TITLE
[question] Auth - Integration with Keyrock

### ISSUE THREAD

**Issue by dalxds** [ScorpioBroker/ScorpioBroker#239]
Whereas I've read the docs on the security part, I can't seem to understand the component that Scorpio uses to handle Authentication/Authorization.
Is there a current integration with an IDM such as Keyrock? What is the proposed implementation for security?
Thanks!

**Comment by ScorpioBroker** [comment]
Hi,

scorpio basically uses spring clouds support for oauth. This can be either configured in the application.yml or via command line/in a docker-compose file via spring_args env var.

the configuration in the yml file would look like this.
security:
  active: true
  oauth2:
    client:
    # for keycloak configure
      #accessTokenUri: http://10.0.4.33:8080/auth/realms/mykeycloak/protocol/openid-connect/token
      #userAuthorizationUri: http://10.0.4.33:8080/auth/realms/mykeycloak/protocol/openid-connect/auth
      #clientId: authserver
      #clientSecret: ae8c99a9-f98d-41e9-8fb2-d348acb987e0
    # for ketrock configure  
      accessTokenUri: http://172.30.64.120:3000/oauth2/token
      userAuthorizationUri: http://172.30.64.120:3000/oauth2/authorize
      clientId: a2034c11-d2a9-4cab-9fac-ff65425bd53f
      clientSecret: 7364baec-6d6f-4307-8c71-d66e1e6c3afc
    resource:
    # for keycloak configure
      #userInfoUri: http://10.0.4.33:8080/auth/realms/mykeycloak/protocol/openid-connect/userinfo
    # for keycloak configure
      userInfoUri: http://172.30.64.120:3000/user

We have tested it with keyrock and keycloak but it should work with anything oauth2 compatible. You would still need to setup the oauth server to actually control the access to the respective interfaces.

For the command line / docker-compose you would be add --<configparam>=<value> where indent are seperated by dot. so e.g. "--security.active=true --security.oauth2.client.clientid=something ..."

**Comment by ScorpioBroker** [comment]
sorry github swallows the indents in the post please check the application.yml example here at the bottom 
https://github.com/ScorpioBroker/ScorpioBroker/blob/development/AllInOneRunner/src/main/resources/application-dev.yml

**Comment by dalxds** [comment]
thank you!
