### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by hlange** [ScorpioBroker/ScorpioBroker#252]
Hello, 

I am currently experimenting with the examples in the API-Walkthrough (https://github.com/ScorpioBroker/ScorpioBroker/blob/development/docs/en/source/API_walkthrough.rst).

I can create new entries, but when I try to edit a value I get the following error:
`{"timestamp":"2021-11-02T12:26:21.131+0000","status":405,"error":"Method Not Allowed","message":"Request method 'POST' not supported","path":"/ngsi-ld/v1/entities/house2:smartrooms:room1"}`

The cURL command was:
```
curl localhost:9090/ngsi-ld/v1/entities/house2%3Asmartrooms%3Aroom1 -s -S -H 'Content-Type: application/json' -H 'Link: https://pastebin.com/raw/Mgxv2ykn' -d @- <<EOF
{
        "temperature": {
        "value": 25,
        "unitCode": "CEL",
        "type": "Property",
        "providedBy": {
                "type": "Relationship",
                "object": "smartbuilding:house2:sensor0815"
        }
  },
  "isPartOf": {
        "type": "Relationship",
        "object": "smartcity:houses:house2"
  }
}
EOF
```
I am using docker to run the broker

`sudo docker-compose -f docker-compose-aaio.yml up`

How can I fix that?

Also, the example to fetch a specific attribute is also not working.

Mentioned in the walkthrough:
`curl localhost:9090/ngsi-ld/v1/entities/smartcity%3Ahouses%3Ahouse2/?attrs=location -s -S -H 'Accept: application/ld+json' -H 'Link: <https://pastebin.com/raw/Mgxv2ykn>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"'`

Results to: 
```
"type":"http://uri.etsi.org/ngsi-ld/errors/ResourceNotFound",
        "title":"Resource not found.",
        "details":"Resource not found."
```
It looks like that the working command is:
`curl localhost:9090/ngsi-ld/v1/entities/smartcity%3Ahouses%3Ahouse2?attrs=location -s -S -H 'Accept: application/ld+json' -H 'Link: <https://pastebin.com/raw/Mgxv2ykn>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"'`

**Comment by ScorpioBroker** [comment]
Hi,
thanks for the report. yes that's a bug in the walkthrough when updating/appending an entity it has to have /attrs at the end. So post on localhost:9090/ngsi-ld/v1/entities/house2%3Asmartrooms%3Aroom1/attrs is correct. PR #216 addresses this but hasn't been merged in yet. Will do that now and close here once the PR is in

**Comment by hlange** [comment]
Thanks, it works now.

**Comment by hlange** [comment]
It looks like it also exist a problem with updating a specific value:

```
curl localhost:9090/ngsi-ld/v1/entities/house2%3Asmartrooms%3Aroom1/attrs/temperature -s -S -H 'Content-Type: application/json' -H 'Link: https://pastebin.com/raw/Mgxv2ykn' -d @- <<EOF
{
        "value": 26,
        "unitCode": "CEL",
        "type": "Property",
        "providedBy": {
                "type": "Relationship",
                "object": "smartbuilding:house2:sensor0815"
        }
}
EOF
```

Answer:
`{"timestamp":"2021-11-02T13:32:25.615+0000","status":405,"error":"Method Not Allowed","message":"Request method 'POST' not supported","path":"/ngsi-ld/v1/entities/house2:smartrooms:room1/attrs/temperature"}`

**Comment by hlange** [comment]
This command is working:
```
curl -XPATCH -H "Content-type: application/json" -d '{
  "value":9999
}' 'http://localhost:9090/ngsi-ld/v1/entities/house2%3Asmartrooms%3Aroom1/attrs/temperature'
```

**Comment by ScorpioBroker** [comment]
Hi,

yes sorry about that there was twist in mind while writing those tutorials, append is POST and update is PATCH. We will update the tutorials accordingly.

**Comment by hlange** [comment]
No problem, mistakes happens! Thanks for the great work!
