### ISSUE TITLE
issue with GET Query (/ngsi-ld/v1/entityOperations/query)

### ISSUE THREAD

**Issue by Neeraj-Nec** [ScorpioBroker/ScorpioBroker#259]
Hi @ScorpioBroker ,

I am sending the following request to fetch the data of "Vehicle" type by psot Query (/ngsi-ld/v1/entityOperations/query). The following example is the body part of my request 
{
 	"type": "Query",
 	"entities": [
 		{
 			"type" : "Vehicle"
 		}
 	] ,
 	"attrs": ["brandName"]
 }
provided link header (context): https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld 
getting following error 
{"timestamp":"2021-11-15T03:55:44.131+0000","status":500,"error":"Internal Server Error","message":"Type has to be Query for this operation","path":"/ngsi-ld/v1/entityOperations/query"}

**Comment by amitrnec** [comment]
Hi,

It is working fine. you can check again.

Thanks.
