### ISSUE TITLE
Partial update api is not working properly 

### ISSUE THREAD

**Issue by yogeshbirla3986** [ScorpioBroker/ScorpioBroker#279]
I have created a room1 enitty using the below payload 

curl localhost:9090/ngsi-ld/v1/entities -s -S -H 'Content-Type: application/ld+json' -d @- <<EOF
        {
  "id": "house2:smartrooms:room1",
  "type": "Room",
  "temperature": {
        "value": 23,
        "unitCode": "CEL",
        "type": "Property",
        "providedBy": {
                "type": "Relationship",
                "object": "smartbuilding:house2:sensor0815"
         }
   },
  "isPartOf": {
        "type": "Relationship",
        "object": "smartcity:houses:house2"
  },
  "@context": [{"Room": "urn:mytypes:room", "temperature": "myuniqueuri:temperature", "isPartOf": "myuniqueuri:isPartOf"},"https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"]
}
EOF

and then tried to do a partial update on temperature using

curl localhost:9090/ngsi-ld/v1/entities/house2%3Asmartrooms%3Aroom1/attrs/temperature -s -S -H 'Content-Type: application/json' -H 'Link: https://pastebin.com/raw/Mgxv2ykn' -d @- <<EOF
{
        "value": 26,
        "unitCode": "CEL",
        "type": "Property",
        "providedBy": {
                "type": "Relationship",
                "object": "smartbuilding:house2:sensor0815"
        }
}
EOF

but it is not updating temperature , it is creating new attrs value , unitCode , type , providedBy 

i did this using docker-compose-aaio.yml file of ScorpioBroker/ScorpioBroker github development branch

also tried with docker-compose-dist.yml file but facing same issue .

Thank you

**Comment by amitrnec** [comment]
Hi,
We have checked the same process with your data through dev branch , It is working as expected.
In case of partial update, only attribute value get updated and not creating new attribute.
Kindly can you verify again.

Thanks,
Amit.

**Comment by yogesh-nextgen** [comment]
Hi,
when i am making a PATCH request using the above payload it is working now ,
Previously i was making a POST request that's why it was not working as expected .
Thank you very much for you quick response .

**Comment by yogeshbirla3986** [comment]
Hi,
When i was using that curl request it was not working because that curl makes a POST on that port,
but when  i tried with postman and make it as a PATCH request it is working now.

Thank you very much for you quick response .
