### ISSUE TITLE
Problem with temporal query

### ISSUE THREAD

**Issue by pierre-josselin** [ScorpioBroker/ScorpioBroker#284]
I deployed the latest version of Scorpio AAIO with Docker and Docker Compose through [this script](https://github.com/ScorpioBroker/ScorpioBroker/blob/development/docker-compose-aaio.yml), on a Debian 10 virtual machine.

When I send this request (which worked fine on an older version of Scorpio) :

GET /ngsi-ld/v1/temporal/entities/urn:...?attrs=discussion&timerel=between&time=2022-01-03T23:00:00Z&endTime=2022-02-04T22:59:59Z

I get this error :

```json
{
	"type":"https://uri.etsi.org/ngsi-ld/errors/BadRequestData",
	"title":"Bad Request Data.",
	"details":"time is unknown"
}
```

**Comment by ScorpioBroker** [comment]
Hi,
this is one of the updates in the NGSI-LD spec. The new names are timeAt and endTimeAt.

**Comment by pierre-josselin** [comment]
Thanks for the quick response!
