### ISSUE TITLE
Integrating to external authentication provider

### ISSUE THREAD

**Issue by prahvin** [ScorpioBroker/ScorpioBroker#285]
Adding authentication support while invoking REST API endpoints

**Comment by ScorpioBroker** [comment]
Hi, 
could you please elaborate a bit what exactly the issue is? 
With security enabled, Scorpio supports OAuth2. You can have a look at the application.yml
https://github.com/ScorpioBroker/ScorpioBroker/blob/development/AllInOneRunner/src/main/resources/application.yml 
from line 58 you can find the respective settings.

**Comment by prahvin** [comment]
> 

Hi,
After integrating with keycloak instance, setup the keycloak as below.
  security:
    active: true
    oauth2:
     resourceserver:
       jwt:
         issuer-uri: http://localhost:8080/auth/realms/myrealm
     client:
       provider:
         keycloak:
           issuer-uri: http://localhost:8080/auth/realms/myrealm
       registration:
         keycloak-client:
           provider: keycloak
           client-id: myclient
           client-secret: 91699dd5-963c-4f98-b8a9-03790e5426ba
           authorization_grant_type: client_credentials
         keycloak:
           client-id: myclient
           client-secret: 91699dd5-963c-4f98-b8a9-03790e5426ba

However the bearer token sent in the request is rejected with 401 unauthorized error
![keycloak](https://user-images.githubusercontent.com/25497881/155129959-7cbc48f5-c55a-427d-8b58-2e4c1be48fef.jpg)

Need help with configuring scorpio broker further to enable proper authorization of RestAPI requests.

**Comment by prahvin** [comment]
SOLVED: Set profile in application.yml to "docker-rest"
![docker-rest](https://user-images.githubusercontent.com/25497881/155300545-50b939e0-7220-4f40-8bc6-2ab19bfbd65b.jpg)

modify "WebSecurityConfiguration.java"'s configure() method
![configure](https://user-images.githubusercontent.com/25497881/155300908-d3c7e226-7991-4740-ab32-b19cd9e05e05.jpg)

Note: setting the profile to "docker" causes kafka to fail wierd!
