### ISSUE TITLE
Broker consuming big amounts of RAM

### ISSUE THREAD

**Issue by mainakae** [ScorpioBroker/ScorpioBroker#29]
Hello everybody,

In our deployment (docker version with each micro-service running standalone in a container), the whole set of microservices composing the broker is taking as much as 14GB of RAM. This is limiting our capability to test different scenarios (namely distribution and federation), as we need to allocate a relatively high amount of resources to deploy several broker instances.

Thanks for your time and attention.

**Comment by ScorpioBroker** [comment]
Hi, i was working on that today. So i got a solution for the all in one version where i made a special runner to have everything inside of one jvm. I'll commit this by tomorrow i think. Just have to make sure i didn't damage something else.

**Comment by ScorpioBroker** [comment]
i haven't yet changed the docker-aaio profile to take advantage of this... will arrive tomorrow

**Comment by mainakae** [comment]
That's great news, thank you! I'll be testing it as soon as it's ready.

**Comment by mainakae** [comment]
Great! we had the chance to test it, and now it seems a lot better: around 4GB of ram and performing better (queries are answered in less than a second).

Excellent!
