### ISSUE TITLE
Possible bug with registrations

### ISSUE THREAD

**Issue by pierre-josselin** [ScorpioBroker/ScorpioBroker#294]
Hello,

I have a problem with scorpio that may be a bug because I didn't had this problem with an older version.

On an instance of Orion-LD, I created this entity:

`POST http://orion-ld:1026/ngsi-ld/v1/entities`

```json
{
    "id": "urn:ngsi-ld:Test:abcd",
    "type": "Test",
    "name": {
        "type": "Property",
        "value": "Hello world !"
    }
}
```

On an instance of Scorpio latest version, I created this registration:

`POST http://scorpio:9090/ngsi-ld/v1/csourceRegistrations`

```json
{
    "id": "urn:ngsi-ld:ContextSourceRegistration:1646214174",
    "type": "ContextSourceRegistration",
    "information": [
        {
            "entities": [
                {
                    "type": "Test"
                }
            ],
            "properties": [
                "name"
            ]
        }
    ],
    "endpoint": "http://orion-ld:1026"
}
```

But when I try to get my entity back, I get nothing:

`GET http://scorpio:9090/ngsi-ld/v1/entities?id=urn:ngsi-ld:Test:abcd&type=Test`

```json
[]
```

`GET http://scorpio:9090/ngsi-ld/v1/entities/urn:ngsi-ld:Test:abcd`

```json
{
	"type":"https://uri.etsi.org/ngsi-ld/errors/ResourceNotFound",
	"title":"Resource not found.",
	"details":"Resource not found."
}
```

However it seems that the registration is considered by Scorpio because if I create it with an invalid endpoint (non-existent host), when I try to retrieve the entity on Scorpio, the request will load for a long time.

If it's not a bug and I made a mistake I'm sorry, but I feel like I'm following [the documentation](https://github.com/FIWARE/tutorials.LD-Subscriptions-Registrations) correctly, and this same example was working during my tests in September 2021.

**Comment by ScorpioBroker** [comment]
Hi,

GET http://scorpio:9090/ngsi-ld/v1/entities/urn:ngsi-ld:Test:abcd gives you only the local resource. The empty result is correct in this case.

However the query you are doing should be working exactly like you did it. I can't recreate the problem on my side.
Using orion ld latest and scorpio aaio latest on docker-compose i recreated your scenario and it works as it should. My only change was the ip address in the registration.

Do you have any log output? This could be a network problem.

**Comment by pierre-josselin** [comment]
Hi @ScorpioBroker, thank you for your answer. I'm going to deepen my tests to understand where the problem comes from (a bit later because I'm working on another project at the moment).
