### ISSUE TITLE
Scorpio loops on Startup if core context is not found.

### ISSUE THREAD

**Issue by jason-fox** [ScorpioBroker/ScorpioBroker#305]
Not really an "issue" as such - more of a question about what should occur in this circumstance. When testing Scorpio this morning for some reason https://uri.etsi.org was temporarily unavailable. Since it appears that the core context is downloaded as part of startup, and startup won't continue the effect is to cause Scorpio to hang indefinitely.

Given the lack of the core context would be a fatal operational failure, should the broker exit gracefully after a (configurable) number of attempts? It would be easier to diagnose the issue if Scorpio died in this case.

**Comment by ScorpioBroker** [comment]
Hi,

yeah i think you are right. We have kind of assumed that the core context is there on startup and once we have it it's fine. 
We should consider the time outs as you suggested and maybe just pack it in as backup for "offline" mode.

**Comment by jason-fox** [comment]
Completed.
