### ISSUE TITLE
Temporale Entity behavior between FIWARE 8.1.0 and 2.1.14

### ISSUE THREAD

**Issue by mdespland** [ScorpioBroker/ScorpioBroker#306]
I have a test to check the creation of temporal entities with broker and the behavior change, is it a bug or a feature ? :)
My test is simple
1 - Creating an entity
2 - Retrieving the entity
3 - Retrieving the temporal representation of the entity
4 - Adding a temporal representation of the entity
5 - Retrieving the entity
6 - Retrieving the temporal representation of the entity

The code of the test is available in the image : ```registry.eu-west-0.prod-cloud-ocb.orange-business.com/fiware/ngsild-test:temporal01```

```
docker run -it --rm --network test-ngsi-scorpio_default -e ORION_API=http://scorpio:9090 registry.eu-west-0.prod-cloud-ocb.orange-business.com/fiware/ngsild-test:temporal01
```

I have test it against : 
   #image: scorpiobroker/scorpio:scorpio-aaio-no-eureka_2.1.2
    image: scorpiobroker/scorpio:scorpio-aaio_FIWARE_8.1.0
    #image: scorpiobroker/scorpio:scorpio-aaio-no-eureka_2.1.13
    #image: scorpiobroker/scorpio:scorpio-aaio-no-eureka_2.1.1

On FIWARE 8.1.0 test 3 succeed and test 6 retrieve the data from test 1 + test 4
With the other version, test 3 return HTTP 404 and test 6 return only the data from test 4

**Comment by amitrnec** [comment]
Hi,
We will check this functionality.
Can you please share other version that you are using ?.

Thanks.

**Comment by mdespland** [comment]
Hi, 
I just restart testing to decide which version to use for one of our project
With Orion-LD 1.0.1 + Mintaka 0.5.9 test works like Scorpio FIWARE 8.1.0 (except the HTTP status of test 4)

Thanks

**Comment by ScorpioBroker** [comment]
Hi,
i'll check the functionality this week.

**Comment by amitrnec** [comment]
Hi,
We have checked this functionality with below docker images.
image: scorpiobroker/scorpio:scorpio-aaio_FIWARE_8.1.0
#image: scorpiobroker/scorpio:scorpio-aaio-no-eureka_2.1.13
This functionality is working properly.

Please let us know if you have any concern with this version.

Thanks
Amit

**Comment by mdespland** [comment]
On my side, when I test with image: scorpiobroker/scorpio:scorpio-aaio-no-eureka_2.1.13

The result is 

```
Create an entity with temporal representation
    ✔ Create an entity the classical way (529ms)
{
    "id": "urn:entities:sensor:i7fky2nKbfJXvptc",
    "type": "MeteoStation",
    "temperature": {
        "type": "Property",
        "value": 22.2,
        "observedAt": "2020-06-09T21:32:52.98601Z",
        "unitCode": "CEL"
    },
    "@context": [
        "https://smartdatamodels.org/context.jsonld",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.3.jsonld"
    ]
}
    ✔ Retrieve the entity
{
    "id": "urn:entities:sensor:i7fky2nKbfJXvptc",
    "type": "MeteoStation",
    "temperature": {
        "type": "Property",
        "value": 22.2,
        "instanceId": "urn:ngsi-ld:a4861050-56aa-4229-8f9a-9e8ae8d30ca2",
        "observedAt": "2020-06-09T21:32:52.98601Z",
        "unitCode": "CEL"
    },
    "@context": [
        "https://smartdatamodels.org/context.jsonld",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.3.jsonld"
    ]
}
    ✔ Retrieve the temporal representation of the entity
409 {"type":"https://uri.etsi.org/ngsi-ld/errors/AlreadyExists","title":"Already exists.","details":"urn:entities:sensor:i7fky2nKbfJXvptc already exists"}
1)Add Temporal element for the existing property
```

So The POST /temporal/entities failed with a HTTP 409

When I test with scorpiobroker/scorpio:scorpio-aaio_FIWARE_8.1.0

```
Create an entity with temporal representation
✔ Create an entity the classical way (1317ms)
{
"id": "urn:entities:sensor:VKXvPc9tnWR80rMn",
"type": "MeteoStation",
"temperature": {
    "type": "Property",
    "value": 22.2,
    "observedAt": "2020-06-09T21:32:52.98601Z",
    "unitCode": "CEL"
},
"@context": [
    "https://smartdatamodels.org/context.jsonld",
    "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
]
}
✔ Retrieve the entity (543ms)
404 {"type":"http://uri.etsi.org/ngsi-ld/errors/ResourceNotFound","title":"Resource not found.","details":"Resource not found."}
1) Retrieve the temporal representation of the entity
✔ Add Temporal element for the existing property (540ms)
```

The POST /temporal/entities works, but the GET /temporal/entities done before failed with a 404

**Comment by amitrnec** [comment]
Hi,
We have tested with image: scorpiobroker/scorpio:scorpio-aaio-no-eureka_2.1.13

1. create entity (http://172.30.48.25:9090/ngsi-ld/v1/entities)
2. Get Entity(http://172.30.48.25:9090/ngsi-ld/v1/entities/urn:entities:sensor:VKXvPc9tnWR80rMn)
3.  Get Temporal entity (http://172.30.48.25:9090/ngsi-ld/v1/temporal/entities/urn:entities:sensor:VKXvPc9tnWR80rMn)
4.  Add temporal element in existing entity(http://172.30.48.25:9090/ngsi-ld/v1/temporal/entities/urn:entities:sensor:VKXvPc9tnWR80rMn/attrs)
 {
"temperature_NEW": {
    "type": "Property",
    "value": 24.2,
    "observedAt": "2020-06-09T21:32:52.98601Z",
    "unitCode": "CEL"
},
"@context": [
    "https://smartdatamodels.org/context.jsonld",
    "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
]
}
5. Get temporal entity(http://172.30.48.25:9090/ngsi-ld/v1/temporal/entities/urn:entities:sensor:VKXvPc9tnWR80rMn)
Now We have followed all these step and all are working properly.
So We think you are follow same step, correct ?

we will check same functionality with scorpiobroker/scorpio:scorpio-aaio_FIWARE_8.1.0 image .
Thanks,
Amit

**Comment by mdespland** [comment]
Hello
No for the 4 I use a POST on /temporal/entities not /temporal/entities/<id>/attrs
I will check with /attrs

**Comment by amitrnec** [comment]
Hi,
We have tested with scorpiobroker/scorpio:scorpio-aaio_FIWARE_8.1.0 image.
It is also working properly.
Thank you.

Thanks,
Amit.

**Comment by mdespland** [comment]
With the POST on /temporal/entities not /temporal/entities//attrs it works better (and well with scorpio:scorpio-aaio-no-eureka_2.1.13) but with scorpio:scorpio-aaio_FIWARE_8.1.0 the value added in the create entity is not return with the GET temporal

**Comment by amitrnec** [comment]
Hi,
As your comment are you following same step.
1. Create entity
2. Retrieve entity
3. Retrieve Temporal entity
4.  Add attributes in existing entity (http://172.30.48.25:9090/ngsi-ld/v1/entities/urn:entities:sensor:VKXvPc9tnWR80rMn/attrs)
5.  Add attributes in existing temporal  entity (http://172.30.48.25:9090/ngsi-ld/v1/temporal/entities/urn:entities:sensor:VKXvPc9tnWR80rMn/attrs) 
6. Repeat step 3
All are working properly as expected with scorpio:scorpio-aaio_FIWARE_8.1.0 

Thanks.

**Comment by mdespland** [comment]
With scorpio-aaio_FIWARE_8.1.0

After the creation of entity , the GET /entities and GET /temporal/entities work

``` 
  Create an entity with temporal representation
    ✔ Create an entity the classical way (559ms)
{
    "id": "urn:entities:sensor:2t2pvmuY3rNEf51n",
    "type": "MeteoStation",
    "temperature": {
        "type": "Property",
        "value": 22.2,
        "observedAt": "2020-06-09T21:32:52.98601Z",
        "unitCode": "CEL"
    },
    "@context": [
        "https://smartdatamodels.org/context.jsonld",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}
    ✔ Retrieve the entity (654ms)
{
    "id": "urn:entities:sensor:2t2pvmuY3rNEf51n",
    "type": "MeteoStation",
    "temperature": {
        "type": "Property",
        "value": 22.2,
        "instanceId": "urn:ngsi-ld:22de260d-af2b-4147-9af1-d89275a4ff47",
        "observedAt": "2020-06-09T21:32:52.98601Z",
        "unitCode": "CEL"
    },
    "@context": [
        "https://smartdatamodels.org/context.jsonld",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}
    ✔ Retrieve the temporal representation of the entity (555ms)

``` 

But after adding attributes to the existing temporal entity POST /temporal/entities/<id>/attrs


```
    ✔ Add Temporal element for the existing property (530ms)
{
    "id": "urn:entities:sensor:2t2pvmuY3rNEf51n",
    "type": "MeteoStation",
    "temperature": [
        {
            "type": "Property",
            "value": 80,
            "instanceId": "urn:ngsi-ld:34243cec-a143-4d3c-9fab-1422d0360782",
            "observedAt": "2021-08-02T12:05:00Z"
        },
        {
            "type": "Property",
            "value": 130,
            "instanceId": "urn:ngsi-ld:6e2a7924-3396-488f-95f2-159e82e2a2d6",
            "observedAt": "2014-08-01T12:03:00Z"
        },
        {
            "type": "Property",
            "value": 60,
            "instanceId": "urn:ngsi-ld:ce2bca01-3b24-41d2-9a53-606fd76b8822",
            "observedAt": "2016-08-03T12:07:00Z"
        },
        {
            "type": "Property",
            "value": 100,
            "instanceId": "urn:ngsi-ld:d3ce5e0b-b329-4896-9cb5-129973279450",
            "observedAt": "2012-08-03T12:07:00Z"
        }
    ],
    "@context": [
        "https://smartdatamodels.org/context.jsonld",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}
1) Retrieve the temporal representation of the entity
``` 

The first value disappear from the list :
```
"temperature": {
        "type": "Property",
        "value": 22.2,
        "instanceId": "urn:ngsi-ld:22de260d-af2b-4147-9af1-d89275a4ff47",
        "observedAt": "2020-06-09T21:32:52.98601Z",
        "unitCode": "CEL"
    },
```

with scorpiobroker/scorpio:scorpio-aaio-no-eureka_2.1.13 it is ok

**Comment by amitrnec** [comment]
Hi,
We will check accordingly.
Thanks.

**Comment by ScorpioBroker** [comment]
Hi @mdespland,

the situation with the FIWARE release from our point is basically that's a 11 month old release. We would highly recommend using latest or 2.1.14 in general. The FIWARE releases are not that regular and tbh. out of our control. 

Best Regards

**Comment by mdespland** [comment]
Hi,

Yes agree to use the latest version :) 
But for this I need to have on my side the test suite to check the feature I use still working as expected 
And to be sure what is the expected behavior

I will also see how to contribute to the test suite of the ETSI CIM
