### ISSUE TITLE
Problem connecting ScorpioBroker with FIWARE IoT Agent for a JSON-based Protocol

### ISSUE THREAD

**Issue by acanovasodins** [ScorpioBroker/ScorpioBroker#308]
Hi,

I'm trying to connect ScorpioBroker with [FIWARE IoT Agent for a JSON-based Protocol](https://github.com/telefonicaid/iotagent-json) using MQTT transport. In the device provisioning the NGSI-LD entity is created successfully and the MQTT publications correctly update entity in Scorpio Broker. But when I execute PATCH on the command attribute, Scorpio Broker returns an error that the attribute is not present in the entity. Below I detail the entire process:

1.- Provisioned device in IoT Agent:
```json
{
  "count": 1,
  "devices": [
    {
      "device_id": "TEST-DEVICE",
      "service": "test",
      "service_path": "/",
      "entity_name": "urn:ngsi-ld:Device:Test",
      "entity_type": "Device",
      "transport": "MQTT",
      "attributes": [
        {
          "object_id": "value",
          "name": "value",
          "type": "Property"
        },
        {
          "object_id": "timestamp",
          "name": "TimeInstant",
          "type": "ISO8601"
        }
      ],
      "lazy": [],
      "commands": [
        {
          "object_id": "setpoint",
          "name": "setpoint",
          "type": "command"
        }
      ],
      "static_attributes": [],
      "protocol": "MQTT_JSON"
    }
  ]
}
```
2.- The NGSI-LD entity in ScorpioBroker is correct:
```json
{
  "id": "urn:ngsi-ld:Device:Test",
  "type": "Device",
  "setpoint": {
    "type": "command",
    "value": ""
  },
  "setpoint_info": {
    "type": "Property",
    "value": {
      "type": "commandResult",
      "@value": " "
    }
  },
  "setpoint_status": {
    "type": "Property",
    "value": {
      "type": "commandStatus",
      "@value": "UNKNOWN"
    }
  },
  "value": {
    "type": "Property"
  },
  "@context": [
    "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.3.jsonld"
  ]
}
```
As explained here:
https://github.com/FIWARE/tutorials.LD-Subscriptions-Registrations
The attribute "setpoint" is dinamically added to the entity, internally ScorpioBroker makes this GET request to the IoT Agent:
```
GET /ngsi-ld/v1/entities?id=urn%3Angsi-ld%3ADevice%3ATest HTTP/1.1
Accept: application/ld+json
Host: 10.10.1.10:4041
```
```
HTTP/1.1 200 OK
Content-Type: application/ld+json; charset=utf-8

{
  "@context":"https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld",
  "id":"urn:ngsi-ld:Device:Test"
  "type":"Device",
  "setpoint": {
    "type":"command",
    "value":""
  }
}
```
3.- The ContextSourceRegistration is correct:
```json
{
  "id": "urn:ngsi-ld:csourceregistration:-316130612",
  "type": "ContextSourceRegistration",
  "endpoint": "http://10.10.1.10:4041",
  "information": [
    {
      "properties": "setpoint",
      "entities": [
        {
          "id": "urn:ngsi-ld:Device:Test",
          "type": "Device"
        }
      ]
    }
  ],
  "@context": [
    "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.3.jsonld"
  ]
}
```
4.- The PATCH request for update "setpoint" command attribute:
```
PATCH http://localhost:9090/ngsi-ld/v1/entities/urn%3Angsi-ld%3ADevice%3ATest/attrs/setpoint
Link: <https://uri.etsi.org/ngsi-ld/primer/store-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json" type="application/ld+json"
Content-Type: application/json
NGSILD-Tenant: test
NGSILD-Path: /

{
  "type": "Property",
  "value": ""
}
```
```
HTTP/1.1 404

{
  "type": "https://uri.etsi.org/ngsi-ld/errors/ResourceNotFound",
  "title": "Resource not found.",
  "details": "Provided attribute is not present"
}
```
Why, when making the PATCH request, does the ScorpioBroker not detect that the "setpoint" attribute is in the ContextSourceRegistration and forward the update to the IoT Agent?

Thanks

**Comment by pawannec** [comment]
Hi,
Can you please share the setup details and Scorpio version ? did you use docker or a development setup? in case please share the docker version or development branch correspondingly.
Thanks

**Comment by acanovasodins** [comment]
Hi
> Can you please share the setup details and Scorpio version ? did you use docker or a development setup?

I used docker setup

> in case please share the docker version or development branch correspondingly.

https://github.com/ScorpioBroker/ScorpioBroker/blob/development/docker-compose-aaio.yml

Thanks

**Comment by mohitNEC** [comment]
Hi,

There is an NGSI-LD version issue while integrating Scorpio Broker with IoT Agent. Currently, Scorpio Broker is using NGSI-LD v1.3.1
NGSI-LD does not supports the type: "command" , as the issue regarding this has already been raised

https://github.com/telefonicaid/iotagent-ul/issues/538

IoT Agent Integration is not part of Development branch so after IoT Agent updated then we will merge it in the Development Branch.

Thanks

**Comment by Blobonat** [comment]
A very good explanation of the underlying specification problem is given in [telefonicaid/iotagent-ul/issues/573](https://github.com/telefonicaid/iotagent-ul/issues/573#issuecomment-1203142396).
