### ISSUE TITLE
Subscription Notificatios not following the structure model according to standard.

### ISSUE THREAD

**Issue by mainakae** [ScorpioBroker/ScorpioBroker#31]
Hello everyone,

I've noticed that, according to the standard as defined in _GS CIM 009 V1.2.1_, point 5.3.1, the Notification should follow a different structure as it is being used now. Now the entity is sent as the topmost object in the document being sent, whereas it should be contained in a "data" attribute inside a notification object, that would also contain the time of the notification (notifiedAt), the subscription ID, among others.

Thanks for your time and attention,
Pedro

**Comment by ScorpioBroker** [comment]
Hi Pedro,

thanks for the spot. I've fixed it now.

BR
Benni
