### ISSUE TITLE
ProblemDetails Error structure typo

### ISSUE THREAD

**Issue by kiskit** [ScorpioBroker/ScorpioBroker#310]
Hi,

According to the specification, the ProblemDetails structure should contain a field named "detail". On at least a few responses (e.g. bad request), Scorpio returns a field named "details", breaking compatibility.
The specification mentions that field in table 6.4.3.1-1 (at least for versions 1.3.1 and 1.5.1).

**Comment by amitrnec** [comment]
Hi,
We have fixed  this issue in #311 

Thanks,
Amit.

**Comment by amitrnec** [comment]
Hi,
Now we have merged in Dev branch.

Thanks.
