### ISSUE TITLE
No 'next' link in headers when querying using limit and offset

### ISSUE THREAD

**Issue by PascalDesmet** [ScorpioBroker/ScorpioBroker#316]
Hi there,

I've created a local Scorpio Broker using the latest compose file. [docker-compose.txt](https://github.com/ScorpioBroker/ScorpioBroker/files/8993116/docker-compose.txt)
I've added some content and that is working fine. 
[Content.zip](https://github.com/ScorpioBroker/ScorpioBroker/files/8993122/Content.zip)

When I try to retrieve entities in a paged manner as described in GS CIM 009 using a get 'http://localhost:9090
/ngsi-ld/v1/entities?type=https://uri.fiware.org/ns/data-models%23TrafficFlowObserved&limit=2&offset=6', I always get the same first 2 entities back and there is no 'next' link indication in the headers of the returned result.
Is it possible issue #44 is back?

Kind regards,
Pascal Desmet

**Comment by ScorpioBroker** [comment]
Hi,
yes this was a bug. We fixed it now. Thanks for the report. dockerhub version 2.1.15 has the bugfix for this.
