### ISSUE TITLE
Create or Update temporal entity may return 409

### ISSUE THREAD

**Issue by kiskit** [ScorpioBroker/ScorpioBroker#318]
Hello guys,

So when using POST /temporal/entities with a body that contains an id that already exists, I get a conflict (409). The spec seems to say it's not allowed (6.18.3.1) and that it should update fields of the temporal entity instead (chapter 5.6.11 says update if it exists too).
Please advise.

**Comment by amitrnec** [comment]
Hi,
Yes correct that's a bug. We will fix it.

Thanks,
Amit.

**Comment by kiskit** [comment]
Thanks for your reactivity

**Comment by ScorpioBroker** [comment]
Hi, dockerhub version 2.1.15 has the bugfix for this.
