### ISSUE TITLE
Temporal entity attribute delete never returns 404

### ISSUE THREAD

**Issue by kiskit** [ScorpioBroker/ScorpioBroker#319]
Hello fellow Scorpio people,
Tried this:
```bash 
curl --request DELETE --url http://127.0.0.1:9090/ngsi-ld/v1/temporal/entities/uri:te1/attrs/xyztdfgw
```
with existing te1.
It may work once if the attribute exists but the second time it should return 404. It returns 204 instead.

**Comment by ScorpioBroker** [comment]
Hi, yes we are currently working on this already 
https://github.com/ScorpioBroker/ScorpioBroker/pull/315
should be out with the next release.

**Comment by kiskit** [comment]
Sorry didn't find the issue when I first looked

**Comment by ScorpioBroker** [comment]
No worries... better one report too much as one to less. Was just pointing out that this should be fixed soonish.

**Comment by kiskit** [comment]
Cool, thanks. It's unclear to me if #315 applies also to temporal entities attribute instances but I think it behaves the same.

**Comment by amitrnec** [comment]
Hi,
Now fixed this issue and merged in dev branch.
Thanks.
