### ISSUE TITLE
GET /ngsi-ld/v1/entities mandatory parameters

### ISSUE THREAD

**Issue by papr8ka** [ScorpioBroker/ScorpioBroker#326]
# GET /ngsi-ld/v1/entities mandatory parameters

Hi,

The endpoint GET /ngsi-ld/v1/entities does not match the [ngsi ld specification](https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.05.01_60/gs_cim009v010501p.pdf) at [6.4.3.2](https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.05.01_60/gs_cim009v010501p.pdf#%5B%7B%22num%22%3A540%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22FitH%22%7D%2C452%5D).

The specification expects **attrs** OR **q** OR **geometry** OR **type** as mandatory parameter(s). The current implementation returns 400 if neither of **type**/**attrs** are found. This is not suitable for whole entities listing based on value of a given field.

## Current behavior

```bash
curl http://127.0.0.1:9090/ngsi-ld/v1/entities?q=attribute==something
```

400 Bad Request:

```json
{
	"type":"https://uri.etsi.org/ngsi-ld/errors/BadRequestData",
	"title":"Bad Request Data.",
	"detail":"Missing mandatory minimum parameter type or attrs"
}
```

## Expected behavior

(In case there is no entity)

```bash
curl http://127.0.0.1:9090/ngsi-ld/v1/entities?q=attribute==something
```

200 OK:

```json
[ ]
```

**Comment by ScorpioBroker** [comment]
Hi, 
yes this is correct. This is a change since 1.3.1 that a q or geoQ query is enough to implicit declare attrs. We haven't implemented this yet.

**Comment by papr8ka** [comment]
Hi,

Do you have an idea of the time frame for this implementation? I saw in the project's [README.md](https://github.com/ScorpioBroker/ScorpioBroker#further-resources) that the version mentioned for ETSI specification is 1.2.2. Is it something that will evolve or is it the final target?
In the meantime, do you have an idea for a workaround ? I don't know the full list of attributes of the entities I want to list, and the filter is only based on the value of one attribute. I could make two requests instead of one, but if you have another idea, I'm interested.

Thanks in advance.

**Comment by ScorpioBroker** [comment]
Hi,

tbh. that is an oversight on our side. We are basically on 1.3.1 at the moment with this excluded and some 1.4.1/1.5.1 things added. We are continuously trying to add the updates of the spec. Seeing that this should be already in, we definatly put it on the front of the road map. So within the next 6 weeks or so (it's vacation season ... ) this should work, maybe earlier but no guaranties. 

About the workaround ... do you know the type of entities you want to query? this could also be a list of comma separated types (sorry no wildcards) than you can query it in one go.

**Comment by papr8ka** [comment]
Hi,

No, I have no idea of the entity type I'm requesting. My use case is very specific, and can only be done through q parameter.

In this case I'll wait for the feature, thanks!

**Comment by amitrnec** [comment]
Hi
Now this is implemented.

Thanks.
