### ISSUE TITLE
Add DateTime support including milliseconds for notifiedAt

### ISSUE THREAD

**Issue by Blobonat** [ScorpioBroker/ScorpioBroker#327]
As far as I have seen Scorpio uses the `YYYY-MM-DDThh:mm:ssZ`-format for `notifiedAt` inside a notification. It would be nice to also support a `DateTime`-string including milliseconds for `notifiedAt` to have a more precise timestamp.

**Comment by amitrnec** [comment]
Hi,
Now fixed this issue #328 

Thanks.
