### ISSUE TITLE
Retrieving entity by ID returns 404 even when querying by type finds it

### ISSUE THREAD

**Issue by mainakae** [ScorpioBroker/ScorpioBroker#33]
SETUP: docker container-per-service

After re-creating all services (but postgres) all entities seem to be searchable by regular queries, but accessing those entities straight by ID doesn't find them, just throws a 404 error.

**Comment by ScorpioBroker** [comment]
Hi,
yes i think i know how this appears. 
2 Reasons 
1. kafka docker doesn't keep its state i need to figure out what to save here.
2. at the moment our strategy was to sync from kafka to postgres but not the other way around.
This means if by some reason kafka logs get deleted outside of the flow of the broker (a.k.a. me deleting the log files) there is a missing sync between postgres and kafka. I need to find a proper synching strategy here.

**Comment by xannz** [comment]
I have some follow up questions regarding this issue:
- Does Scorpio expect Kafka to have it's topics retention set to infinity? It seems normal to me that Kafka deletes old messages. 
- Does Scorpio read directly from random offsets inside a Kafka topic? If so, why not directly from the Postgres db?

**Comment by ScorpioBroker** [comment]
Hi,
yes at the moment that is the case for the retrieve entity part. Honestly it's a left over from the initial idea to use only kafka (with ksql). As it is only in the entity retrieve part it kind of flew under the radar for now. I'm currently in the process of eliminating the parts. I'll come back once i'm done.

**Comment by ScorpioBroker** [comment]
Hi,
i changed the retrieve part to use the database so this error should be gone for good.
