### ISSUE TITLE
No body returned by /entityOperations/create on success

### ISSUE THREAD

**Issue by kiskit** [ScorpioBroker/ScorpioBroker#330]
## Problem statement
When using /entityOperations/create and obtaining a 201 status, the body is empty.
## Modus Operandi
```json
[
	{
		"id": "uri:entity1",
		"type": "Temperature",
		"dataProvider": {
			"type": "Property",
			"value": "62349895462c09197b1d6776"
		},
		"xy": {
			"type": "Property",
			"value": "apopo"
		}
	}
]
```
## Expectations
The status returned is **201** and the body is **empty**. According to the specification, it should contain **the list of identifiers of the entities successfully created**.

**Comment by amitrnec** [comment]
Hi,
Now fixed this issue #332 

Thanks.
