### ISSUE TITLE
Eureka Server is not working with scorpiobroker 

### ISSUE THREAD

**Issue by SURAJKALLOLI** [ScorpioBroker/ScorpioBroker#333]
Hi,
Java 17
springboot version 2.7.0

After running the docker-compose-aaio-gateway.yml file, Eureka server is not running on localhot:8761 and  I am not able to view the Eureka server dashboard but in logs it showing that client is registering with eureka and zuul also not taking the servises only scorpiobroker and gateway is working on port 9090.

**Comment by ScorpioBroker** [comment]
Hi,

docker-compose-aaio.yml is not starting/working with eureka. It's starting the version which doesn't implement the eureka client. Please have a look at the https://github.com/ScorpioBroker/ScorpioBroker/blob/development/docker-compose-aaio-gateway.yml. You would still need to edit the port "8761" to "8761:8761" to get it reachable.

**Comment by SURAJKALLOLI** [comment]
Yes, docker-compose-aaio-gateway.yml this file only i am talking about.
And eureka server taking direction to http://localhost:59722/ not on port 8761:8761  and how to zuul interact with this , i want to know.

**Comment by ScorpioBroker** [comment]
Hi, 

I'm not quite sure what you mean by "eureka server taking direction to http://localhost:59722/" 8761 is the default port and we are not changing it in our eureka. 
Just FYI. the gateway we are providing is not Zuul based anymore but the newer Spring Gateway. 
If you are looking for a config for Zuul you can check out this older commits
https://github.com/ScorpioBroker/ScorpioBroker/blob/1d1ab95d14bac39a636f7f68a21e455224db057c/SpringCloudModules/gateway/src/main/resources/application-aaio.yml 
this is how the gateway is configured. So all services are registered by name and looked up like this.
