### ISSUE TITLE
Question: Is Scorpio integration with QuantumLeap or timeseries DB like Timescaledb/CreateDB in roadmap?

### ISSUE THREAD

**Issue by yshashix** [ScorpioBroker/ScorpioBroker#336]
Hi team,
I am looking forward to knowing if you have any plans for integration with timeseries database.
I see the Fiware application QuantumLeap subscription trying to do it but currently, but it does not support NGSI-LD fully
#227 or do you guys expect QuantumLeap to do it?

**Comment by martin-p-bauer** [comment]
Hi @yshashix,
NGSI-LD itself supports a temporal API and Scorpio implements the core version of it, i.e. you can request temporal information from a specified time interval. Scorpio does not yet implement the aggregation functionality defined in NGSI-LD v1.4, which is on our medium-term roadmap - after implementing this, the functionality will be quite similar to what Quantum Leap provides. To our understanding, QuantumLeap is currently able to ingest NGSI-LD information (okay, looking at the above, there still seem to be issues), but the query interface continues to be based on NGSIv2. We would very much like to see the NGSI-LD temporal API supported by QuantumLeap, but for that you have to ask the QuantumLeap team.

**Comment by yshashix** [comment]
@martin-p-bauer ,
Thank you for the clarification.
Glad to know that Scorpio itself implements temporal API, but does it save time-series data in timescaleDB or saves date postgress only with timestamp? I thought by default broker would keep the latest state of the entity, if so then where are time-series data persisted? (Regarding quantum leap, I will ask them, thnx)

**Comment by ScorpioBroker** [comment]
Hi so what happens in Scorpio 
everything is in postgres there are a bunch of different databases for "live" entities and for the temporal interface/entities. 
To be precise for history we save the attribute instances separately with the timestamps (observedAt, createdAt, modifiedAt) as indexed fields.
You can use the temporal interface separately to create temporal entities directly. /ngsi-ld/v1/temporal/entities
On top, unless it's switched off (scorpio.history.autorecording setting), when you create/update/append entities via /ngsi-ld/v1/entities we are auto recording the entities in the temporal part to keep a history.

**Comment by yshashix** [comment]
Thanks for your insight. It was helpful to understand.
