### ISSUE TITLE
Error deploying Dist-deployment Scorpio-broker v2.1.13

### ISSUE THREAD

**Issue by Anupamskd7** [ScorpioBroker/ScorpioBroker#341]
Description:
When deploying the dist-deployment files (https://github.com/ScorpioBroker/ScorpioBroker/tree/2.1.13/KubernetesFile/dist-deployment-files) on Kubernetes cluster, the "_Atcontextserver_" miscroservice goes into error state with the following error in the pod event:

- Liveness probe failed: sh: 1: curl: not found
- Back-off restarting failed container
- Readiness probe failed: sh: 1: curl: not found

Even tried deployment through Helm, we are getting the same error.

Steps to reproduce:
1. Import the deployment files from storage, then deployment and then the service folder into the K8s cluster.
2.  Or, git clone and helm install scorpio scorpio-broker

Affected Product Version:
Scorpio broker v2.1.13

Environment details (with versions):

OS: Centos 7
Env: K8s on Rancher, Helm

**Comment by mohitNEC** [comment]
Hi Anupam,

We have fixed this issue #346 

Thanks
