### ISSUE TITLE
Simplified Temporal Representation of an Entity not following the NGSI-LD specification

### ISSUE THREAD

**Issue by Blobonat** [ScorpioBroker/ScorpioBroker#345]
Hi,

when requesting a simplified temporal representation of an entity using the `options=temporalValues` the NGSI-LD spefication states (v1.6.1 section 4.5.9):
> The simplified temporal representation of an Entity shall include the following: [...]
> For each Property, a member whose key is the Property Name (a term). The member value shall be a JSON-LD object labelled with the type "Property". Such JSON-LD object shall only **contain a member whose key shall be "values"**. The value of the referred values member shall be a JSON-LD Array that shall contain as many array elements as Property instances (i.e. data points of the concerned Property) being represented. **Each array element shall be another Array containing exactly two array elements**: the first element shall be a Property value and the second element shall correspond to the associated Temporal Property (for instance "observedAt").

Currently Scorpio (`scorpiobroker/all-in-one-runner:spring-kafka-latest`) returns a Simplified Temporal Representation of an Entity with the attribute `airTemperature` like this:
```
{
"id":"urn:ngsi-ld:Building:building4",
"type":"Building",
"airTemperature":[10.5,"2022-10-09T18:04:12Z",-3.5,"2021-12-08T15:23:12Z"]
}
```

Following the spec I expect the entity representation like this (I am unsure whether or not `"type": "Property",` has to be actually included):
```
{
"id":"urn:ngsi-ld:Building:building4",
"type":"Building",
"airTemperature": {
    "type": "Property",
    "values": [[10.5, "2022-10-09T18:04:12Z"], [-3.5, "2021-12-08T15:23:12Z"]]
  }
}
```

**Comment by amitrnec** [comment]
Hi,
Now we have fixed this issue #349 

Thanks
