### ISSUE TITLE
Subscription requires at least one notification.attributes to be specified

### ISSUE THREAD

**Issue by mainakae** [ScorpioBroker/ScorpioBroker#35]
Hello everyone.

According to the specification, a subscription without any specified notification.attributes, should return all of the available properties of the entity. The implementation (as of now) fails returning a 500 error.

**Example**
```jsonnet
POST /ngsi-ld/v1/subscriptions
{
    "type": "Subscription",
    "entities": [
        {
            "type": "https://w3id.org/iot/qoi#Quality"
        }
    ],
    "watchedAttributes": [
        "https://w3id.org/iot/qoi#prop1"
    ],
    "notification": {
        "endpoint": {
            "uri": "http://localhost:3000/api/notification",
            "accept": "application/json"
        },
        "format": "normalized",
        "attributes": null
    },
    "@context": [
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}
```

**Response**
```json
{
    "timestamp": "2019-11-17T15:02:30.151+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "No message available",
    "path": "/"
}
```

Best regards,
Pedro.

**Comment by MS-Fiware** [comment]
Hi,

have you tried to remove the `"attributes"` attribute or set it to `undefined`? According to spec `"attributes"` shall be undefined in order to include all attributes. Actually `null` is a defined value.

Regards,
Michael

**Comment by mainakae** [comment]
Good point, you are right, null values are disallowed as of NGSI-LD specs.

Anyway, it also happens when the field is left undefined, we where trying different alternatives and tried also with null (just in case).

Best regards,
Pedro
