### ISSUE TITLE
Update Entity not working

### ISSUE THREAD

**Issue by rpahli** [ScorpioBroker/ScorpioBroker#352]
It is currently not possible to update an entity.

Docs: https://github.com/ScorpioBroker/ScorpioBroker/blob/development/docs/en/source/API_walkthrough.rst#updating-an-entity--appending-to-an-entity

It looks like the Controller does not contain an update method: https://github.com/ScorpioBroker/ScorpioBroker/blob/development/Core/EntityManager/src/main/java/eu/neclab/ngsildbroker/entityhandler/controller/EntityController.java

**Comment by ScorpioBroker** [comment]
Hi, 

sorry this an error in the documentation. The update requires the /attrs after the entity id. 
this is wrong in our documentation but correct in the impl (chapter 6.6 in the spec).
@amitrnec could you please check that part of the documentation. 

Thanks

**Comment by amitrnec** [comment]
Hi,
Now have corrected in document #353 

Thanks
