### ISSUE TITLE
Subscription is not working

### ISSUE THREAD

**Issue by Gaurav-sen1** [ScorpioBroker/ScorpioBroker#354]
Description:
Scorpio Subscription is not working while provisioning an IOT Device. 

**Subscription  API :**
curl --location --request POST ' _contextBrokerIP_:9090/ngsi-ld/v1/subscriptions/' \
--header 'Content-Type: application/json' \
--header 'fiware-service: fiwaredt' \
--header 'fiware-servicepath: /digitaltwin' \
--data-raw '{
  "id": "urn:ngsi-ld:Entity:FdtEntity16",
  "type": "Subscription",
  "entities": [{
                "type": "Entity6"
  }],
  "notification": {
        "endpoint": {
                "uri": "http://_notificationIP_:5555/contentListener",
                "accept": "application/json"
        }
  }
}' 

**Device Provisioning API** 
curl --location --request POST 'http://_DeviceProvisionIP_:4041/iot/devices/' \
--header 'cache-control: no-cache' \
--header 'content-type: application/json' \
--header 'fiware-service: fiwaredt' \
--header 'fiware-servicepath: /digitaltwin' \
--data-raw '{
    "devices": [
        {
            "device_id":"device015",
            "entity_name":"urn:ngsi-ld:Entity:FdtEntity16",
            "entity_type":"Entity6",
            "protocol":"IoTA-JSON",
            "attributes": [
                {"object_id":"transactionId", "name":"transactionId","type":"String"},
                {"object_id": "dateIssued", "name":"dateIssued" ,"type":"DateTime"},
                {"object_id":"alert_count", "name":"alert_count", "type":"Integer"},
                {"object_id":"category", "name":"category", "type":"String"},             

                {"object_id":"alert_array", "name":"alert_array","type":"Property"},
                {"object_id":"location", "name":"location", "type":"geo:point"},
                {"object_id":"source", "name":"source", "type":"String"},
                {"object_id":"deviceId", "name":"deviceId", "type":"String"},
                {"object_id":"address", "name":"address", "type":"String"}
            ]
    }
    ]
}'

Docker Image:
scorpiobroker/scorpio:scorpio-aaio-no-eureka_latest

Environment details (with versions):
OS: Centos 7
Env: localhost, Docker

**Comment by amitrnec** [comment]
Hi,
Please add header 'NGSILD-Tenant: fiwaredt' instead of 'fiware-service: fiwaredt' and 'fiware-servicepath: /digitaltwin' header in case of subscription.

Thanks,
Amit Raghav.

**Comment by Gaurav-sen1** [comment]
Hello Amit Raghav sir,

Thank you for the guidance, it is working now.
