### ISSUE TITLE
Subscription specifying a notification HTTP header failing

### ISSUE THREAD

**Issue by steveaitch** [ScorpioBroker/ScorpioBroker#356]
I'm trying to set up a subscription which specifies a header to send with the notification but it is giving a Java error:

	{
		"id": "urn:ngsi-ld:Subscription:subname",
		"type": "Subscription",
		"entities": [
			{
				"type": "https://uri.fiware.org/ns/data-models#AirQualityObserved"
			}
		],
		"notification": {
			"endpoint": {
				"uri": "https://XXX.execute-api.eu-west-1.amazonaws.com/default/YYY",
				"accept": "application/json",
				"receiverInfo": [{"Authorization": "API-KEY"}]
				
			}
		},
		"@context": [
			"https://raw.githubusercontent.com/smart-data-models/data-models/master/context.jsonld"
		]
	}

This results in:

	{
		"type": "https://uri.etsi.org/ngsi-ld/errors/BadRequestData",
		"title": "Bad Request Data.",
		"detail":"Failed to parse notification parameter.
	Cannot invoke "java.util.List.iterator()" because the return value of "java.util.Map.get(Object)" is null"
	}

Without the receiverInfo entry it works fine. This is in version 3.0.5.

**Comment by amitrnec** [comment]
Hi,
This issue has been fixed #360 

Thanks.
