### ISSUE TITLE
GET /ngsi-ld/v1/types?details=true returns TenantNotFound error

### ISSUE THREAD

**Issue by PascalDesmet** [ScorpioBroker/ScorpioBroker#357]
I've installed version 3.0.1 and the call http://localhost:9090/ngsi-ld/v1/types?details=true returns
{
    "type": "https://uri.etsi.org/ngsi-ld/errors/TenantNotFound",
    "title": "Tenant not found.",
    "details": "Tenant not found."
}

as the same call in version 2.x worked fine returning an array of EntityTypes each having an array of attributeNames.

Is this broken or do I have to construct my API in another manner ?

kind regards,
Pascal Desmet

**Comment by amitrnec** [comment]
Hi
Thanks for the information.
Can you share the full name of version that you are using?

Thanks,
Amit Raghav.

**Comment by amitrnec** [comment]
Hi
Reminder for share the full name of version that you are using.

Thanks.

**Comment by amitrnec** [comment]
Hi
Reminder for share the full name of version that you are using.

Thanks.
