### ISSUE TITLE
Subscription with watchedAttributes: null breaks subscription mechanism

### ISSUE THREAD

**Issue by mainakae** [ScorpioBroker/ScorpioBroker#36]
Hello everybody,

In this case, issuing a subscription with watchedAttributes set to null, which according to standard should trigger notifications upon change of any attribute, not only returns a 500 error, but also degrades the overall performance of the broker by consuming unusual amounts of resources (both ram and network usage, as described in issue #26).

This is the usecase:

`POST /ngsi-ld/v1/subscriptions`
```json
{
    "type": "Subscription",
    "entities": [
        {
            "type": "https://w3id.org/iot/qoi#Quality"
        }
    ],
    "watchedAttributes": null,
    "notification": {
        "endpoint": {
            "uri": "http://localhost:3000/api/notification",
            "accept": "application/json"
        },
        "format": "normalized",
        "attributes": [
        	"https://w3id.org/iot/qoi#prop2"
        ]
    },
    "@context": [
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}
```

Response
```json
{
    "timestamp": "2019-11-18T08:43:17.879+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "No message available",
    "path": "/"
}
```

Best regards,
Pedro.

**Comment by ScorpioBroker** [comment]
Hi, 
i tested this yesterday with the latest commit and didn't get that error. I fixed a few things in the serialization during the runner changes. So maybe i fixed that one "accidentally". On which version did you test this.
Regards
Benni
