### ISSUE TITLE
 Supports Role Based Access Control policies for security thing

### ISSUE THREAD

**Issue by SURAJKALLOLI** [ScorpioBroker/ScorpioBroker#365]
We trying to apply policies to the API , The aim is to client request for a resource to an API, and based on the defined policies, the client is able or not to access the resource. Is there any enhancement in future for  this , let me know.

**Comment by ScorpioBroker** [comment]
Hi,

no currently there is nothing specific planed on this end. From FIWARE's point of view the policy enforcement should happen with keycloak in front. You would configure the respective endpoints for your user. 
This is an open item on the ETSI list to my understanding but there is nothing concrete at the moment.
