### ISSUE TITLE
Performance difference using ngsi-ld/v1/entities?type=

### ISSUE THREAD

**Issue by mathias-vh** [ScorpioBroker/ScorpioBroker#366]
Hi,

We are using Scorpio broker version all-in-one-runner:java-kafka-3.0.5 at the moment together with Apache Nifi and Kafka. Each Kafka topic consumed is a different ngsi-ld entity type, all have very different loads.

For example, one type has around 200 messages per minute, another has around 10 per minute and another type has around 50K per minute.

When using the following endpoint, ngsi-ld/v1/entities?type=<type>&limit=10, we are getting an almost instant response for some types but using the same endpoint for a different type, even after 30 minutes we are getting no response.

Below is the query plan for an example type that gives an instant response in postgres too:

SELECT DISTINCT data_without_sysattrs as data 
FROM entity 
WHERE ((type = 'https://uri.etsi.org/ngsi-ld/default-context/DENMaccident')) 
LIMIT 10

  | 1. | Limit
  | 2. | Aggregate
  | 3. | Index Scan using i_entity_type on entity as entityIndex Cond: (type = 'https://uri.etsi.org/ngsi-ld/default-context/DENMaccident'::text)

Below is the query plan for an example type that also fails to give a response in postgres (30min+ waiting time):

SELECT DISTINCT data_without_sysattrs as data 
FROM entity 
WHERE ((type = 'https://uri.etsi.org/ngsi-ld/default-context/DENMroadworks')) 
LIMIT 10

  | 1. | Limit
  | 2. | Unique
  | 3. | Gather Merge
  | 4. | Sort
  | 5. | Bitmap Heap Scan on entity as entityRecheck Cond: (type = 'https://uri.etsi.org/ngsi-ld/default-context/DENMroadworks'::text)
  | 6. | Bitmap Index Scan using i_entity_typeIndex Cond: (type = 'https://uri.etsi.org/ngsi-ld/default-context/DENMroadworks'::text)

What could be causing this? From what I noticed the types with slow performance do not seem to always relate to the distribution of the data. Some types with very high load cannot be queried, while others with high load are near instant. This is the same for the ones with low load.

Kind regards,

Mathias van Heule

**Comment by ScorpioBroker** [comment]
Hi Mathias,

we will investigate this. This is indeed odd that postgres makes a completely different execution plan for basically the same query. It's doing an additional sequence scan instead of directly the index scan... weird. I'll investigate.

Thanks

**Comment by mathias-vh** [comment]
Hi ScorpioBroker,

When doing the same query for the affected entity types without the use of distinct, the query is near instant.

Postgres has no loose index scan or skip scan and is forced to scan the entire index to find all unique values and as a table grows, this operation keeps getting slower.

Unless I am missing something I do not see the need for distinct here, since entities are unique , querying types with ngsi-ld/v1/entities?type=<type>&limit=10 could just be done with the query below:

SELECT data_without_sysattrs as data
FROM entity
WHERE ((type = 'https://uri.etsi.org/ngsi-ld/default-context/DENMaccident'))
LIMIT 10

I do not know how easy is this to change this with the use of the quarkus framework.

Br Mathias

**Comment by mathias-vh** [comment]
solved in release 3.0.8
