### ISSUE TITLE
Subscriptions not deleted in a federated setup

### ISSUE THREAD

**Issue by vgonzalez7** [ScorpioBroker/ScorpioBroker#369]
Subscriptions are not correctly deleted in a federated setup. Posting a subscription in the federation broker correctly forwards it
to the context broker, but deleting a subscription in the federation broker doesn't delete it from the context broker. Also it throws
an HTTP 500 error. Steps to reproduce (context broker instance is in port 9090, federation broker instance is in port 9091):

**Step 1: Federate the context broker**

```
curl --location --request POST 'http://x.x.x.x:9091/ngsi-ld/v1/csourceRegistrations' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "urn:ngsi-ld:ContextSourceRegistration:test",
    "type": "ContextSourceRegistration",
    "information": [{
        "entities": [{
            "type": "https://uri.fiware.org/ns/data-models#ParkingSpot"
        }]
    }],
    "endpoint": "http://x.x.x.x:9090"
}'
```

**Step 2: Subscribe to the federation broker**

```
curl --location --request POST 'http://x.x.x.x:9091/ngsi-ld/v1/subscriptions' \
--header 'Content-Type: application/ld+json' \
--data-raw '{
   "id": "urn:Subscription:test",
   "type": "Subscription",
   "entities": [{
        "type": "ParkingSpot"
    }],
    "notification": {
        "endpoint": {
                "uri": "https://webhook.site/958296c2-2c21-44de-9728-bb462afe425c",
                "accept": "application/json"
        }
  },
  "@context": ["https://smartdatamodels.org/context.jsonld"]
}'
```

**Step 2-2: Federation broker proxies subscription to the context broker**

```
{
    "id": "urn:ngsi-ld:Subscription:512836485",
    "type": "Subscription",
    "entities": [
        {
            "type": "https://uri.fiware.org/ns/data-models#ParkingSpot"
        }
    ],
    "isActive": true,
    "notification": {
        "endpoint": {
            "accept": "application/json",
            "uri": "http://x.x.x.x:9091/remotenotify/-8986104680060273025"
        },
        "format": "normalized"
    },
    "status": "active"
}
```

(Notifications are correctly received at the endpoint)

**Step 3: Delete subscription to the federation broker**

`curl --location --request DELETE 'http://x.x.x.x:9091/ngsi-ld/v1/subscriptions/urn%3ASubscription%3Atest'`

**Step 3-2: HTTP 500 Internal Server Error**

```
{
    "type": "https://uri.etsi.org/ngsi-ld/errors/InternalError",
    "title": "Internal error",
    "detail": "I/O error on DELETE request for "/ngsi-ld/v1/subscriptions/urn:ngsi-ld:Subscription: 512836485": null; nested exception is org.apache.http.client.ClientProtocolException"
}
```

**Step 4: Delete subscription to the federation broker (a second time)**

`curl --location --request DELETE 'http://x.x.x.x:9091/ngsi-ld/v1/subscriptions/urn%3ASubscription%3Atest'`

**Step 4-2: HTTP 204 No Content**

"urn:Subscription:test" is deleted but "urn:ngsi-ld:Subscription:512836485" is not, forcing you to delete the proxy subscription manually.

Kind rergards,
Víctor

**Comment by ScorpioBroker** [comment]
Hi Victor,

what a coincidence. I've made yesterday a patch for the spring version which fixes that. spring-kafka-3.0.8. I'm checking the other version this week as well. there should be a 3.0.8 release for all versions soon.

BR

**Comment by vgonzalez7** [comment]
That's good news, thanks!

Best regards,
Víctor
