### ISSUE TITLE
GET /ngsi-ld/v1/temporal/entities?lastN=10

### ISSUE THREAD

**Issue by bcouraud** [ScorpioBroker/ScorpioBroker#371]
Hi,
Would it be possible to get access to the lastN data, but ordered by Date Observed as proposed in NGSI-LD spec ?
Otherwise, what intermediary solution do we have ?
?timerel=between&timeAt=2023-01-10:08:00:00Z&endTimeAt=2023-01-10:13:00:00Z

Many thanks !!

**Comment by amitrnec** [comment]
Hi,

It is already there in NGSI-LD spec and implemented in scorpio broker .

**The lastN parameter refers to a number, n, of Attribute instances which shall correspond to the last n
timestamps (in descending ordering) of the temporal property (by default observedAt) within the concerned 
temporal interval.**

?type=AirQualityObserved&timerel=between&timeAt=2018-08-01:12:00:00Z&endTimeAt=2024-08-01:13:00:00Z&lastN=5

Thanks,
Amit.

**Comment by ScorpioBroker** [comment]
Hi to clarify the issue is not that lastn is not supported but that it is supposed to sort by observedAt which it doesn't at the moment.

**Comment by bcouraud** [comment]
Thanks. Absolutely, the issue is about the sorting by ObservedAt. 
I tried the request "?type=AirQualityObserved&timerel=between&timeAt=2018-08-01:12:00:00Z&endTimeAt=2024-08-01:13:00:00Z&lastN=5", but only get an empty array... 
I thought it could be because "ObservedAt" is not of the right format, but seems to be ok.
Here is an extract of the last data stored:
[
    {
        "id": "urn:ngsi-ld:AirQualityObserved:Nice-FR24035-Lenval",
        "type": "AirQualityObserved",
        "https://smartdatamodels.org/dataModel.Environment/no": {
            "type": "Property",
            "value": 3.7,
            "instanceId": "urn:ngsi-ld:2c959370-bbe5-4938-8c40-a7e85f509141"
        },
        "https://smartdatamodels.org/dataModel.Environment/no2": {
            "type": "Property",
            "value": 33.5,
            "instanceId": "urn:ngsi-ld:6d7bd6ce-1ba5-401b-81ab-540c24bb27eb"
        },
        "https://smartdatamodels.org/dataModel.Environment/nox": {
            "type": "Property",
            "value": 12.9,
            "instanceId": "urn:ngsi-ld:07a4df23-b44c-422c-83e4-36ac6a85533c"
        },
        "https://smartdatamodels.org/dataModel.Environment/pm10": {
            "type": "Property",
            "value": 36.4,
            "instanceId": "urn:ngsi-ld:be193c27-386c-4d4a-9314-e680c889f11f"
        },
        "https://smartdatamodels.org/dataModel.Environment/pm25": {
            "type": "Property",
            "instanceId": "urn:ngsi-ld:d358869a-f888-4f76-b511-53558c8dbc01"
        },
        "https://smartdatamodels.org/dateObserved": {
            "type": "Property",
            "value": {
                "type": "DateTime",
                "@value": "2023-01-05T19:00:00.000Z"
            },
            "instanceId": "urn:ngsi-ld:fac9d370-6270-4557-9cf9-85a1559f2ee0"
        },
        "location": {
            "type": "Property",
            "value": {
                "type": "Point",
                "coordinates": []
            },
            "instanceId": "urn:ngsi-ld:a9a64ab7-966e-4d05-aba2-8f06815aa71b"
        }
    }
]
