### ISSUE TITLE
Getting error while sending PATCH request to update attributes on Scorpio Context Broker with IoT OPC-UA Protocol

### ISSUE THREAD

**Issue by ashok-vimal** [ScorpioBroker/ScorpioBroker#375]
**Curl request:**

```
curl --location --request PATCH 'https://172.30.53.212/scorpio/v1/entities/urn:ngsi-ld:Device:age10_Car/attrs/CarAccelerate' \
--header 'NGSILD-Tenant: opcua_car' \
--header 'NGSILD-Path: /demo' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer 9ac294b1-b69b-3b5d-95f0-bf55c89b98bb' \
--data-raw '{
"type": "Property",
"value": "5"
}'
```

**As we are unable to understand why "Iot" comes with url request. Please find below in Bold for reference** 

**Error while Patch request:**

{
    "type": "https://uri.etsi.org/ngsi-ld/errors/InternalError",
    "title": "Internal error",
    "detail": "404 Not Found: "<!DOCTYPE html><EOL><html lang="en"><EOL><head><EOL><meta charset="utf-8"><EOL><title>Error</title><EOL></head><EOL><body><EOL><pre>Cannot PATCH **/iot/ngsi-ld/v1/entities/urn:ngsi-ld:Device:age10_Car/attrs/CarAccelerate</pre><EOL></body><EOL></html><EOL>""**
}

**Expected Output:**

 "type": "Property",1/24/2023 10:31:52 AM     "value": "5"

**Logs of Pod OPC-UA Iot-Agent:**

2fbcbaad6ad5 | op=IoTAgentNGSI.GenericMiddlewares | from=n/a | srv=n/a | subsrv=n/a | msg=Request for path [/iot/ngsi-ld/v1/entities/urn:ngsi-ld:Device:age10_Car/attrs/CarAccelerate] from [iotagent-opcua:4041] | comp=IoTAgent1/24/2023 10:31:52 AM time=2023-01-24T05:01:52.288Z | lvl=DEBUG | corr=767a75b7-e335-42a9-b018-2fbcbaad6ad5 | trans=767a75b7-e335-42a9-b018-2fbcbaad6ad5 | op=IoTAgentNGSI.GenericMiddlewares | from=n/a | srv=n/a | subsrv=n/a | msg=Body:1/24/2023 10:31:52 AM 1/24/2023 10:31:52 AM {1/24/2023 10:31:52 AM     "type": "Property",1/24/2023 10:31:52 AM     "value": "5"1/24/2023 10:31:52 AM }1/24/2023 10:31:52 AM 1/24/2023 10:31:52 AM  | comp=IoTAgent1/24/2023 10:31:52 AM time=2023-01-24T05:01:52.290Z | lvl=DEBUG | corr=767a75b7-e335-42a9-b018-2fbcbaad6ad5 | trans=767a75b7-e335-42a9-b018-2fbcbaad6ad5 | op=IoTAgentNGSI.DomainControl | from=n/a | srv=n/a | subsrv=n/a | msg=response-time: 5 | comp=IoTAgent1/24/2023 10:31:52 AM time=2023-01-24T05:01:52.502Z | lvl=INFO | corr=8c518ba6-5a38-4c40-8656-44619e0a3523 | trans=8c518ba6-5a38-4c40-8656-44619e0a3523 | op=IoTAgentOPCUA.OPCUABinding | from=n/a | srv=n/a | subsrv=n/a | msg=subscription keepalive | comp=IoTAgent

**Affected Product Version:**

We are using latest image of Scorpio and OPC-UA

**Environment details (with versions):**

OS: Centos 7
Docker Version: 1.19.03
Env -(Rancher Kubernetes Engine): 2.5.9

**Comment by amitrnec** [comment]
Hi,
the endpoints that are using is not correct so kindly use this endpoint.
ex: http://scorpiobrokerIp:9090/ngsi-ld/v1/entities/urn:ngsi-ld:Device:age10_Car/attrs/CarAccelerate

BR,
Amit.
