### ISSUE TITLE
Notifications to unreachable endpoints delay notifications to legit endpoints

### ISSUE THREAD

**Issue by vgonzalez7** [ScorpioBroker/ScorpioBroker#377]
Hello,

I noticed something when subscribing to the same type of entity from several endpoints. I'm using the _scorpiobroker/all-in-one-runner:java-kafka-3.0.9_ version from docker-compose.

Let's say we have three subscriptions to the same type. Endpoints X, Y and Z. Endpoints X and Z are open and reachable, but endpoint Y is not. The behaviour I expect is that the notifications arrive normally to endpoints X and Z, but throw an error for endpoint Y. The second part is correct, after a couple of minutes I receive this on the log:

**2023-02-17 09:04:13,296 ERROR [eu.nec.ngs.com.sub.NotificationHandlerREST] (vert.x-eventloop-thread-0) finally failed to send notification** (this is endpoint Y)

Endpoint X, which subscribed **before** endpoint Y, received the notification in time. However, I noticed that endpoint Z didn't receive the notification in time, but only after endpoint Y failed. So one of the legit endpoints (Z) had to wait for the unreachable one to timeout. This looks like notifications are served in order, and newer ones have to wait for older ones even if they timeout. If I'm not mistaken, this could lead to denial of sevice attacks by simply posting a subscription to all types with an invalid endpoint.

BR,
Víctor

**Comment by ScorpioBroker** [comment]
fixed in 4.0.3
