### ISSUE TITLE
Duplicate NGSILD-Tenant database is being created inside Postgis

### ISSUE THREAD

**Issue by Gaurav-sen1** [ScorpioBroker/ScorpioBroker#378]
Description:
There are two NGSILD-Tenant database being created correspond to IOT-Agent **"Fiware-Service"** .

IOT Agents Used:
1. JSON 
2. OPCUA

It is observed that duplicate NGSILD-Tenant database is created while provisioning a device from the IOT Agent.

**Device Provisioning API :**

curl --location --request POST 'http://<IOT-Agent-API>:4041/iot/devices/' \
--header 'cache-control: no-cache' \
--header 'content-type: application/json' \
--header 'fiware-service: Sensor' \
--header 'fiware-servicepath: /' \
--data-raw '{
    "devices": [
        {
            "device_id":"Sensor_01",
            "entity_name":"urn:ngsi-ld:Sensor:01",
            "entity_type":"Sensor",
            "protocol":"IoTA-JSON",
            "attributes": [
               
                {"object_id":"hasSensingRange", "name":"hasSensingRange", "type":"String"}
            ]
    }
    ]
}'

for the above **"fiware-service: Sensor"**, below NGSILD-Tenant are created

- **ngbsensor**
- **ngbSensor**
 
It creates API communication ambiguity.

Docker Image:
scorpiobroker/scorpio:scorpio-aaio-no-eureka_latest

**Comment by amitrnec** [comment]
Hi Gaurav,
Please share proper description.

Thanks.

**Comment by Gaurav-sen1** [comment]
Hello Amit,

As I have observed that, this is happened only (duplicate database creation ) when Northbound data APIs is invoked.

**North Bound Data API**

curl --location 'http://<IOT-Agent>:7896/iot/json?k=1234&i=Sensor_01' \
--header 'Content-Type: application/json' \
--header 'Fiware-Service: Sensor' \
--header 'Fiware-ServicePath: /' \
--data '{
    "hasSensingRange": "50"
  
}
'
 
Regards
Gaurav Sen

**Comment by amitrnec** [comment]
Hi Gaurav,

Thanks for the information.
This issue is from IoT agent side so please raise the ticket for the same.

BR,
Amit Raghav.
