### ISSUE TITLE
Not able to get  historical entity data

### ISSUE THREAD

**Issue by Neeraj-Nec** [ScorpioBroker/ScorpioBroker#379]
1- Frist i create an entity by using following curl command

 curl --location --request POST '180.179.214.211:9090/ngsi-ld/v1/entityOperations/create' \
--header 'Content-Type: application/json' \
--data-raw '[
  {
    "id": "tenanttest:urn:test:testbatchentity10058",
    "type": "TestType",
    "stringproperty": {"type": "Property", "value": "teststring"},
    "intproperty": {"type": "Property", "value": 123},
    "floatproperty": {"type": "Property", "value": 123.456},
    "complexproperty": {"type": "Property", "value": {"some": {"more": "values"}}},
    "testrelationship": {"type": "Relationship", "object": "urn:testref1"}
  },
  {
    "id": "tenanttest:urn:test:testbatchentity10068",
    "type": "TestType",
    "stringproperty": {"type": "Property", "value": "teststring"},
    "intproperty": {"type": "Property", "value": 123},
    "floatproperty": {"type": "Property", "value": 123.456},
    "complexproperty": {"type": "Property", "value": {"some": {"more": "values"}}},
    "testrelationship": {"type": "Relationship", "object": "urn:testref1"}
  }
]'

2- Get the data using type 

curl --location --request GET '180.179.214.211:9090/ngsi-ld/v1/temporal/entities?type=TestType' \
--header 'Content-Type: application/json'

output : []

**Comment by amitrnec** [comment]
Hi Neeraj,
Now we have fix this issue #380

Thanks.

**Comment by Neeraj-Nec** [comment]
ok Thanks @amitrnec. can I get the updated image from docker ?

**Comment by Neeraj-Nec** [comment]
Thanks @amitrnec
