### ISSUE TITLE
returned attributeNames might be not an array

### ISSUE THREAD

**Issue by zarelit** [ScorpioBroker/ScorpioBroker#381]
If the EntityType has a single attribute, `attributeNames` in the response is not an array.

To reproduce:
* start with an empty instance
* insert the following entity 
```
{
        "id": "smartcity:houses:house3",
        "type": "House",
        "temperature": {
            "type": "Property",
            "value": 22.5,
            "observedAt": "2023-02-13T11:30:40Z"
        },
        "@context": [
            {
                "House": "urn:mytypes:house",
            },
            "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
        ]
    }
```
* Request `GET /ngsi-ld/v1/types?details=true` . The response is:
```
{
    "id": "urn:mytypes:house",
    "type": "EntityType",
    "attributeNames": "temperature",
    "typeName": "urn:mytypes:house"
}
```

Expected response is:
```
{
    "id": "urn:mytypes:house",
    "type": "EntityType",
    "attributeNames": ["temperature"],
    "typeName": "urn:mytypes:house"
}
```

This happens with the docker image `scorpiobroker/scorpio:scorpio-aaio-no-eureka_latest` (repo digest: "scorpiobroker/scorpio@sha256:e4775f70397c871b9ceee4985059b1047e26fc5ad1f1b8baa6f9017fd44df7ea")

**Comment by amitrnec** [comment]
Hi,
This is json-ld core behavior to strip away arrays if it's only one entry so we will look into it later.

Thanks.
