### ISSUE TITLE
Bug with registrations

### ISSUE THREAD

**Issue by pierre-josselin** [ScorpioBroker/ScorpioBroker#382]
I created a registration:

```json
{
    "type": "ContextSourceRegistration",
    "information": [
        {
            "entities": [
                {
                    "type": "City",
                    "id": "urn:ngsi-ld:City:13de6f8c-d61e-4353-a2d3-5544df0b6c6f"
                }
            ],
            "propertyNames": [
                "name"
            ]
        }
    ],
    "mode": "exclusive",
    "operations": [
        "updateOps",
        "retrieveOps"
    ],
    "endpoint": "http://orion-ld:1026"
}
```

Unable to retrieve my entity through registration:

**GET** http://scorpio:9090/ngsi-ld/v1/entities/?id=urn:ngsi-ld:City:13de6f8c-d61e-4353-a2d3-5544df0b6c6f&type=City

```json
[]
```

By intercepting the registration I realize that Scorpio is making an incorrect request to the second context broker:

**GET** http://orion-ld:1026/ngsi-ld/v1/entities/id=urn:ngsi-ld:City:13de6f8c-d61e-4353-a2d3-5544df0b6c6f&type=City

```json
{
    "message": "Entity ID must be urn:XXX:<TYPE>:XXX in order to determine the entity type"
}
```

The character "?" which is used to open the query string seems to be lost at some point.

This is confirmed by adding a proxy between Scorpio and the other context broker which adds this missing character:

~~**GET** http://orion-ld:1026/ngsi-ld/v1/entities/id=urn:ngsi-ld:City:13de6f8c-d61e-4353-a2d3-5544df0b6c6f&type=City~~

**GET** http://orion-ld:1026/ngsi-ld/v1/entities/?id=urn:ngsi-ld:City:13de6f8c-d61e-4353-a2d3-5544df0b6c6f&type=City

```json
{
    "id": "urn:ngsi-ld:City:13de6f8c-d61e-4353-a2d3-5544df0b6c6f",
    "type": "City",
    "name": {
        "type": "Property",
        "value": "Hello world"
    }
}
```

This is probably the problem I encountered in my previous issue #294.

Scorpio image: scorpiobroker/all-in-one-runner:spring-kafka-latest

**Comment by tarmo-profi** [comment]
Hello Pierre,

We are also experiencing this issue so you are not alone with this.
NEC knows this issue so they will provide us a patch soon.

**Comment by ScorpioBroker** [comment]
Hi Pierre, Tarmo

the issue is adressed now in version 3.0.11.
@pierre-josselin 
Just managing some expectations. The mode and the operations entry are currently not properly supported, it is one of the latest changes in the spec and we are currently working on that but it is not in yet.

**Comment by tarmo-profi** [comment]
Hi @ScorpioBroker

It works now when we deleted old CSourceRegistration and posted a new one.

**Comment by pierre-josselin** [comment]
Hi @ScorpioBroker @tarmo-profi

Thank you for your answers and glad to see that the problem is fixed.
