### ISSUE TITLE
MQTT notifications NullPointerException "Cannot invoke "com.google.common.collect.ArrayListMultimap.asMap()" because "headers" is null"

### ISSUE THREAD

**Issue by mathias-vh** [ScorpioBroker/ScorpioBroker#383]
When creating a subscription like the example below:
{
  "description": "Notify me of co2 on AirQualityObserved",
  "type": "Subscription",
  "entities": [{"type": "AirQualityObserved"}],
  "watchedAttributes": ["co2"],
  "notification": {
    "attributes": ["co2"],
    "format": "keyValues",
    "endpoint": {
      "uri": "tcp://mqtt.eclipseprojects.io:1883/airquality",
      "accept": "application/json"
    }
  },
   "@context": "https://smartdatamodels.org/context.jsonld"
}

The following error is occuring:
 2023-03-24 09:16:28,223 ERROR [eu.nec.ngs.com.sub.NotificationHandlerMQTT] (pool-10-thread-5) Exception ::: java.lang.NullPointerException: Cannot invoke "com.google.common.collect.ArrayListMultimap.asMap()" because "headers" is null
mosquitto-scorpio-scorpio3-1   |        at eu.neclab.ngsildbroker.commons.subscriptionbase.NotificationHandlerMQTT.getPayload(NotificationHandlerMQTT.java:68)
mosquitto-scorpio-scorpio3-1   |        at eu.neclab.ngsildbroker.commons.subscriptionbase.NotificationHandlerMQTT.sendReply(NotificationHandlerMQTT.java:47)
mosquitto-scorpio-scorpio3-1   |        at eu.neclab.ngsildbroker.commons.subscriptionbase.BaseNotificationHandler.notify(BaseNotificationHandler.java:72)
mosquitto-scorpio-scorpio3-1   |        at eu.neclab.ngsildbroker.commons.subscriptionbase.BatchNotificationHandler.finalizeBatch(BatchNotificationHandler.java:92)
mosquitto-scorpio-scorpio3-1   |        at eu.neclab.ngsildbroker.commons.subscriptionbase.BatchNotificationHandler.increaseBatch(BatchNotificationHandler.java:56)
mosquitto-scorpio-scorpio3-1   |        at eu.neclab.ngsildbroker.commons.subscriptionbase.BatchNotificationHandler.addDataToBatch(BatchNotificationHandler.java:81)
mosquitto-scorpio-scorpio3-1   |        at eu.neclab.ngsildbroker.commons.subscriptionbase.BaseSubscriptionService.sendNotification(BaseSubscriptionService.java:566)
mosquitto-scorpio-scorpio3-1   |        at eu.neclab.ngsildbroker.commons.subscriptionbase.BaseSubscriptionService.checkSubscriptions(BaseSubscriptionService.java:550)
mosquitto-scorpio-scorpio3-1   |        at eu.neclab.ngsildbroker.commons.subscriptionbase.BaseSubscriptionService.checkSubscriptionsWithAbsolute(BaseSubscriptionService.java:522)
mosquitto-scorpio-scorpio3-1   |        at eu.neclab.ngsildbroker.subscriptionmanager.messaging.SubscriptionMessagingBase.handleBaseRequestEntity(SubscriptionMessagingBase.java:57)
mosquitto-scorpio-scorpio3-1   |        at eu.neclab.ngsildbroker.subscriptionmanager.messaging.SubscriptionMessagingBase$1.run(SubscriptionMessagingBase.java:32)
mosquitto-scorpio-scorpio3-1   |        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
mosquitto-scorpio-scorpio3-1   |        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
mosquitto-scorpio-scorpio3-1   |        at java.base/java.lang.Thread.run(Thread.java:833)

This is a public test MQTT broker service but the same error happens when running a local mosquitto broker.

Any idea what could be causing this?

**Comment by amitrnec** [comment]
Hi,
Please share complete curl with subscription and entity.

Thanks.

**Comment by mathias-vh** [comment]
Hi, this is the complete curl:
curl --location 'http://localhost:9099/ngsi-ld/v1/subscriptions/' \
--header 'Content-Type: application/ld+json' \
--header 'Accept: application/ld+json' \
--data-raw '{
  "description": "Notify me of co2 on AirQualityObserved",
  "type": "Subscription",
  "entities": [{"type": "AirQualityObserved"}],
  "watchedAttributes": ["co2"],
  "notification": {
    "attributes": ["co2"],
    "format": "keyValues",
    "endpoint": {
      "uri": "tcp://mqtt.eclipseprojects.io:1883/airquality",
      "accept": "application/json"
    }
  },
   "@context": "https://smartdatamodels.org/context.jsonld"
}'

**Comment by amitrnec** [comment]
Hi,
Thanks for the sharing curl but i am not able to reproduce this error so can you share complete steps when you are getting this error.

Thanks.

**Comment by mathias-vh** [comment]
Hi,
running scorpiobroker/all-in-one-runner:java-kafka-3.0.9 locally.
Running mosquitto as MQTT locally using image: eclipse-mosquitto:2

Create a subscription with the CURL below:
curl --location 'http://localhost:9099/ngsi-ld/v1/subscriptions/'
--header 'Content-Type: application/ld+json'
--header 'Accept: application/ld+json'
--data-raw '{
"description": "Notify me of co2 on AirQualityObserved",
"type": "Subscription",
"entities": [{"type": "AirQualityObserved"}],
"watchedAttributes": ["co2"],
"notification": {
"attributes": ["co2"],
"format": "keyValues",
"endpoint": {
"uri": "tcp://mqtt.eclipseprojects.io:1883/airquality",
"accept": "application/json"
}
},
"@context": "https://smartdatamodels.org/context.jsonld"
}'

Create an entity using the entityOperations/upsert/ endpoint with the CURL below, for example:
curl --location 'http://localhost:9099/ngsi-ld/v1/entityOperations/upsert/' \
--header 'Content-Type: application/ld+json' \
--header 'Accept: application/ld+json' \
--data-raw '[{
	"id": "urn:ngsi-ld:AirQualityObserved:id:QZBB:17467438",
	"dateCreated": {
		"type": "Property",
		"value": {
			"@type": "DateTime",
			"@value": "2022-04-04T12:00:00Z"
		}
	},
	"dateModified": {
		"type": "Property",
		"value": {
			"@type": "DateTime",
			"@value": "2022-04-04T12:00:00Z"
		}
	},
	"location": {
		"type": "Property",
		"value": {
			"type": "Point",
			"coordinates": [
				50.994891405280434, 3.6321380336795333
			]
		}
	},
	"type": "AirQualityObserved",
	"dateObserved": {
		"type": "Property",
		"value": {
			"@type": "DateTime",
			"@value": "2022-04-04T08:00:00Z"
		}
	},
	"airQualityIndex": {
		"type": "Property",
		"value": 53
	},
	"reliability": {
		"type": "Property",
		"value": 0.7
	},
	"as": {
		"type": "Property",
		"value": 681.4
	},
	"c6h6": {
		"type": "Property",
		"value": 627.7
	},
	"cd": {
		"type": "Property",
		"value": 737.3
	},
	"co": {
		"type": "Property",
		"value": 1020.2
	},
	"co2": {
		"type": "Property",
		"value": 1030.1
	},
	"ni": {
		"type": "Property",
		"value": 256.1
	},
	"no": {
		"type": "Property",
		"value": 845.0
	},
	"no2": {
		"type": "Property",
		"value": 97.6
	},
	"nox": {
		"type": "Property",
		"value": 21.2
	},
	"o3": {
		"type": "Property",
		"value": 322.2
	},
	"pm10": {
		"type": "Property",
		"value": 765.6
	},
	"pm25": {
		"type": "Property",
		"value": 25.1
	},
	"pb": {
		"type": "Property",
		"value": 868.2
	},
	"precipitation": {
		"type": "Property",
		"value": 72.5
	},
	"relativeHumidity": {
		"type": "Property",
		"value": 0.8
	},
	"sh2": {
		"type": "Property",
		"value": 843.4
	},
	"so2": {
		"type": "Property",
		"value": 967.5
	},
	"typeofLocation": {
		"type": "Property",
		"value": "outdoor"
	},
	"volatileOrganicCompoundsTotal": {
		"type": "Property",
		"value": 930.4
	},
	"temperature": {
		"type": "Property",
		"value": 20
	},
	"windDirection": {
		"type": "Property",
		"value": 54.8
	},
	"windSpeed": {
		"type": "Property",
		"value": 167.7
	},
	"@context": [
		"https://smartdatamodels.org/context.jsonld"
	]
}]'

**Comment by mathias-vh** [comment]
can confirm that this issue is limited to using a MQTT broker, using a webhook uri works.
example:
{
  "description": "Notify me of co2 on AirQualityObserved",
  "type": "Subscription",
  "entities": [{"type": "AirQualityObserved"}],
  "notification": {
    "endpoint": {
      "uri": "https://webhook.site/b96a4108-3403-4525-9b43-7c60d7489ffb",
      "accept": "application/json"
    }
  },
   "@context": "https://smartdatamodels.org/context.jsonld"
}

**Comment by amitrnec** [comment]
Hi,
we have fixed this issue #384 and soon will be merge in quarkus dev branch.

Thanks.

**Comment by mathias-vh** [comment]
Hi,
I have build a docker container including this fix and can confirm this fix works,
