### ISSUE TITLE
Question: Adding TimescaleDB to store temporal data

### ISSUE THREAD

**Issue by yshashix** [ScorpioBroker/ScorpioBroker#386]
Hi Team,

I would like to store temporal data in the timescaledb indexed with observedAt timestamp parameter. I have a few questions

1. Will it work with AIO setup as well? Because jdbc connecting database will be different for temporal and non-temporal.( I have planned to add separate "live" entities in the tsdb timescaledb ). I guess for separate modular application compilation it won't be a problem as application.properties are different for different applications [https://github.com/ScorpioBroker/ScorpioBroker/blob/9f27e2bcbb49b9d207d1a0380540e3afd095d03c/HistoryManager/src/main/resources/application.properties#L17](url)
2.  Apart from above, i probably need to do some changes in /commons/storage right?[https://github.com/ScorpioBroker/ScorpioBroker/tree/quarkus-release/3.0.11/Commons/src/main/java/eu/neclab/ngsildbroker/commons/storage](url)

**Comment by ScorpioBroker** [comment]
Hi,
i theory yes it should be possible to just switch the database to timescale DB (we are also testing this at the moment). It is postgres after all. We also use PostGIS but that is included in the -ha containers from timescale so should be fine ... 
If you want to create a hyper_table it would be the temporalentityattrinstance table and than it depends a bit .... default operations go to observedAt however this is not mandatory by ngsi-ld so the field can be null at the moment ... which is an issue for the hyper table. modifiedAt is always present but you have to adjust the temporary queries and add timeproperty=modifiedAt 

There should be no code/sql changes needed to our understanding to get the improvements from the hyper table... but as said we are still looking into it so we can't really say something definitive at the moment.

**Comment by yshashix** [comment]
@ScorpioBroker Thanks for information
