### ISSUE TITLE
Failed startup when building AAIO container

### ISSUE THREAD

**Issue by anyname2** [ScorpioBroker/ScorpioBroker#39]
Commit 4d7524b5286da25f79e6df7d27d6e581c931f0fa have broken AAIO container, it now fails to start. The issue is in AllInOneRunner/src/main/resources/application.yml.

Host names for Kafka and PostgreSQL were changed to localhost, which refers to the container itself when executing in docker. This is wrong, since Kafka and PostgreSQL are running in separate containers.

**Comment by ScorpioBroker** [comment]
Hi, fixed it. 
Sorry bad commit

**Comment by anyname2** [comment]
The commit only fixed references to kafka, not Postgre.

**Comment by ScorpioBroker** [comment]
yes sorry fixed that one
