### ISSUE TITLE
"invalid @id value: value of @id must be a string" on subscription update (PATCH /subscriptions/{subscriptionId})

### ISSUE THREAD

**Issue by MS-Fiware** [ScorpioBroker/ScorpioBroker#4]
Hi,

when trying to patch a subscription with PATCH /subscriptions/{subscriptionId} I get a "500 Internal Server Error" in the HTTP response.

My request:

`curl -X PATCH \
  http://192.168.57.101:9090/ngsi-ld/v1/subscriptions/urn:ngsi-ld:Subscription:838170928 \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "notification": {
        "attributes": [
            "id",
            "type",
            "airQualityLevel",
            "dateObserved"
        ],
        "endpoint": {
            "accept": "application/ld+json",
            "uri": "http://localhost:8080/subscription/air-quality-level-change"
        },
        "format": "keyValues"
    },
    "@context": [
        "https://schema.lab.fiware.org/ld/context",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}'`

The response body:

`{
    "timestamp": "2019-10-01T09:45:51.344+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "invalid @id value: value of @id must be a string",
    "path": "/urn:ngsi-ld:Subscription:838170928"
}`

I tested with the latest commit https://github.com/ScorpioBroker/ScorpioBroker/commit/fb4a758068878e29998d31037da54133f374f2a6.

Greetings,
Michael

**Comment by ScorpioBroker** [comment]
Hi,

should be fixed now. Was a problem with expanding the attribute values in the json.

Regards
Benjamin

**Comment by MS-Fiware** [comment]
Thanks, seems also to be good right now. :)
