### ISSUE TITLE
non-dockerized startup of broker components not possible

### ISSUE THREAD

**Issue by MS-Fiware** [ScorpioBroker/ScorpioBroker#40]
Hi,

I just tried to start each broker component the old fashion way separately on the command line. It seems not to be supported anymore.

At least I get a 
`no main manifest attribute, in <PATH>/<FILE>.jar` 
when running a `java -jar <PATH>/<FILE>.jar`.

Did you remove some needed manifest files?

Best regards,
Michael

**Comment by ScorpioBroker** [comment]
Hi,
no didn't change anything there. Just tried it with the QueryManager and it worked. 
I added a new var (-DskipDefault) for the building of the aio container which doesn't repackage the individual microservices but only the final runner.jar. This was needed to avoid having multiple 60MB jars inside of the jar. But if you just run it with clean package -DskipTests it should just work normal. Unfortunately i haven't found a way to have both things in one maven build. At the moment it's either building the indivual microservices or the all in one runner or you can have both (run aaio-docker without skipDefault) but than the runner jar will be like 500MB

**Comment by MS-Fiware** [comment]
I used the -DskipDefault option, which might have been the reason for failing. 
Good to read you're updating the README at this moment. ;)

Best regards,
Michael
