### ISSUE TITLE
Upgrade Scorpio 4.0.2 from 3.11. is stuck

### ISSUE THREAD

**Issue by tarmo-profi** [ScorpioBroker/ScorpioBroker#401]
Hello,

We have ran Scorpio 3 for few months and now we decided to upgrade it to version 4.
It seems that migration processes are stuck:

```
2023-06-26 11:06:14,296 DEBUG [org.fly.cor.int.sql.DefaultSqlScriptExecutor] (main) Executing SQL: CREATE INDEX i_temporalentityattrinstance_attribname
    ON public.temporalentityattrinstance USING hash
    (attributeid text_ops)
```

We use mostly temporal entities so I think this migration seems to be lengthy process and it's been executing that SQL query for hours - but Scorpio isn't actually making any requests into timescaleDB.

Any ideas to fix this issue? Should we wait it to be finished?

**Comment by ScorpioBroker** [comment]
Hi,

this can take quite some time. Scorpio itself isn't doing anything here except for sending the sql command over. the reindexing is running in the db. i'll setup a controlled env to have better metric than quite some time.

**Comment by tarmo-profi** [comment]
Issue fixed by doing migrations manually.
