### ISSUE TITLE
update docker image

### ISSUE THREAD

**Issue by djs0109** [ScorpioBroker/ScorpioBroker#418]
Hello, I see that in the release note it says "Scorpio will be release as an docker image on dockerhub".

However, when I check dockerhub [here](https://hub.docker.com/r/scorpiobroker/scorpio/tags), the latest release was made last year, and the tags seem to be far behind the release of this repo. Am I looking in the wrong place?

Since we are currently using Scorpio mainly based on the docker image, it will be of great interest to know, how is the standard workflow on this and what is the update frequency of the docker image.

If the docker image will not be updated constantly, what will be the suggestion to keep our deployment up to date? Should we always build the image locally?

**Comment by ScorpioBroker** [comment]
Hi,

please have a look here https://hub.docker.com/r/scorpiobroker/all-in-one-runner we changed our repo structure some time ago and release on scorpiobroker/microservice-name or scorpiobroker/all-in-one-runner.
We tag the images like this <OSName for native build/Java for java build>-kafka-<version/latest>
so e.g. 
scorpiobroker/all-in-one-runner:java-kafka-4.1.1 / scorpiobroker/all-in-one-runner:java-kafka-latest
or 
scorpiobroker/all-in-one-runner:ubuntu-kafka-4.1.1

We don't have a set release interval. It is depended on the issue reports and updates on the ngsi-ld spec.

**Comment by djs0109** [comment]
That is what I am looking for, thank you!
