### ISSUE TITLE
Incorrect compaction of `name` attribute when using FQNs.

### ISSUE THREAD

**Issue by jason-fox** [ScorpioBroker/ScorpioBroker#419]
Scorpio 4.0.9.  I create an Entity using the following `@context`:  https://github.com/FIWARE/tutorials.Getting-Started/blob/NGSI-LD/data-models/ngsi-context.jsonld

```console
curl -L 'http://localhost:9090/ngsi-ld/v1/entities/' \
-H 'Content-Type: application/ld+json' \
--data-raw '{
    "id": "urn:ngsi-ld:Building:farm001",
    "type": "Building",
    "category": {
    	"type": "Property",
        "value": ["farm"]
    },
    "address": {
        "type": "Property",
        "value": {
            "streetAddress": "Großer Stern 1",
            "addressRegion": "Berlin",
            "addressLocality": "Tiergarten",
            "postalCode": "10557"
        },
        "verified": {
			"type": "Property",
			"value": true
		}
    },
    "location": {
        "type": "GeoProperty",
        "value": {
             "type": "Point",
             "coordinates": [13.3505, 52.5144]
        }
    },
    "name": {
        "type": "Property",
        "value": "Victory Farm"
    },
    "@context": "http://context/ngsi-context.jsonld"
}'
```

I then Get the type without an `@context` as shown:

```console
curl -L 'http://localhost:9090/ngsi-ld/v1/entities?type=https%3A%2F%2Furi.fiware.org%2Fns%2FdataModels%23Building' \
-H 'Accept: application/ld+json' 
```

The response is as shown:

```json
[
    {
        "id": "urn:ngsi-ld:Building:farm001",
        "type": "https://uri.fiware.org/ns/dataModels#Building",
        "https://schema.org/address": {
            "type": "Property",
            "value": {
                "addressLocality": "Tiergarten",
                "addressRegion": "Berlin",
                "postalCode": "10557",
                "streetAddress": "Großer Stern 1"
            },
            "https://uri.fiware.org/ns/dataModels#verified": {
                "type": "Property",
                "value": true
            }
        },
        "location": {
            "type": "GeoProperty",
            "value": {
                "type": "Point",
                "coordinates": [
                    13.3505,
                    52.5144
                ]
            }
        },
        "ngsi-ld:name": {
            "type": "Property",
            "value": "Victory Farm"
        },
        "https://uri.fiware.org/ns/dataModels#category": {
            "type": "Property",
            "value": "farm"
        },
        "@context": [
            "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.6.jsonld"
        ]
    }
]
```

Since `name`  (like `location`) is already defined in `ngsi-ld-core-context-v1.6.jsonld` it should just appear with `name`

**Comment by ScorpioBroker** [comment]
Hi,

name is not defined in the 1.6 context. I think it was removed intentionally.
name is only defined in your creating context.

https://tinyurl.com/4w6wcbks on the playground it behaves the same.

BR

**Comment by jason-fox** [comment]
Hmmm,

There is an inconsistency between the following core contexts:

- https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld. = contains `"name"`
- https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.6.jsonld = no `"name"`
- https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.7.jsonld = no `"name"`

**Comment by ScorpioBroker** [comment]
From my understanding ... 
the first one is for 1.2.1 and you can't really use that one anymore. at least with scorpio since the 1.3.1 had some breaking changes with the location entry... however if you provide this one scorpio will just replace it with the 1.6 context to have some backwards compatibility. 

I think name was basically removed at some point in the spec, it was in the subscription i think. Because name was such a common thing to be used in other data models that it was a real pain that it was in the core context.

**Comment by jason-fox** [comment]
Closing -  this is an ETSI issue not a Scorpio issue.
