### ISSUE TITLE
Federation setup doesn't work

### ISSUE THREAD

**Issue by lauramartingonzalezzz** [ScorpioBroker/ScorpioBroker#421]
Hello,

the federation setup doesn't work properly. Below I describe the steps to reproduce the error, but basically the Federator Context Broker returns empty when asked for entities of some type.

**Step 1.** The current setup is as follows:
- Satellite CB is deployed on `http://satellite_ip:satellite_port`
- Federator CB is deployed on `http://federator_ip:federator_port`
- Both Scorpio Brokers are using the image `scorpiobroker/all-in-one-runner:java-kafka-latest`. Currently 4.1.1.

**Step 2.** Register the satellite broker into the federator broker.
```
POST http://federator_ip:federator_port/ngsi-ld/v1/csourceRegistrations
Content-Type: application/ld+json
Body:
{
    "id": "urn:ngsi-ld:ContextSourceRegistration:test",
    "type": "ContextSourceRegistration",
    "information": [
        {
            "entities": [
                {
                    "type": "AirQualityObserved"
                }
            ]
        }
    ],
    "endpoint": "http://satellite_ip:satellite_port",
    "@context": [
        "https://raw.githubusercontent.com/smart-data-models/dataModel.Environment/master/context.jsonld"
    ]
}
```
**Step 3.** Query the AirQualityObserved entities in both Context Brokers.

Satellite Request:
```
GET http://satellite_ip:satellite_port/ngsi-ld/v1/entities/?type=AirQualityObserved
Link: <https://raw.githubusercontent.com/smart-data-models/dataModel.Environment/master/context.jsonld>;rel="http://www.w3.org/ns/json-ld#context";type="application/ld+json"
Accept: application/ld+json
```

Satellite Response:
```
200 OK
[
    {
        "id": "urn:ngsi-ld:AirQualityObserved:test1",
        "type": "AirQualityObserved",
        "co": {
            "type": "Property",
            "value": 0.2,
            "observedAt": "2023-07-30T04:25:00Z",
            "unitCode": "GP"
        },
        "dateObserved": {
            "type": "Property",
            "value": "2023-07-30T04:25:00Z"
        },
        "@context": [
            "https://raw.githubusercontent.com/smart-data-models/dataModel.Environment/master/context.jsonld",
            "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.6.jsonld"
        ]
    },
    {
        "id": "urn:ngsi-ld:AirQualityObserved:test2",
        "type": "AirQualityObserved",
        "co": {
            "type": "Property",
            "value": 0.1,
            "observedAt": "2023-07-30T17:53:00Z",
            "unitCode": "GP"
        },
        "dateObserved": {
            "type": "Property",
            "value": "2023-07-30T17:53:00Z"
        },
        "@context": [
            "https://raw.githubusercontent.com/smart-data-models/dataModel.Environment/master/context.jsonld",
            "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.6.jsonld"
        ]
    }
]
```

Federator Request:
```
GET http://federator_ip:federator_port/ngsi-ld/v1/entities/?type=AirQualityObserved
Link: <https://raw.githubusercontent.com/smart-data-models/dataModel.Environment/master/context.jsonld>;rel="http://www.w3.org/ns/json-ld#context";type="application/ld+json"
Accept: application/ld+json
```

Federator Response:
```
200 OK
[]
```
Thanks

**Comment by martin-p-bauer** [comment]
Hello Laura,

I could reproduce the problem. We will work on fixing it as soon as possible, but it may take a couple of days as our main developer is not available.

Best regards,
Martin

**Comment by tarmo-profi** [comment]
Following this because this problem is also occurring in our systems.

**Comment by amitrnec** [comment]
Hi,
Currently working on this issue and will fix asap.

Thanks.

**Comment by amitrnec** [comment]
Hi,
Issue has been fixed and code merged in development-quarkus branch.

Thanks.

**Comment by tarmo-profi** [comment]
@amitrnec we need new image into dockerhub.

**Comment by amitrnec** [comment]
Hi,
Please check new release.

Thanks..

**Comment by tarmo-profi** [comment]
Java-Kafka version is missing @amitrnec

**Comment by amitrnec** [comment]
Yes . Thanks for the information. we will update java kafka version image as well.
For the time being you can use java-latest version.

Thanks.

**Comment by amitrnec** [comment]
Now you can test with Java-Kafka version as well.

Thanks.

**Comment by vgonzalez7** [comment]
The issue still persists in our system after updating both brokers to 4.1.2 though docker compose (`scorpiobroker/all-in-one-runner:java-kafka-latest`).

Thanks

**Comment by amitrnec** [comment]
Hi,
You are creating the entities with @context but context is missing in csource registration payload so please add @context as below. 
 "contextSourceInfo":[
        {
            "key": "jsonldContext",
            "value": "https://raw.githubusercontent.com/smart-data-models/dataModel.Environment/master/context.jsonld"
        }
    ]

Thanks.

**Comment by martin-p-bauer** [comment]
In the general case, it is not required to provide an @context in the contextSourceInfo of a ContextSourceRegistration.

It is actually a new optional feature to provide a specific @context as part of the registration. The idea is to support restricted Context Sources that cannot properly handle the @context themselves.

**Comment by amitrnec** [comment]
Fixed this issue #426 and will be release soon.

**Comment by tarmo-profi** [comment]
@amitrnec

When this release will provide the images into Dockerhub?

**Comment by ScorpioBroker** [comment]
Hi Tarmo,

i think i'll make a release this weekend. I'm currently also working on the temporal sql part to have both parts fixed up in the next release.

**Comment by tarmo-profi** [comment]
Requesting csourceRegistrations from http://localhost:9090/ngsi-ld/v1/csourceRegistrations/ produces an 400 error:
```
curl --location 'http://localhost:9090/ngslocalhost:9090/ngsi-ld/v1/csourceRegistrations/
{"type":"https://uri.etsi.org/ngsi-ld/errors/InvalidRequest","title":"Invalid request.","detail":{"message":"Invalid request."},"errorCode":400}
```

**Comment by ScorpioBroker** [comment]
Hi,

yes this is spec behaviour. In the spec it says "At least one among: type, attrs, q, or georel shall be present."
I think it is basically a copy from the normal query interface which doesn't allow this (for a good reason).. however in csource it might be a bit to much. let me check if it's possible for ngsi-ld to change this a bit.

**Comment by tarmo-profi** [comment]
Okay folks, I got the federation (csourceRegistration) work. Thanks for helping us!

**Comment by lauramartingonzalezzz** [comment]
We also got it working, thank you so much!
