### ISSUE TITLE
Request  is forwarded to incorrect endpoint, headers cannot be processed.

### ISSUE THREAD

**Issue by jason-fox** [ScorpioBroker/ScorpioBroker#423]
Scorpio 4.1.1. - Possibly related to #421  ?

### Path gaining extra `/`s

If I register a context provider as shown:

```console
curl -L 'http://localhost:9090/ngsi-ld/v1/csourceRegistrations/' \
-H 'Content-Type: application/json' \
-H 'Link: <http://context/ngsi-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
-d ' {
    "type": "ContextSourceRegistration",
    "information": [
        {
            "entities": [
                
                 {
                    "type": "Shelf"
                }
            ]
        }
    ],
     "contextSourceInfo":[
        {
            "key": "jsonldContext",
            "value": "https://fiware.github.io/tutorials.Step-by-Step/tutorials-context.jsonld"
        }
    ],
    "mode": "inclusive",
    "operations": [
        "federationOps"
    ],
    "endpoint": "http://adapter:3000"
}'
```

and then make a request to Scorpio using `http://localhost:9090/ngsi-ld/v1/entities/?type=Shelf`, the registrant is receiving the forwarded request on **GET** `//ngsi-ld/v1/entities?type=Shelf&limit=1000` - this is incorrect as the request has an extra `/` in the path.

Note that if I had set the endpoint to  `"http://adapter:3000/"` it would be even worse as it makes a request to   **GET** `///ngsi-ld/v1/entities?type=Shelf&limit=1000`  with a tripled slash `/` - this should also be reduced.

> **Note:** - if the registrant does not service `//ngsi-ld/v1/entities` or `///ngsi-ld/v1/entities` it will most likely return a 404 
> or an empty array which is similar to the issue described in #421 

### Header handling

When I  query the registrant directly I receive back a number of shelf entities, and it responds with a number of headers.

```console
curl -iX GET 'http://localhost:3005/ngsi-ld/v1/entities/?type=Shelf&limit=1000' \
-H 'Link: <http://context/ngsi-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"'
```

```text
Surrogate-Control: no-store
Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate
Expires: 0
Content-Type: application/json; charset=utf-8
Link: <https://fiware.github.io/tutorials.Step-by-Step/tutorials-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"
Content-Length: 3090
Date: Tue, 01 Aug 2023 06:39:25 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

Making the same request on Scorpio, results in the following error:

```console
curl -L 'http://localhost:9090/ngsi-ld/v1/entities/?type=Shelf&limit=1000' \
-H 'Link: <http://context/ngsi-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"
```

```json
{
    "type": "https://uri.etsi.org/ngsi-ld/errors/InternalError",
    "title": "Internal error",
    "detail": {
        "message": "a header name cannot contain some prohibited characters, such as : https://uri.etsi.org/ngsi-ld/hasValue"
    },
    "errorCode": 500
}
```

It is unclear which header is being complained about.

The same error occurs when querying a single entity on Scorpio - e.g. `urn:ngsi-ld:Shelf:unit001?type=Shelf`

```console
curl -L 'http://localhost:9090/ngsi-ld/v1/entities/?urn:ngsi-ld:Shelf:unit001?type=Shelf' \
-H 'Link: <http://context/ngsi-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"
```

returns:

```json
{
    "type": "https://uri.etsi.org/ngsi-ld/errors/InternalError",
    "title": "Internal error",
    "detail": {
        "message": "a header name cannot contain some prohibited characters, such as : https://uri.etsi.org/ngsi-ld/hasValue"
    },
    "errorCode": 500
}
```

**Comment by martin-p-bauer** [comment]
Regarding "Header handling" - is it possible that for the Link header in the request the single quote (') is missing at the end? Maybe then the header is parsed incorrectly?

**Comment by jason-fox** [comment]
The **Link** header (when present) is always returned as a static string like:

```text
Link: <https://fiware.github.io/tutorials.Step-by-Step/tutorials-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"
```

The only part that is configurable is which `@context` URL to pass.

**Comment by jason-fox** [comment]
@amitrnec  - you can use the `docker-compose` found [here](https://github.com/jason-fox/lepus) to spin up an NGSI-v2 Orion with a federationsOps wrapper for testing.
