### ISSUE TITLE
Examples provided in documentation do not work as described

### ISSUE THREAD

**Issue by Marcel5751** [ScorpioBroker/ScorpioBroker#432]
While trying out the Scorpio Broker for potential usage in a research project, I noticed that several examples from the official documentation do not work in as described practice.

One example is from the [API walkthrough](https://scorpio.readthedocs.io/en/latest/API_walkthrough.html#limit-the-attributes) section of the documentation. After creating the entities as per documentation, I ran the following curl command copied from the docs:

```shell
curl localhost:9090/ngsi-ld/v1/entities/?type=Room&q=isPartOf==%22smartcity%3Ahouses%3Ahouse2%22\&attrs=temperature -s -S -H 'Accept: application/json' -H 'Link: <https://pastebin.com/raw/Mgxv2ykn>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"'
```

This request results in an Internal Server error.

```json
{
  "type": "https://uri.etsi.org/ngsi-ld/errors/InternalError",
  "title": "Internal error",
  "detail": {
    "message": "ERROR: invalid input syntax for type json (22P02)"
  },
  "errorCode": 500
}
```

The request works as expected when omitting the `attrs=temperature` query parameter.

Regarding the temporal Interface, the  provided [aggregation functions](https://scorpio.readthedocs.io/en/latest/aggregation-support.html) example also did not work as expected.

First of all, the request fails with an `Invalid operator in q query` error because of a typo in the query. It should be `q=brandName==Mercedes` instead of `q=brandName=Mercedes`.

```shell
curl -X GET --location "http://localhost:9090/ngsi-ld/v1/temporal/entities/?type=Vehicle&q=brandName%3D%3DMercedes&attrs=speed&timerel=between&timeAt=2020-08-01T12%3A00%3A00Z&endTimeAt=2020-08-01T13%3A00%3A00Z&aggrMethods=max%2Cavg&aggrPeriodDuration=PT4M&options=aggregatedValues" \
    -H "Link: <https://pastebin.com/raw/Mgxv2ykn>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"" \
    -H "Accept: application/json"
```

After correcting this error, the request returns an empty array.
When removing the query parameter `q=brandName==Mercedes` the interface returns the expected output. The request also works as expected when omitting the time filter (.i.e. `ngsi-ld/v1/temporal/entities/?type=Vehicle&q=brandName==Mercedes&attrs=speed`) So it seems that only the combination of the query and temporal parameters is not evaluated correctly.

Tested with the [docker compose file](https://github.com/ScorpioBroker/ScorpioBroker/blob/development-quarkus/compose-files/docker-compose-java-aaio-kafka.yml) from Scorpio repository. Scorpio version at time of testing is `java-kafka-4.1.3`.

**Comment by ScorpioBroker** [comment]
Hi,

yes this is indeed an error it's a bit weird because attrs and q individual work as expected. 
Investigating...
@amitrnec 
Please check this documentation part when we update it.

@Marcel5751 
About the aggr functions we have overhauled them to be more consistent that is why the old doc is not correct anymore.
Basically the timeproperty in the temporal query declares which timeproperty to be used also in the aggr functions. By default it is observedAt which is not present in e.g. brandName so it will not be added to the result. Just set timeproperty=modifiedAt and it should be as expected

**Comment by ScorpioBroker** [comment]
@Marcel5751 
One more thing if you are looking for a collection of the operations please download the api-test.json from the root that is a postman collection

**Comment by Marcel5751** [comment]
Thanks for the quick response and explanations! The hint at the postman collection is quite useful.

Indeed, setting `timeproperty=modifiedAt` allows the filter by "brandName" to work. Since the timeframe specified in the example refers to the `observedAt` timestamps of the "speed" property, we still get back an empty array, which makes sense because the `modifiedAt` timestamps of the "speed" property is set to the moment the POST request was issued.

I suppose it is not possible to consider the timeproperty `modifiedAt` to filter the brandName and at the same time consider the timeproperty `observedAt` to filter the speed? In other words, the query and temporal filers both use the same `timeproperty` (This behavior is also in line with the NGSI-LD standard if I am not mistaken).
