### ISSUE TITLE
PSQLException: ERROR: index row size 2928 exceeds maximum 2712 for index "subscriptions_subscription_request_key "

### ISSUE THREAD

**Issue by Dhawalkachi** [ScorpioBroker/ScorpioBroker#439]
Dear team, 
When we are trying to create a new subscription using API, we are getting below given issue when in subscription table (columns: subscription_id and subscription_request) request field exceeds text limit of 2712 characters due to the constraint ["subscriptions_subscription_request_key" UNIQUE, btree (subscription_request)]. We manually changed it to "subscriptions_subscription_request_key" UNIQUE, btree (md5(subscription_request)) and it started working fine. 
But as new schema is created by scorpio broker everytime a new tenant is created, this has to be done at scorpio broker side.

Following is the response that might help us:
** Response: 
{
    "type": "[https://uri.etsi.org/ngsi-ld/errors/InternalError"](https://uri.etsi.org/ngsi-ld/errors/InternalError%22),
    "title": "Internal error",
    "detail": "PreparedStatementCallback; SQL [INSERT INTO subscriptions (subscription_id, subscription_request) VALUES (?, ?) ON CONFLICT(subscription_id) DO UPDATE SET subscription_request = EXCLUDED.subscription_request]; ERROR: index row size 2928 exceeds maximum 2712 for index "subscriptions_subscription_request_key "
  Hint: Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.; nested exception is org.postgresql.util.PSQLException: ERROR: index row size 2928 exceeds maximum 2712 for index "subscriptions_subscription_request_key "
  Hint: Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing."
}**

Regards,
Dhawal Kachiwala

**Comment by amitrnec** [comment]
Hi,
I think you are using old version of scorpio broker so now you can use new version.
https://hub.docker.com/layers/scorpiobroker/all-in-one-runner/java-kafka-4.1.3/images/sha256-5fe4087cd0d511e73eea93a6e603ff07e974e23c7c04b377648d7b401f60bc0f?context=explore

Please let me know if you are getting the same issue.

BR,
Amit Raghav

**Comment by ScorpioBroker** [comment]
Just to confirm in the current version this index is not present and tbh. i searched for the index in the migration files this is not from us i think 
current indexes are 
 public   | I_entity_scopes                                              | index | ngb   | entity
 public   | I_entity_types                                               | index | ngb   | entity
 public   | I_temporalentity_types                                       | index | ngb   | temporalentity
 public   | contexts_pkey                                                | index | ngb   | contexts
 public   | csource_pkey                                                 | index | ngb   | csource
 public   | entity_pkey                                                  | index | ngb   | entity
 public   | entitymap_management_pkey                                    | index | ngb   | entitymap_management
 public   | fki_cs_id_fkey                                               | index | ngb   | csourceinformation
 public   | flyway_schema_history_pk                                     | index | ngb   | flyway_schema_history
 public   | flyway_schema_history_s_idx                                  | index | ngb   | flyway_schema_history
 public   | i_csource_c_id                                               | index | ngb   | csource
 public   | i_csource_data                                               | index | ngb   | csource
 public   | i_csource_id                                                 | index | ngb   | csource
 public   | i_csourceinformation_e_id                                    | index | ngb   | csourceinformation
 public   | i_csourceinformation_e_prop                                  | index | ngb   | csourceinformation
 public   | i_csourceinformation_e_rel                                   | index | ngb   | csourceinformation
 public   | i_csourceinformation_e_type                                  | index | ngb   | csourceinformation
 public   | i_csourceinformation_i_location                              | index | ngb   | csourceinformation
 public   | i_entity_createdat                                           | index | ngb   | entity
 public   | i_entity_data                                                | index | ngb   | entity
 public   | i_entity_location                                            | index | ngb   | entity
 public   | i_entity_modifiedat                                          | index | ngb   | entity
 public   | i_entitymap_qtoken                                           | index | ngb   | entitymap
 public   | i_temporalentity_location                                    | index | ngb   | temporalentityattrinstance
 public   | i_temporalentityattrinstance_attribname                      | index | ngb   | temporalentityattrinstance
 public   | i_temporalentityattrinstance_data                            | index | ngb   | temporalentityattrinstance
 public   | i_temporalentityattrinstance_entityid                        | index | ngb   | temporalentityattrinstance
 public   | i_temporalentityattrinstance_entityid_attributeid_instanceid | index | ngb   | temporalentityattrinstance
 public   | i_temporalentityattrinstance_location                        | index | ngb   | temporalentityattrinstance
 public   | id_pkey                                                      | index | ngb   | csourceinformation
 public   | registry_subscriptions_pkey                                  | index | ngb   | registry_subscriptions
 public   | spatial_ref_sys_pkey                                         | index | ngb   | spatial_ref_sys
 public   | subscriptions_pkey                                           | index | ngb   | subscriptions
 public   | temporalentity_pkey                                          | index | ngb   | temporalentity
 public   | temporalentityattrinstance_pkey                              | index | ngb   | temporalentityattrinstance
 public   | tenant_database_name_key                                     | index | ngb   | tenant
 public   | tenant_pkey                                                  | index | ngb   | tenant
 public   | unique_c_id                                                  | index | ngb   | csource

**Comment by amitrnec** [comment]
@ScorpioBroker He is using old version.
 scorpiobroker/scorpio:scorpio-aaio-no-eureka_2.1.22

Thanks.
