### ISSUE TITLE
Invalid Link header when query results in pagination

### ISSUE THREAD

**Issue by anyname2** [ScorpioBroker/ScorpioBroker#44]
When making a request for entities that would result in more than 50 entieis (or what is set by `limit` URL parameter), `Link` header in response is invalid.

- URI-Reference needs to be followed by `;` before `rel="next"` 
- Multiple `Link` headers should be present instead of concatenating 2 links with a comma

**Response**
```
link: </?type=T1&q=prop1==val1|prop1==val2&offset=50&limit=50&qtoken=baf00bed-468a-4e0a-8e7f-c8f45da25922>rel="next", <http://localhost:9090/ngsi-ld/atcontext/1580767110>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"
```

**Expected**
```
link: </?type=T1&q=prop1==val1|prop1==val2&offset=50&limit=50&qtoken=baf00bed-468a-4e0a-8e7f-c8f45da25922>; rel="next"
link: <http://localhost:9090/ngsi-ld/atcontext/1580767110>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"
```

**Comment by ScorpioBroker** [comment]
Hi should be fixed now. you'll get different links now and the entry is fixed.
