### ISSUE TITLE
Query Filters not working as expected

### ISSUE THREAD

**Issue by anjasumma** [ScorpioBroker/ScorpioBroker#448]
**issue summary:** several query filter options don't work for me as expected
**Scorpio version:** I am not sure which exact version we use - we use an image of the aio runner from (docker says) two months ago.

I usually check in the [ETSI NGSI-LD API](https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.06.01_60/gs_CIM009v010601p.pdf) when I want to know how something works in Scorpio. This is version 1.6.1 from 08/22. I don't know if Scorpio is already supposed to be up to date with that version.

**Problems description:**
### multiple q filters lead to unexpected results:
I (accidentally) used two q filters instead of one with AND.
expected results: either both querys used for filtering or error message from broker
seen results: first query is executed, second is ignored
I don't know if that's a bug or a feature, but I find it misleading.

### operators not working properly:
I tried some of the operators described in the document on page 58 (top).
Using the "unequal" operator returned thesame results as using the "equal" operator when using the unencoded version (so the "!" was just ignored). Using the encoded version (%x21%x3D) I got a 400 Bad Request error.
My colleague reported that the and operator as semicolon ";" did not work (I think you just fixed that?). Instead the words "AND" or "OR" work, which are not included in the API doc.

**(Additional) Questions:**
Which API level should is Scorpio currently expected to follow and how can i find this out?
How do I find out from a running container which exact version of Scorpio I use?

Thank you for improving Scorpio :)

**Comment by ScorpioBroker** [comment]
Hi Anja,

those issues should be fixed in 4.1.6 please give it another try. 
About the need to encode this params ... i'm currently looking into this but it is most likely something that the framework we are using has to solve. There is currently activity going on to support this properly. Background ... e.g. ; used to be a valid alternative to & in URLs and the RFC was never removed so some webservers are still using it as a separator. So we got to provide the encoded ; at the moment %3B

**Comment by anjasumma** [comment]
Thanks for taking the time to answer :)
I will try to upgrade our version to the 4.1.6 version from Dockerhub. Then I'll test and report the results.

**Comment by anjasumma** [comment]
Thanks to the wonders of Docker and CI/CD, the new version is up and running already:
scorpiobroker/all-in-one-runner:java-kafka-4.1.6   5 minutes ago   Up 5 minutes 

I have no problem to encode the params (it does say so in your documentation), but actually encoding is what **doesn't work**:

The query
`<broker>/ngsi-ld/v1/entities?type=<entity_type>&q=service%x21%x3D="<id>"`
gets me back a 400 Bad Request.

The query
`<broker>/ngsi-ld/v1/entities?type=<entity_type>&q=service!="<id>"`
gets me back (now, in the new version) what I expected :)

For "AND" I now see the encoded version (%x3B) returning me a 400 as well, whereas using "AND" gives me a 500 (maybe my query is bad, I see "ERROR: invalid input syntax for type json (22P02)" whatever that means).
It does work with a semicolon now.


Unfortunately, the mystery of two q filters is also not solved. I think the second one is still ignored silently:
The query
`<broker>/ngsi-ld/v1/entities?type=<entity_type>&q=service=="<some_ID>"&q=configuration[value]==<some_other_ID>`
gives me back (first result even):
```
 "configuration": {
            "type": "Property",
            "value": {
                "parameter": <param_ID>,
                "value": "<different_ID>"
            }
        },
```
where <some_other_ID> != <different_ID>

(If I switch the order, the other q filter is ignored ...)

**Comment by anjasumma** [comment]
The same mystery happens with duplicate "attrs" parameter. I think that might have a common origin ;)
