### ISSUE TITLE
DateTime property is serialized differently in notifications and queries

### ISSUE THREAD

**Issue by anyname2** [ScorpioBroker/ScorpioBroker#45]
Consider this entity:
```json
{
    "id": "urn:ngsi-ld:MyEntity:e1",
    "type": "MyEntity",
    "dateProp": {
        "type": "Property",
        "value": {
            "@type": "DateTime",
            "@value": "2019-11-27T11:42:27Z"
        }
    },
    "@context": {}
}
```

When queried it is serialized as follows (notice the missing `@` on `dateProp.value.type`):
```json
{
    "id": "urn:ngsi-ld:MyEntity:e1",
    "type": "MyEntity",
    "dateProp": {
        "type": "Property",
        "value": {
            "type": "DateTime",
            "@value": "2019-11-27T11:42:27Z"
        }
    },
    "@context": {}
}
```

When entity is sent in a notification it is serialized as follows (`dateProp.value` is seriazlied as string):
```json
{
    "id": "urn:ngsi-ld:MyEntity:e1",
    "type": "MyEntity",
    "dateProp": {
        "type": "Property",
        "value": "2019-11-27T11:42:27Z"
    },
    "@context": {}
}
```

**Expected behaviour**
All 3 representations should be consistent.

**Comment by ScorpioBroker** [comment]
Hi,
i made a fix for this issue. So that query and notification replies look like this `{
    "id": "urn:ngsi-ld:MyEntity:e1",
    "type": "MyEntity",
    "dateProp": {
        "type": "Property",
        "value": {
            "type": "DateTime",
            "@value": "2019-11-27T11:42:27Z"
        }
    },
...
}`
The replacement of @type with type is defined behaviour due to the ngsi-ld core context.
