### ISSUE TITLE
Subscriptions without notification attributes not accepted

### ISSUE THREAD

**Issue by tanktoo** [ScorpioBroker/ScorpioBroker#47]
Hi,
I tried to do a subscription:

```
{
    "id": "urn:ngsi-ld:Subscription:1201",
    "type": "Subscription",
    "entities": [
        {
            "type": "Vehicle"
        }
    ],
    "watchedAttributes": [
        "speed"
    ],
    "notification": {
        "format": "keyValues",
        "endpoint": {
            "uri": "bla.de",
            "accept": "application/json"
        }
    },
  "@context":[
        "http://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld",
        {
            "Vehicle": "http://example.org/vehicle/Vehicle",
            "brandName": "http://example.org/vehicle/brandName",
            "speed": "http://example.org/vehicle/speed"
        }
  ]
}
```

Subscription is the same as in the examples but I deleted the "attributes" in "notification". I think this should be allowed according to the standard in section 5.2.14.1:

> attributes     string[]  Attribute Name as short-hand string. Empty array (0 length) is not allowed 0..1 Entity Attribute Names (Properties or Relationships) to be included in the notification payload body. If undefined it will mean all Attributes

Would be great it this can be checked.

**Comment by ScorpioBroker** [comment]
Hi this should be addressed now and will send all attribs of an entity if the attribute entry is not present in the notification part.
