### ISSUE TITLE
Question: Is there a way to use Transport Layer Security (TLS)?

### ISSUE THREAD

**Issue by dyrmig** [ScorpioBroker/ScorpioBroker#489]
Scorpio will only work when I disable TLS in my Postgres server (require_secure_transport disabled).
Idealy It would be a good security practice to have TLS activated.
Is threre a way to work with SSL/TLS connections?

**Comment by ScorpioBroker** [comment]
Hi,

currently the setting for SSL on postgres is set to disabled (default). If you want to change it you can set the env var to 
QUARKUS_DATASOURCE_REACTIVE_POSTGRESQL_SSL_MODE to any of those
disable, allow, prefer, require, verify-ca, verify-full

if want to verify you got to set 
QUARKUS_DATASOURCE_REACTIVE_KEY_CERTIFICATE_PEM to true  
QUARKUS_DATASOURCE_REACTIVE_KEY_CERTIFICATE_PEM_KEYS to the keys 
and respectively 
QUARKUS_DATASOURCE_REACTIVE_TRUST_CERTIFICATE_PEM
QUARKUS_DATASOURCE_REACTIVE_TRUST_CERTIFICATE_PEM_CERTS

There is also a JDBC part for migration where you would need to overwrite the jdbc url with respective settings
set the env var
JDBCURL respectively please check here for details 
https://quarkus.io/guides/datasource#jdbc-url


however this will currently most likely not work with tenant as those clients are generated programmatically and we didn't address this part. I'll ping back on here if this is confirmed to work with tenants
