### ISSUE TITLE
Semantically Versioned Docker Images are not available.

### ISSUE THREAD

**Issue by jason-fox** [ScorpioBroker/ScorpioBroker#49]
When using Docker Images in a production environment, it is bad practice to default to "latest" - e.g. https://vsupalov.com/docker-latest-tag/ - I would like fixed tags based on the product release.

Currently Scorpio does not offer semantic versions on DockerHub. I've noticed the latest release (0.9.5) has just been tagged on [GitHub ](https://github.com/ScorpioBroker/ScorpioBroker/releases/tag/0.9.5) - could someone also retag the build components on DockerHub?

e.g.

* scorpiobroker/scorpio:scorpio-aaio_0.9.5
* scorpiobroker/scorpio:SubscriptionManager_0.9.5
* scorpiobroker/scorpio:gateway_0.9.5
* scorpiobroker/scorpio:AtContextServer_0.9.5
* scorpiobroker/scorpio:config-server_0.9.5
* scorpiobroker/scorpio:EntityManager_0.9.5
* scorpiobroker/scorpio:eureka-server_0.9.5
* scorpiobroker/scorpio:HistoryManager_0.9.5
* scorpiobroker/scorpio:QueryManager_0.9.5
* scorpiobroker/scorpio:RegistryManager_0.9.5
* scorpiobroker/scorpio:StorageManager_0.9.5
* scorpiobroker/scorpio:SubscriptionManager_0.9.5

**Comment by Takezo36** [comment]
Hi Jason,
Benjamin here (private account). Yes definately doing that. I've changed the build script to add build versions to the tag and have uploaded an 0,9,5 of the aaio version. I'll tag the rest next week when i'm back at work.

Benjamin

**Comment by ScorpioBroker** [comment]
Hi Jason,

i've uploaded the versioned containers now and updated the yml files for docker-compose. As with the aaio version, normal points to the dockerhub version and dev to maven build version.
We will keep this up from now.

Regards
Benni
