### ISSUE TITLE
Location property value shouldn't be scaped

### ISSUE THREAD

**Issue by mainakae** [ScorpioBroker/ScorpioBroker#5]
Hello all,

I've noticed that the value of the Location property has to be scaped in order for it to work. As I understand, this doesn't follow the specification, and as such should be fixed.

Example of how it's working as of now:

```json
{
  "location":{
    "type":"GeoProperty",
    "value":"{ \"type\":\"Point\", \"coordinates\":[ -8.5, 41.2 ] }"
  }
}
```

And how it should be:

```json

  "location":{
    "type":"GeoProperty",
    "value": {
        "type": "Point",
        "coordinates": [ -8.5, 41.2 ] 
    }
  }
```

Thanks for your time and the great work you are putting in this project, and best regards.
Pedro.

**Comment by ScorpioBroker** [comment]
Hi,

yes we will change this to support both input variants. This is a bit of an "ugly" solution because of some problems with geo json and json-ld. geo json allows this so it's kind of fine. But will definately address this in one of the next updates.

Thanks & Regards
Benjamin

**Comment by ScorpioBroker** [comment]
Hi i updated the parsing and we now allow both as input for the broker and will only provide the none escaped version as output.

BR
Benjamin
