### ISSUE TITLE
Consise notation raises an error when posting or updating an entity

### ISSUE THREAD

**Issue by alifrugal** [ScorpioBroker/ScorpioBroker#501]
I am trying to post and/or update (using single or batch operations) an entity using the concise notation with an attribute : 

```json 
 {
            "id": "urn:ngsi-ld:Example:example-1",
            "type": "Example",
           "someAttribute": {
            "value": "someValue",
            "observedAt": "2023-12-25T14:53:33.803Z",
            "providedBy": {
                "object": "some:urn"
            }
        }
}
```

This raises the following error: 
```json
{
    "type": "https://uri.etsi.org/ngsi-ld/errors/BadRequestData",
    "title": "Bad Request Data.",
    "detail": {
        "message": "The key providedBy is an invalid entry."
    },
    "errorCode": 400
}
```

If I specify the type of the attribute then I can post the entity. 

This doesn't raise any error: 

```json 
 {
            "id": "urn:ngsi-ld:Example:example-1",
            "type": "Example",
           "someAttribute": {
            "type": "Property", 
            "value": "someValue",
            "observedAt": "2023-12-25T14:53:33.803Z",
            "providedBy": {
                "object": "some:urn"
            }
        }
}

```

**Comment by jason-fox** [comment]
I think this has been fixed in 4.1.15.  I tested the following concise create in #416

> ```console
> curl -L 'http://localhost:9090/ngsi-ld/v1/entities/' \
> -H 'Content-Type: application/json' \
> -H 'Link: <http://context/ngsi-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
> -d '{
>     "id": "urn:ngsi-ld:City:002",
>     "type": "City",
>     "temperature": {
>         "value": 25,
>         "unitCode": "CEL",
>         "observedAt": "2022-06-30T00:00:00.000Z"
>     },
>     "address": {
>         "value": {
>             "streetAddress": "Viale di Valle Aurelia",
>             "addressRegion": "Lazio",
>             "addressLocality": "Roma",
>             "postalCode": "00138"
>         }
>     },
>     "location": {
>         "type": "Point",
>         "coordinates": [
>             12.482,
>             41.893
>         ]
>     },
>     "population": {
>         "value": 4342212,
>         "observedAt": "2021-01-01T00:00:00.000Z"
>     },
>     "name": {
>         "languageMap": {
>             "el": "Ρώμη",
>             "en": "Rome",
>             "it": "Roma"
>         }
>     },
>     "runBy": {
>         "object": "urn:ngsi-ld:Adminstration:001"
>     }
> }'
> ```
