### ISSUE TITLE
Notification does not supply correct header information.

### ISSUE THREAD

**Issue by jason-fox** [ScorpioBroker/ScorpioBroker#510]
Scorpio 4.1.11

I create a Subscription on a tenant as shown:

```console
curl -L -X POST 'http://localhost:1026/ngsi-ld/v1/subscriptions/' \
-H 'Content-Type: application/ld+json' \
-H 'NGSILD-Tenant: openiot' \
--data-raw '{
  "description": "Notify me of all feedstock changes",
  "type": "Subscription",
  "entities": [{"type": "FillingLevelSensor"}],
  "watchedAttributes": ["filling"],
  "notification": {
    "attributes": ["filling", "location"],
    "format": "normalized",
    "endpoint": {
      "uri": "http://tutorial:3000/subscription/low-stock-farm001",
      "accept": "application/json",
      "receiverInfo": [
        {
          "key": "fiware-service",
          "value": "openiot"
        }
      ]
    }
  },
   "@context": "http://context/ngsi-context.jsonld"
}'
```

I then trigger the subscription using the following upsert.

```console
curl -L -X POST 'http://localhost:9090/ngsi-ld/v1/entityOperations/upsert/?options=update' \
-H 'Content-Type: application/ld+json' \
-H 'NGSILD-Tenant: openiot' \
--data-raw '[
        {
            "@context": "http://context/ngsi-context.jsonld",
            "id": "urn:ngsi-ld:Device:filling002",
            "type": "FillingLevelSensor",
            "filling": {
                "type": "Property",
                "value": 0.96,
                "unitCode": "C62",
                "accuracy": {
                    "type": "Property",
                    "value": 0.05
                },
                "observedAt": "2024-01-12T13:28:33.867Z"
            }
        }
    ]'
```

The expected headers at the receiver endpoint are:

-  `Content-Length` :`433`  
-  `Content-Type` : `application/json`
-  `User-Agent` : `Vert.x-WebClient/4.4.4`
-  `Host` : `tutorial:3000`
-  `Accept` : `application/json`
-  `Link` : `<http://context/ngsi-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"`
-  `Ngsild-Tenant` : `openiot`
-  `fiware-service` : `openiot`

The actual headers received at the receiver endpoint are:

-  `Content-Length` : `433` ✅ 
-  `User-Agent` : `Vert.x-WebClient/4.4.4` ✅ 
-  `Accept` : `application/json` ✅ 
-  `Host` : `tutorial:3000` ✅ 
-  `value` : `openiot`  ❌ 
-  `key` : `fiware-service`  ❌ 

> [!NOTE]
>
> Headers are case insensitive.

The issues are as follows:

1.  `Content-Type` header is missing -  according to the specification this MIME type should be present and should default to `application/json`
2.  The `Link` header is missing - since the payload is supposed be be JSON, the `@context` should be found in the `Link` header in this case. Note that if the content-type was specified to be application/ld+json the `Link` header is not present.
3.  The Subscription was set up on a tenant - the `Ngsild-Tenant` is missing on the notification.
4.  `receiverInfo` is defined  an array of objects each with a `key` and `value`, these are being misinterpreted as the names of the headers themselves. i.e  `fiware-service` : `openiot`  not  -  `value` : `openiot`  and  `key` : `fiware-service`  

>   **6.3.14 Tenant specification**
>
> In case the target tenant is the default tenant, the HTTP header is omitted. If
> the HTTP header "NGSILD-Tenant" is present in the HTTP request, it shall also be present in HTTP response. This
> also applies to HTTP notifications sent as a result of subscriptions with an "NGSILD-Tenant" HTTP header
>(clause 6.3.8).

**Comment by jason-fox** [comment]
The lack of the `Content-Type` header  means that other microservices will have difficulty in interpreting the notification. This is causing issues with QuantumLeap for example, which interprets the missing header as an error. For the NGSI-LD tutorial application the notification is received, but the body cannot be displayed (since it is of an unknown `Content-Type`

**Comment by jason-fox** [comment]
See https://www.rfc-editor.org/rfc/rfc9110#field.content-type

> A sender that generates a message containing content SHOULD generate a Content-Type header field in that message unless the intended media type of the enclosed representation is unknown to the sender. If a Content-Type header field is not present, the recipient MAY either assume a media type of "application/octet-stream" ([[RFC2046](https://www.rfc-editor.org/rfc/rfc9110#RFC2046)], [Section 4.5.1](https://www.rfc-editor.org/rfc/rfc2046#section-4.5.1)) or examine the data to determine its type.

So it is perfectly reasonable for a receiver **not** to assume that the notification is `application/json` if the `Content-Type` header is missing.

**Comment by amitrnec** [comment]
Hi,
we are working on this issue.

Thanks.

**Comment by jason-fox** [comment]
I am unable to test this on the latest release, since I cannot create a valid subscription on 4.1.15 due to #527
