### ISSUE TITLE
URL encoded semicolon (%3B) raises an internal error with Scopes 

### ISSUE THREAD

**Issue by alifrugal** [ScorpioBroker/ScorpioBroker#513]
When testing Scopes, I hit the wrong key and typed `%3B` instead of `%23`and it has raised an internal error. 

The `%3B` should be ignored or escaped when used in Scopes to not generate an error (or catch the error). 

```json
{
    "type": "https://uri.etsi.org/ngsi-ld/errors/InternalError",
    "title": "Internal error",
    "detail": {
        "message": "Cannot read the array length because \"<local2>\" is null"
    },
    "errorCode": 500
}
```

Example of entity to reproduce the issue: 

```json
{
    "id": "urn:ngsi-ld:Example:Ex1",
    "type": "Example",
    "name": "Ex1",
    "scope": "/Example/Ex1"
}
```
Then perform a GET `/ngsi-ld/v1/entities?type=Example&scopeQ=/Example/%3B`

**Comment by amitrnec** [comment]
Hi,
We are working on it.

Thanks.

**Comment by martin-p-bauer** [comment]
I think it should be a "bad request" error. %3B is a semicolon, which is used as a logical "and" in the scope query language (NGSI-LD spec, clause 4.19). "And" cannot have an empty second parameter,  so it is a bad request.

**Comment by alifrugal** [comment]
> I think it should be a "bad request" error. %3B is a semicolon, which is used as a logical "and" in the scope query language (NGSI-LD spec, clause 4.19). "And" cannot have an empty second parameter, so it is a bad request.

Agree, I think that's the best way to handle it
