### ISSUE TITLE
Empty array of relationship raises an error when using follow relationship query feature

### ISSUE THREAD

**Issue by alifrugal** [ScorpioBroker/ScorpioBroker#514]
When using the follow relationship feature on an entity that has a relationship that contains an empty array, this generates an error.

Example of an entity to reproduce the error: 

```json 
{
    "id": "urn:ngsi-ld:Example:Ex1",
    "type": "Example",
    "name": "Ex1",
    "hasChild": {
        "object": [],
        "objectType": "Example"
    }
}
```

Query to perform: `/ngsi-ld/v1/entities/urn:ngsi-ld:Example:Ex1?join=inline&joinLevel=2`

**Comment by amitrnec** [comment]
Hi,

This issue has already been fixed. will release soon.

Thanks.

**Comment by alifrugal** [comment]
Thanks, closing it then.

**Comment by alifrugal** [comment]
Per @amitrnec comment, this is fixed in the next version.
