### ISSUE TITLE
Error in subscriptions: "cannot determine type of sub attribute. please provide a valid type"

### ISSUE THREAD

**Issue by alifrugal** [ScorpioBroker/ScorpioBroker#517]
I am not sure what causes the issue but my subscriptions stopped being triggered and I am seeing this error logs from scorpio:
 
```
{
    "status": "DOWN",
    "checks": [
        {
            "name": "SmallRye Reactive Messaging - liveness check",
            "status": "DOWN",
            "data": {
                "application-eu.neclab.ngsildbroker.subscriptionmanager.messaging.SubscriptionMessagingString#handleBatchEntities": "[KO] - cannot determine type of sub attribute. please provide a valid type"
            }
        },
        {
            "name": "Reactive PostgreSQL connections health check",
            "status": "UP",
            "data": {
                "<default>": "UP"
            }
        },
        {
            "name": "SmallRye Reactive Messaging - readiness check",
            "status": "DOWN",
            "data": {
                "application-eu.neclab.ngsildbroker.subscriptionmanager.messaging.SubscriptionMessagingString#handleBatchEntities": "[KO] - cannot determine type of sub attribute. please provide a valid type"
            }
        },
        {
            "name": "Database connections health check",
            "status": "UP",
            "data": {
                "<default>": "UP"
            }
        },
        {
            "name": "SmallRye Reactive Messaging - startup check",
            "status": "UP"
        }
    ]
}```

**Comment by alifrugal** [comment]
After some investigation, it seems that having `objectType` specified in relationships of entities are causing subscriptions using `q` to crash the broker. 

Example below of an attribute that makes subscriptions using `q` to crash. 

`"someAttribute": {
  "type": "Relationship",
  "objectType": "someType",
  "object": "urn:ngsi-ld:someType:ST1"
}`

**Comment by brijeshnec** [comment]
Hi @alifrugal,
I attempted to replicate the process but encountered difficulties. Could you please share the precise steps? 
Thanks.

**Comment by amitrnec** [comment]
Hi,
We are not able to reproduce this issue so kindly can you share the steps.

Thanks.

**Comment by alifrugal** [comment]
I think @ScorpioBroker has fixed the issue there: https://github.com/ScorpioBroker/ScorpioBroker/commit/b789dec54598fb64839d8ad99a39a3912765f9e5

But to respond, I had entities with attributes containing `objectType` like this one: 

`"someAttribute": { "type": "Relationship", "objectType": "someType", "object": "urn:ngsi-ld:someType:ST1" }`

When creating a subscription to monitor these entities with a query `q`, the container were crashing with the error: 
`com.google.gson.JsonParseException: cannot determine type of sub attribute. please provide a valid type`
