### ISSUE TITLE
Trailing slash is currently mandatory on URLs

### ISSUE THREAD

**Issue by jason-fox** [ScorpioBroker/ScorpioBroker#52]
When creating a new entity I use the following syntax:

```console
curl -iX POST 'http://localhost:9090/ngsi-ld/v1/entities/' \
--header 'Content-Type: application/ld+json' \
--data-raw '{ ... etc  }'
````

and the entity is created successfully

If however I use the URL `http://localhost:9090/ngsi-ld/v1/entities`  - i.e. without the closing slash I get:

```json
{
    "timestamp": "2020-01-14T10:36:39.338+0000",
    "status": 405,
    "error": "Method Not Allowed",
    "message": "Request method 'POST' not supported",
    "path": "/ngsi-ld/v1/entities"
}
```

The NGSI-LD specification section 6.4.2. **does** state the following:

> Resource URI:
> * `/entities/`

However the **URI Generic Syntax definition**  [rfc3986](https://tools.ietf.org/html/rfc3986) states that the lack of a trailing slash should be considered as equivalent to avoid false negatives. Basically both `/entities/` and `/entities` should be supported make the broker more user friendly.

Furthermore the current example in the [README.md](https://github.com/ScorpioBroker/ScorpioBroker#usage) *does not* use a trailing slash and therefore the example does not work.

**Note:** a GET request for a specific `type` does not require a slash before the `?`- so the following works which would seem to indicate that the final slash should be optional

```console
curl  GET 'http://localhost:1026/ngsi-ld/v1/entities?type=https://uri.fiware.org/ns/data-models%23Building'
```

Tested on AAIO 0.9.5

**Comment by ScorpioBroker** [comment]
Comment for handling.
Should be addressed when we change the gateway server

**Comment by ScorpioBroker** [comment]
Hi, addressed this in feature 52 merged. Fixed now
