### ISSUE TITLE
Obtain Version Information and Health Status

### ISSUE THREAD

**Issue by daniel-gonzalez-sanchez** [ScorpioBroker/ScorpioBroker#525]
Hi all,

Is there any version checking endpoint available in Scorpio Context Broker? I mean, an endpoint that returns information about the vendor, the version number, as well as the uptime or health status of the context broker.

In the past, I know there was a `/scorpio/v1/info/` endpoint that provides this type of information to be sure that the context broker is up and to get its descriptive information. I have tested that this endpoint is no longer active in the latest versions of Scorpio and I have not found information about it in the official Scorpio documentation. Is there another endpoint accessible for such a purpose?

Thank you in advance!

Best regards,
Dani

**Comment by amitrnec** [comment]
Hi,
You can use these endpoints for Scorpio Broker build info and health check.

-  /q/info
- /q/health

Thanks.

**Comment by daniel-gonzalez-sanchez** [comment]
Thank so much @amitrnec! Just what I required!

Best regards,
Dani
