### ISSUE TITLE
`q` parameter is dropped from forwarded query retrieval request.

### ISSUE THREAD

**Issue by jason-fox** [ScorpioBroker/ScorpioBroker#535]
Testing **SCORPIO 4.1.15**,  I have a series of entities within an isolated Context broker:

```json
[
     {
        "id": "urn:ngsi-ld:Store:001",
        "type": "Store", ..etc
    },
    {
        "id": "urn:ngsi-ld:Store:002",
        "type": "Store", ..etc
    },
   {
        "id": "urn:ngsi-ld:Store:003",
        "type": "Store",
        "name": {
            "type": "Property",
            "value": "East Side Galleria"
        }
    }
]
```

If I make a query directly on the isolated broker I receive one entry: ✅ 

```console
curl -L 'http://localhost:3005/ngsi-ld/v1/entities?type=Store&q=name%3D%3D%22East%20Side%20Galleria%22 
```

```json
  {
        "id": "urn:ngsi-ld:Store:003",
        "type": "Store",
        "name": {
            "type": "Property",
            "value": "East Side Galleria"
        }
 }
```

I now register that context broker as a ContextSource on **Scorpio** using a registration:

```console
curl -L 'http://localhost:1026/ngsi-ld/v1/csourceRegistrations/' \
-H 'Link: <http://context/ngsi-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
-H 'Content-Type: application/json' \
-d '{
    "type": "ContextSourceRegistration",
    "information": [
        {
            "entities": [
                {
                    "type": "Store"
                }
            ]
        }
    ],
    "contextSourceInfo": [
        {
            "key": "jsonldContext",
            "value": "http://context/ngsi-context.jsonld"
        }
    ],
    "mode": "inclusive",
    "operations": [
        "federationOps"
    ],
    "endpoint": "http://registrant-broker"
}'
```

If I make a query directly on **Scorpio**, I  now receive multiple entries:  ❌ 

```console
curl -L 'http://localhost:9090/ngsi-ld/v1/entities?type=Store&q=name%3D%3D%22East%20Side%20Galleria%22 
```

```json
[
     {
        "id": "urn:ngsi-ld:Store:001",
        "type": "Store", ..etc
    },
    {
        "id": "urn:ngsi-ld:Store:002",
        "type": "Store", ..etc
    },
   {
        "id": "urn:ngsi-ld:Store:003",
        "type": "Store",
        "name": {
            "type": "Property",
            "value": "East Side Galleria"
        }
    }
]
```

Under the hood, Scorpio is sending two requests to the Context Source that is registered:

-  GET `/ngsi-ld/v1/entities?type=Store&limit=1000` 
-  GET `/ngsi-ld/v1/entities?id=urn%3Angsi-ld%3AStore%3A001,urn%3Angsi-ld%3AStore%3A002,urn%3Angsi-ld%3AStore%3A003,urn%3Angsi-ld%3AStore%3A004&options=sysAttrs&limit=1000`

Whereas the expected forwarded request should be:

- GET `/ngsi-ld/v1/entities?type=Store&limit=1000&q=name==%22East%20Side%20Galleria%22`

**Comment by martin-p-bauer** [comment]
The final result should of course only be Store:003, but the forwarded request may not contain q as you expect. We decided to support also distributed entities and it could be that one attribute checked in q is in one Broker and another in another Broker and in this case q would fail in both cases, filtering out the entity, but if you were to filter on the integrated entity, it would be included. Thus, what is currently not working correctly is the filter on the distribution broker side.
