### ISSUE TITLE
SQS can't be used to broadcast messages

### ISSUE THREAD

**Issue by alifrugal** [ScorpioBroker/ScorpioBroker#556]
In java-sqs implementation, SQS is used to broadcast messages to other services. SQS should be only used for one consumer as when a consumer reads the message, it applies a visibility time to hide the message from other consumers for the time to process it.
When the message is processed, the consumer then deletes it from the queue. 

This means a message is only received by only one of the consumer services (subscription, registry, history) that should receive it.

The services need to be rearchitected to use SNS to fan out to dedicated SQS queue per service.

**Comment by ScorpioBroker** [comment]
Adressed in 5.0.0 with SNS fanoutservice
