### ISSUE TITLE
Aggregated Temporal Representation of Entity query fails

### ISSUE THREAD

**Issue by yshashix** [ScorpioBroker/ScorpioBroker#560]
Scorpio version: aio-runner 4.1.15-SNAPSHOT

I am running Scorpio using in-memory and building it from source code.
When I was trying to run examples from https://github.com/ScorpioBroker/ScorpioBroker/blob/development-quarkus/docs/en/source/aggregation-support.rst , it gives below output for query operation.
`{
    "type": "https://uri.etsi.org/ngsi-ld/errors/InvalidRequest",
    "title": "Invalid request.",
    "detail": "observedAt' is not an allowed timeproperty. Use createdAt or deletedAt or modifiedAt or observedAt",
    "status": 400
}`

Note: I have to modify create operation body as well because @context in the body of rest API call failed. I removed @context from body and it worked. I can see create operation data on temporalentityattrinstance postgres table.

Can you tell me what could be problem?

**Comment by brijeshnec** [comment]
Hi,

Thank you for bringing this to my attention.

I've identified and corrected a minor mistake in the document. Please refer to the updated version attached.

Thanks
