### ISSUE TITLE
Merge patch behaves erroneously and overwrites fields, when it's not supposed to

### ISSUE THREAD

**Issue by MericFeyz** [ScorpioBroker/ScorpioBroker#578]
The merge patch behavior does not work as intended. I have been following the docs, specifically the [mergepatch.rst](https://github.com/ScorpioBroker/ScorpioBroker/blob/development-quarkus/docs/en/source/mergepatch.rst), and currently Scorpio behaves neither like the documentations nor the NGSI-LD 1.7.1 specification. 

Steps: 
- Create the following entity 
```
{
    "id": "urn:ngsi-ld:smartHospital:room01",
    "type": "Room",
    "temperatureSensor": {
        "type": "Property",
        "value": "23",
        "unit": {
            "type": "Property",
            "value": "CEL"
        },
        "observedAt": "2023-06-28T13:21:00.000Z"
    },
    "humiditySensor": {
        "type": "Property",
        "value": 22
    },
    "address": {
        "type": "Property",
        "value": {
            "roomno": 2,
            "streetaddress": "luxemburg"
        }
    },
    "isPartOf": {
        "type": "Relationship",
        "object": "urn:ngsi-ld:smartHospital"
    }
}
```
- Make a PATCH request to `http://localhost:9090/ngsi-ld/v1/entities/urn:ngsi-ld:smartHospital:room01` with the following merge patch:

```
{
    "temperatureSensor": {
        "type": "Property",
        "value": 32.7,
        "observedAt": "2023-06-28T14:21:00.000Z"
    },
    "humiditySensor": {
        "type": "Property",
        "value": "urn:ngsi-ld:null"
    },
    "address": {
        "type": "Property",
        "value": {
            "roomno": 13,
            "streetaddress": "luxemburg"
        }
    }
}
```
- Receive the 400 Bad request error: 
```
{
    "type": "https://uri.etsi.org/ngsi-ld/errors/BadRequestData",
    "title": "Bad Request Data.",
    "detail": "The key observedAt is an invalid entry.",
    "status": 400
}
```
- Remove the observedAt key and make the patch request again. Query the entity:
```
{
    "id": "urn:ngsi-ld:smartHospital:room01",
    "type": "Room",
    "address": {
        "type": "Property",
        "value": {
            "roomno": 13,
            "streetaddress": "luxemburg"
        }
    },
    "isPartOf": {
        "type": "Relationship",
        "object": "urn:ngsi-ld:smartHospital"
    },
    "temperatureSensor": {
        "type": "Property",
        "value": 32.7
    }
}
```
Now the temperatureSensor value is deformed as it lost its observedAt and unit key-value pairs. This is not how the merge patch request should behave, instead it should leave the observedAt and unit key-value pairs untouched, like it suggests in the docs. 

Tested on the development-quarkus branch, built with the ```mvn clean package -DskipTests -Ddocker -Ddocker-tag=java-kafka-latest -Dkafka -Pkafka -Dquarkus.profile=kafka -Dos=java``` arguments and deployed with the docker-compose-java-aaio-kafka.yml compose file.

**Comment by MericFeyz** [comment]
Any updates on this issue?

**Comment by ScorpioBroker** [comment]
Hi this is fixed in github ... next release  will be tomorrow or the day after ... sorry for the long delay we had to take care of bigger changes which came with 1.8.1 ngsi-ld.

**Comment by MericFeyz** [comment]
That is great to hear. I have tried debugging the issue myself but looking at the pull request you're preparing it looks like a comprehensive fix was needed. Thanks!

**Comment by ScorpioBroker** [comment]
5.0.0 is released please update.
