### ISSUE TITLE
Reduce number of kafka topics for Azure Eventhub

### ISSUE THREAD

**Issue by ThomasDh** [ScorpioBroker/ScorpioBroker#579]
In version 4.1.9, a new Kafka topic was introduced for the Scorpio versions using kafka **(histsync).**
This now brings the total number of topics required from 10 topics to 11 topics. This introduces a cost problem for using Scorpio broker with Azure Eventhubs. 

We run the Scorpio Broker on Azure with Eventhubs as our message bus (using kafka API's). Eventhubs on the standard tier only supports 10 event hubs per namespace (1 event hub in a namespace = 1 kafka topic). This is due to limitations of [Azure Event Hub Tiers](https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-quotas#basic-vs-standard-vs-premium-vs-dedicated-tiers)

- Until **version 4.1.8** (with 10 topics), this runs fine on a __Standard__ tier Eventhub. 
Cost start around **20,5 euro / month**.
- From **version 4.1.9** (with 11 topics) we would need to use a **Premium** tier Eventhub. 
Cost starts around **913 euro / month**

This is a significant cost increase for 1 additional topic.
Is it possible to reduce the number of topics or run the all-in-one runner without 1 of the topics?

**Comment by ScorpioBroker** [comment]
hi,
we have reduced it down to 5 topics now and also provide an option to compress some of the payload in the message bus in the next release. Tomorrow or the day after

**Comment by ScorpioBroker** [comment]
5.0.0 is released please update.
