### ISSUE TITLE
Geoquery not supported (unencoded bracket)

### ISSUE THREAD

**Issue by jason-fox** [ScorpioBroker/ScorpioBroker#58]
I create an entity:

```console
curl -L -X POST 'http://localhost:9090/ngsi-ld/v1/entities/' \
-H 'Content-Type: application/ld+json' \
--data-raw '{
    "id": "urn:ngsi-ld:Building:store001",
    "type": "Building",
    "category": {
    	"type": "Property",
        "value": ["commercial"]
    },
    "address": {
        "type": "Property",
        "value": {
            "streetAddress": "Bornholmer Straße 65",
            "addressRegion": "Berlin",
            "addressLocality": "Prenzlauer Berg",
            "postalCode": "10439"
        },
        "verified": {
			"type": "Property",
			"value": true
		}
    },
    "location": {
        "type": "GeoProperty",
        "value": {
             "type": "Point",
             "coordinates": [13.3986, 52.5547]
        }
    },
    "name": {
        "type": "Property",
        "value": "Bösebrücke Einkauf"
    },
    "@context": [
        "https://schema.lab.fiware.org/ld/context"
    ]
}'
```

I make a geo-query using the `georel` parameter searching on a sub-attribute - see p38 of the specification

 > EXAMPLE 3: Geo-query encoded as an HTTP Query String, please note that this is HTTP binding specific.
> ` ?type=Vehicle&georel=near;maxDistance==2000&geometry=Point&coordinates=[8,40]`

```console
curl -L -X GET 'http://localhost:9090/ngsi-ld/v1/entities/?type=Building&geometry=Point&coordinates=[13.3777,52.5162]&georel=near;maxDistance==5000&options=keyValues' \
-H 'Link: <https://schema.lab.fiware.org/ld/context>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
-H 'Accept: application/ld+json'
```

Scorpio returns a 400 response with an unformatted error page:

Expected:

```json
[
    {
        "@context": "https://fiware.github.io/data-models/context.jsonld",
        "id": "urn:ngsi-ld:Building:store001",
        "type": "Building",
        "address": {
            "streetAddress": "Bornholmer Straße 65",
            "addressRegion": "Berlin",
            "addressLocality": "Prenzlauer Berg",
            "postalCode": "10439"
        },
        "name": "Bösebrücke Einkauf",
        "category": [
            "commercial"
        ],
        "location": {
            "type": "Point",
            "coordinates": [
                13.3986,
                52.5547
            ]
        }
    }
]
```

**Comment by ScorpioBroker** [comment]
Hi Jason,

i think this is a url encoding problem. We have always url encoded our requests and that works. As far as i understand the rfc for that (i'm in no way an expert for this) ",", "[", "]" are considered special delimiters for http requests and should/must be url encoded if to be used as value, as it is the case here. 
https://tools.ietf.org/html/rfc3986#section-2

I'm a bit unsure at the moment how this should be handled.

Benni

**Comment by jason-fox** [comment]
If you look at **Appendix D**, you'll find the following:

> Square brackets are now specified as reserved within the
   authority component and are not allowed outside their use as
   delimiters for an IP literal within host.  In order to make this
   change without changing the technical definition of the path, query,
   and fragment components, those rules were redefined to directly
   specify the characters allowed.

Which if I've read it correctly means that square brackets are explicitly allowed in the query params, so it should be the case that Scorpio is able to interpret them.

**Comment by jason-fox** [comment]
Note:

```console
curl -L -X GET 'http://localhost:9090/ngsi-ld/v1/entities/?type=Building&geometry=Point&coordinates=%5B13.3777%2C52.5162%5D&georel=near;maxDistance==2000&options=keyValues' \
-H 'Link: <https://schema.lab.fiware.org/ld/context>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
-H 'Accept: application/ld+json'
```

does  return valid data as expected.

**Comment by kzangeli** [comment]
postman probably url-encode before sending, that would be a logical reason as to why it works.
Not sure that it should be mandatory to url-encode though ...
The spec is not too clear about this.
It would definitely be nice to accept brackets without encoding. It's user-friendly.
@jason-fox - does orion-ld accept your request?

**Comment by jason-fox** [comment]
More info: https://stackoverflow.com/a/39294315/1179828  - particularly at the last paragraph.

**Orion-LD** accepts the URL with the square brackets unencoded. **Scorpio** does not.
Interpreting the unencoded brackets is not a violation of RFC 3986. Sending the data without encoding is.

Your move @ScorpioBroker  😄

**Comment by jason-fox** [comment]
@ScorpioBroker  @kzangeli 

My current thought on this issue is that the NGSI-LD spec itself needs to be updated and clarified as to whether it is necessary to respond to non-RFC 3986 compliant requests. I don't think it does any harm, and obviously it makes the URLs easier to read. Whether this functionality is  mandatory or not I don't know.

At the moment it seems to be a beneficial quirk of **Orion-LD**, but I'd like someone else to pass a judgement on this before withdrawing this and #57

**Comment by kzangeli** [comment]
@martin-p-bauer - would be good to hear some feedback from you

**Comment by martin-p-bauer** [comment]
@ScorpioBroker @jason-fox  @kzangeli 

Yes, we started discussing this - and the NGSI-LD specification is quite silent on this at the moment and we need to address the problem there. 

It is good practice to URL-encode, but we have to decide whether to also allow the non-encoded version. 

According to Benjamin's interpretation Appendix D of RFC 3986 exclusively refers to the host portion, i.e. the use of square brackets for IPv6 host addresses, so in his opinion it does not invalidate the requirement of URL-encoding parameter values. 

In ETSI ISG CIM, we had also discussed the case that somebody wanted to have something including %20 in a non-encoded identifier - of course this was decoded and then retrieving did not work as expected. This case is only solvable if you explicitly URL-encode. -->%%20 

So, we need to decide whether we want to allow non-URL-encoded parameters. A way to do it would be to recommend it as best practice, but be lenient in case it is not done. However, it is then at the risk of the user if there is a "%20" or similar in the non-encoded name that this will lead to results not expected by the user.

**Comment by ScorpioBroker** [comment]
Hi all i made an update to the gateway to allow [] as characters.
However in regards to the spec. 
Appendix D referes to the authority part of an uri which is the host. It explicitly ends with the first /. This does not allow an unescaped use of [] after that. 
https://tools.ietf.org/html/rfc1738#section-2.2
rfc1738 list them explictly as unsafe characters which must be encoded.
To allow them or use them is super discouraged by everyone as you can't rely on the assumption that all component (proxies, gateways, etc.) on your request route will allow them, because it's against http specs.
While looking into the case in our specific impl. I've seen that tomcat removed the external config option to allow those characters, because it is so discouraged and against the rfc. 

I've no problem in allowing them on our gateway but everything behind the brokers, any other context source we cannot guarantee a proper behaviour like this.
This should be highly discouraged by the ngsi-ld spec imho.

**Comment by kzangeli** [comment]
ok, makes sense. Let's encourage to have them encoded.
A question remains, should we forbid the usage of unencoded []? 
- To avoid possible future problems ...
