### ISSUE TITLE
"Bad Request Data" on context source registration creation (POST /csourceRegistrations)

### ISSUE THREAD

**Issue by MS-Fiware** [ScorpioBroker/ScorpioBroker#6]
Hi,

when trying to create a context source registration with POST /csourceRegistrations I get a "400 Bad Request Data" in the HTTP response, although the [spec](https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.01.01_60/gs_CIM009v010101p.pdf) states that at creation time the id is optional and is assigned during registration process, if not provided.

My request:

`curl -X POST \
  http://192.168.57.101:9090/ngsi-ld/v1/csourceRegistrations \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "description": "Provides information for my AirQualityObserved entities",
    "information": [
        {
            "entities": [
                {
                    "idPattern": ".*",
                    "type": "AirQualityObserved"
                }
            ],
            "properties": [
                "airQualityLevel",
                "temperature"
            ],
            "relationships": [
                "refPointOfInterest"
            ]
        }
    ],
    "endpoint": "http://my.ownbroker.org:1026",
    "@context": [
        "https://schema.lab.fiware.org/ld/context",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}'`

The response body:

`{
    "type": 400,
    "title": "Bad Request Data.",
    "detail": [
        "Bad Request Data."
    ]
}`

When providing the id attribute, the Csource registration is created successfully and the id is returned in the response body.

I tested with the latest commit https://github.com/ScorpioBroker/ScorpioBroker/commit/fb4a758068878e29998d31037da54133f374f2a6.

Greetings,
Michael

**Comment by ScorpioBroker** [comment]
Should be fixed by now.
Serializererror.

BR
Benjamin

**Comment by MS-Fiware** [comment]
Thanks also for this fix. Seems to be good now :)
