### ISSUE TITLE
Invalid URI in a relationship is not rejected

### ISSUE THREAD

**Issue by jason-fox** [ScorpioBroker/ScorpioBroker#62]
Related #59 

Specification states:

> 5.5.4 JSON-LD validation
> All the operations that take a JSON-LD document as input shall process such JSON-LD 
> document as follows:
> • If the request payload body is not a valid JSON document then an error of type InvalidRequest shall be raised.
> • If the data included by the JSON-LD document is not syntactically correct, according to the `@context`  or the API Data type definitions, then an error of type BadRequestData shall be raised. For the avoidance of doubt, this includes validation of member values in accordance with their data type, for instance DateTime, and validation of each Relationship's target object which shall be a syntactically valid URI. 

According to  [Microsoft](https://docs.microsoft.com/en-us/dotnet/api/system.uri.iswellformeduristring?redirectedfrom=MSDN&view=netframework-4.8#System_Uri_IsWellFormedUriString_System_String_System_UriKind_) - the following are invalid URIs:  

* `http://www.contoso.com/path???/file name`
* `c:\\directory\filename`
* `file://c:/directory/filename`
* `http:\\\host/path/file`
* `www.contoso.com/path/file`
* `2013.05.29_14:33:41`

However if I create or add a `Relationship`attribute as shown: 

```console
curl -X POST \
  http://localhost:9090/ngsi-ld/v1/entities/urn:ngsi-ld:Shelf:unit001/attrs \
  -H 'Content-Type: application/ld+json' \
  -H 'fiware-servicepath: /' \
  -d '{
    "uri": {
      "type": "Relationship",
      "object": "file://c:/directory/filename"
    },
    "@context": "https://fiware.github.io/tutorials.Step-by-Step/data-models-context.jsonld"
}'
````

The attribute is added with an invalid URI. The expected behaviour is `BadRequestData`

**Comment by ScorpioBroker** [comment]
Hi Jason,

I looked into this and it seems to me that MS is not considering this file://c:/directory/filename a valid uri because it doesn't work in some windows versions like this. It's requiring another / (even though in Win10 also without the 3rd / before c: does work). However in terms of uri rfc (https://tools.ietf.org/html/rfc3986) compliance this is a valid uri. 

i checked with the examples from ms

    http://www.contoso.com/path???/file name (is not valid and throws and error as should because of the space)
    c:\\directory\filename (is not valid and throws error because \ is an invalid char)
    file://c:/directory/filename (is valid)
    http:\\\host/path/file (again not valid because of \)
    www.contoso.com/path/file (is valid)
    2013.05.29_14:33:41(is not valid and throws an error)

**Comment by jason-fox** [comment]
So it just so happens that the one I picked from the list happens to be the one exception here.  😄 

Feel free to close if you don't want to implement any further changes
