### ISSUE TITLE
No validation of member values in accordance with their data type

### ISSUE THREAD

**Issue by jason-fox** [ScorpioBroker/ScorpioBroker#63]
Specification states:

> 5.5.4 JSON-LD validation
> All the operations that take a JSON-LD document as input shall process such JSON-LD 
> document as follows:
> • If the request payload body is not a valid JSON document then an error of type InvalidRequest shall be raised.
> • If the data included by the JSON-LD document is not syntactically correct, according to the `@context`  or the API Data type definitions, then an error of type BadRequestData shall be raised. For the avoidance of doubt, this includes validation of member values in accordance with their data type, for instance DateTime, and validation of each Relationship's target object which shall be a syntactically valid URI. 

The following is therefore *invalid*  since the datetime is not a date - but parses correctly.

```console
curl -X POST \
  'http://localhost:9090/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Building:something",
    "type": "Building",
    "sillyDate": {
    "type": "Property",
    "value": {
        "@type": "DateTime",
        "@value": "" 
    }
  },
    "@context": "https://fiware.github.io/tutorials.Step-by-Step/data-models-context.jsonld"
}'
```

it should return `BadRequestData`

**Comment by ScorpioBroker** [comment]
Hi,

i looked a bit through this and talked with martin about it. Basically the specs needs a bit of an update here to avoid confusion. JSON-LD validation of @type validates the structure of a json attribute not the contents of @value fields. GeoProperty TimeProperty and Relationship have well defined value/id fields in the spec hence they get validated. but value of Property is a free form field even with the typed values. Type can't be used to validate the content of values.

**Comment by martin-p-bauer** [comment]
General difficulty is that JSON-LD allows me to put whatever URI I want as a type - this does not mean that I am actually in a position to validate whether the value adheres to this type (where is it even defined?) So this turns out to be a problem ...

**Comment by ScorpioBroker** [comment]
As this isn't further addressed i'll close this till there is a spec update. Then we will add an enhancement issue.
