### ISSUE TITLE
"Bad Request Data" on discovering context source registrations (GET /csourceRegistrations)

### ISSUE THREAD

**Issue by MS-Fiware** [ScorpioBroker/ScorpioBroker#7]
Hi,

when trying to retrieve all context source registrations with GET /csourceRegistrations I get a "400 Bad Request Data" in the HTTP response.

My request:

`curl -X GET \
  http://192.168.57.101:9090/ngsi-ld/v1/csourceRegistrations \
  -H 'Accept: application/ld+json' \
  -H 'Link: <https://schema.lab.fiware.org/ld/context>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' `

The response body:

`{
    "type": 400,
    "title": "Bad Request Data.",
    "detail": [
        "Bad Request Data."
    ]
}`

I tested with the latest commit https://github.com/ScorpioBroker/ScorpioBroker/commit/fb4a758068878e29998d31037da54133f374f2a6.

Greetings,
Michael

**Comment by ScorpioBroker** [comment]
Hi,

we have done it like this because chapter 5.10.2.4 states "If neither Entity types nor Attribute names are provided, an error of type BadRequestData shall be raised." for the API interaction with the CSourceRegistry. 
Best Regards
Benjamin

**Comment by MS-Fiware** [comment]
Thanks for the hint. I skipped that text passage in the spec. 

I added `?type=<Entity_Type_For_Which_Information_Is_To_Be_Retrieved_From_The_Csource>` to the query string and it works now. :)
