### ISSUE TITLE
Long name not returned as part of the default context when included in the previous create statement 

### ISSUE THREAD

**Issue by jason-fox** [ScorpioBroker/ScorpioBroker#73]
Scorpio 0.9.7 - Possibly related to #61 

I have a jsonld context including `category` defined as shown.

```jsonld
"category": { 
      "@id" :"fiware:category",
      "@type": "@vocab"
    }, 
```

I create a Store 

```console
curl -X POST \
  'http://localhost:9090/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Building:store001",
    "type": "Building",
    "category": {"type": "Property", "value": ["commercial"]},
    "address": {
      "type": "Property", 
      "value": {"streetAddress": "Bornholmer Straße 65", "addressRegion": "Berlin", "addressLocality": "Prenzlauer Berg", "postalCode": "10439"},
      "verified": {"type": "Property", "value": true}
    },
    "location": {"type": "GeoProperty", "value": {"type": "Point", "coordinates": [13.3986, 52.5547]}
    },
    "name": {"type": "Property", "value": "Bösebrücke Einkauf"},
    "furniture": {
      "type": "Relationship", "object": [ "urn:ngsi-ld:Shelf:unit001", "urn:ngsi-ld:Shelf:unit002", "urn:ngsi-ld:Shelf:unit003"]
    },
    "@context": "https://fiware.github.io/tutorials.Step-by-Step/tutorials-context.jsonld"
}'
```

I retrieve the  Store without defining an `@context`

```console
curl -L -X GET 'http://localhost:9090/ngsi-ld/v1/entities/urn:ngsi-ld:Building:store001/' \
-H 'Content-Type: application/ld+json'
```

`category` is  returned within the default context, even though it was defined in the previous request. 

```jsonld
 "https://uri.fiware.org/ns/data-models#category": {
    "type": "Property",
    "value": "commercial"
  },
```

**Note:** - this could be to do with the `@vocab` element, but I'd expect the  long name to be returned since the `@id` was defined.

**Comment by ScorpioBroker** [comment]
Hi,

the broker doesn't store any context which was provided during the creation. If you don't provide the right context things are returned in an expanded form. You have to provide the at context fitting to what you want as output.
A generic approach to stored default contexts for entities is not possible since this will have inconsistencies when different people work on the same entity.
The only default you can expect when not providing an at context is the core context (5.5.5 )
