### ISSUE TITLE
Property compaction for an attribute with an attribute where type  is defined as an xsd:integer

### ISSUE THREAD

**Issue by jason-fox** [ScorpioBroker/ScorpioBroker#74]
Scorpio 0.9.7.

I create a Shelf using the following `@context`

```jsonld
"tutorial": "https://fiware.github.io/tutorials.Step-by-Step/schema/",
 "stocks": {
      "@id": "tutorial:stocks",   
      "@type": "@id"
    },
  "numberOfItems":  {
      "@id": "tutorial:numberOfItems",
      "@type": "xsd:integer"
    },
    "maxCapacity":  {
      "@id": "tutorial:maxCapacity",
      "@type": "xsd:integer"
    },
```

```console
curl -s -o /dev/null -X POST \
  'http://localhost:9090/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit001",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point", "coordinates": [13.3986112,52.554699]}
    },
    "maxCapacity": {"type": "Property", "value": 50},
    "numberOfItems": {"type": "Property", "value": 50},
    "name": {"type": "Property", "value": "Corner Unit"},
    "stocks": {
      "type": "Relationship", "object": "urn:ngsi-ld:Product:001"
    },
    "locatedIn" : {
      "type": "Relationship", "object": "urn:ngsi-ld:Building:store001",
      "requestedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:bob-the-manager"},
      "installedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:employee001"},
      "statusOfWork": {"type": "Property", "value": "completed"}
    },
    "@context": "https://fiware.github.io/tutorials.Step-by-Step/tutorials-context.jsonld"
}'
```

Retrieving the  Shelf  with short names does not  fully reduce the Properties defined with an ` "@type"` =\= `"@id"`.

```console
curl -L -X GET 'http://localhost:9090/ngsi-ld/v1/entities/urn:ngsi-ld:Shelf:unit001' \
-H 'Link: <https://fiware.github.io/tutorials.Step-by-Step/tutorials-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
-H 'Content-Type: application/ld+json'
```

```jsonld
{
  "id": "urn:ngsi-ld:Shelf:unit001",
  "type": "Shelf",
  "locatedIn": {
    "type": "Relationship",
    "installedBy": {
      "type": "Relationship",
      "object": "urn:ngsi-ld:Person:employee001"
    },
    "requestedBy": {
      "type": "Relationship",
      "object": "urn:ngsi-ld:Person:bob-the-manager"
    },
    "tutorial:statusOfWork": {
      "type": "Property",
      "value": "completed"
    },
    "object": "urn:ngsi-ld:Building:store001"
  },
  "tutorial:maxCapacity": {
    "type": "Property",
    "value": 50
  },
  "tutorial:numberOfItems": {
    "type": "Property",
    "value": 15
  },
  "stocks": {
    "type": "Relationship",
    "object": "urn:ngsi-ld:Product:001"
  },
  "location": {
    "type": "GeoProperty",
    "value": {
      "type": "Point",
      "coordinates": [
        13.3986112,
        52.554699
      ]
    }
  },
  "name": {
    "type": "Property",
    "value": "Corner Unit"
  },
  "@context": [
    "https://fiware.github.io/tutorials.Step-by-Step/tutorials-context.jsonld",
    "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
  ]
}
```

It is probably the `@context`  which is incorrect, but the question remains, how to define the property as an integer within the context and ensure that full compaction takes place.

**Comment by ScorpioBroker** [comment]
Hi,

so i searched a bt and found this https://github.com/json-ld/json-ld.org/issues/495 
from what i got you can't use type like this. when i said the type to id it also compacts properly again.
If i get you right you want to enforce that that attribute has to be an int? I think you can't on this level. @type would be normally the place for this in a raw jsonld setup but in ngsi-ld this is predefined as property or relationship and you are only providing the value basically. And you can't really restrict the value type like this since someone else might put something else in there.

**Comment by jason-fox** [comment]
Well, not a bug in Scorpio, but a bug in the ESTI spec.

I knew my idea of using:

```jsonld
"maxCapacity":  {
      "@id": "tutorial:maxCapacity",
      "@type": "xsd:integer"
    }, 
```

Came from somewhere. If you look in the Spec **Appendix C.6 Date Representation**, the spec suggests that:
 
> In addition, it is recommended that in the @context JSON-LD declaration of Properties which value is a time value to include a declaration of the form:
> 
> ```jsonld
> "testedAt": {
> 	 "@type": "https://uri.etsi.org/ngsi-ld/DateTime”,
>         "@id": "http://example.org/test/P1"
> }
> ```
> 

Which is **wrong** isn’t it (invalid JSON-LD)? 


- ` testedAt` is a **Property**
-  `maxCapacity` is a **Property**

-  `testedAt.value` is a **Datetime**
- `maxCapacity.value` is an **Integer**

So _technically_  you are not following the spec, because the spec is asking for the impossible. 😄

**Comment by ScorpioBroker** [comment]
Hi,

so this is a faulty example in the none normative appendix of the spec. I forwarded the problem. Since this is something to fix by ETSI i'll close this now.
