### ISSUE TITLE
"Not Found" on csource registration subscription (POST /csourceSubscriptions)

### ISSUE THREAD

**Issue by MS-Fiware** [ScorpioBroker/ScorpioBroker#8]
Hi,

when trying to create a context source registration subscription with POST /csourceSubscriptions I get a "400 Not Found" in the HTTP response.

My request:

`curl -X POST \
  http://192.168.57.101:9090/ngsi-ld/v1/csourceSubscriptions \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Subscription:MyAwesomeCsourceSubscription",
    "type": "Subscription",
    "description": "Notifies me of all context source registrations for entities I'\''m interested in",
    "entities": [
        {
            "idPattern": ".*",
            "type": "AirQualityObserved"
        }
    ],
    "watchedAttributes": [],
    "notification": {
        "attributes": [],
        "format": "keyValues",
        "endpoint": {
            "uri": "http://localhost:8080/csource-subscription/air-quality-csource-registered",
            "accept": "application/ld+json"
        }
    },
    "@context": [
        "https://schema.lab.fiware.org/ld/context",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}'`

The response body:

`{
    "timestamp": "2019-10-01T15:08:00.823+0000",
    "status": 404,
    "error": "Not Found",
    "message": "No message available",
    "path": "/ngsi-ld/v1/csourceSubscriptions"
}`

I assume that such a response is returned for every not yet implemented kind of request?
Can you provide some sort of overview (e.g. table, chart, ...) of what is currently implemented and what not?

I tested with the latest commit https://github.com/ScorpioBroker/ScorpioBroker/commit/fb4a758068878e29998d31037da54133f374f2a6.

Greetings,
Michael

**Comment by ScorpioBroker** [comment]
Hi,

this is implemented unfortunately a typo made into the commit it should be fixed now.

Regards
Benjamin

**Comment by MS-Fiware** [comment]
Thanks, works like a charm. Keep up the good work! :)
